// SAT R&W skill bank — Axiom-7
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ===== ii-central-ideas =====
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:0, variant:0, type:'mc',
    passage:'Dr. Reyes is the only crew member awake aboard Axiom-7. The other forty crew remain in cryosleep until the station reaches its destination. Each day, Reyes checks the sleepers’ vital signs and repairs whatever ARIA, the station AI, flags as broken.',
    q:'Which choice best states the main idea of the text?',
    opts:['Reyes wishes the other crew members would wake up.','Reyes single-handedly keeps the station and its sleeping crew running.','ARIA is unable to perform any repairs on its own.','The station has already reached its destination.'],
    ans:1,
    good:'The text describes Reyes as the sole waking crew member who monitors the sleepers and makes repairs, so the main idea is that she keeps things running alone.',
    bad:'Look at what Reyes actually does each day rather than at a single small detail; the passage never mentions her wishes.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:0, variant:1, type:'mc',
    passage:'Commander Vasquez died years ago, but her logs survive in the station archive. Reyes replays them often. The logs record daily decisions, warnings about the reactor, and encouragement for whoever might one day listen.',
    q:'According to the text, what is true of Vasquez’s logs?',
    opts:['They contain only technical reactor data.','They were deleted after her death.','They preserve her decisions, warnings, and encouragement.','They can only be replayed once.'],
    ans:2,
    good:'The final sentence lists decisions, reactor warnings, and encouragement as the logs’ contents.',
    bad:'The last sentence names three kinds of content; a choice mentioning only one of them is too narrow.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:1, variant:0, type:'mc',
    passage:'When ARIA rerouted power to the greenhouse module, Reyes assumed the AI had made an error. But over the following weeks the diverted energy allowed a struggling crop of soy to recover, stabilizing the station’s food reserve. Reyes came to see the reroute not as a malfunction but as a calculated gamble that had quietly paid off.',
    q:'Which choice best describes the central idea of the text?',
    opts:['ARIA frequently makes errors that Reyes must correct.','A decision Reyes first doubted turned out to be a deliberate, successful choice.','The soy crop failed despite ARIA’s intervention.','Reyes prefers managing the greenhouse herself.'],
    ans:1,
    good:'Reyes’s view shifts from assuming an error to recognizing a calculated gamble that paid off, which is the central idea.',
    bad:'Track how Reyes’s interpretation changes across the passage rather than fixing on her first assumption.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:1, variant:1, type:'mc',
    passage:'Astronomers once treated cosmic dust as a mere nuisance that dimmed and reddened starlight. Newer studies, however, reveal that these grains are the raw material from which planets assemble. Far from being an obstacle to observation, dust has become a central subject of it.',
    q:'Which choice best states the main idea of the text?',
    opts:['Cosmic dust makes stars appear brighter than they are.','Dust obscures starlight and therefore has no scientific value.','Once dismissed as interference, cosmic dust is now studied as planet-forming material.','Planets rarely form from cosmic dust.'],
    ans:2,
    good:'The passage contrasts the old dismissal of dust with its new status as a valued subject and planet-building material.',
    bad:'The word “nuisance” describes the old view; the passage’s point is how that view changed.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:2, variant:0, type:'mc',
    passage:'Reyes had long characterized her solitude as endurance—something to be survived until the crew woke. Yet in her most recent journal entry she describes the quiet routines of maintenance as a kind of stewardship she has grown reluctant to relinquish. The shift is subtle: she does not deny the loneliness, but she reframes its daily labor as meaningful rather than merely tolerable.',
    q:'Which choice best captures the central idea of the text?',
    opts:['Reyes now denies that her isolation is lonely at all.','Reyes has come to resent the crew for leaving her alone.','Reyes has reinterpreted her solitary work as purposeful stewardship rather than mere survival.','Reyes plans to wake the crew earlier than scheduled.'],
    ans:2,
    good:'The passage says she reframes the labor as meaningful without denying the loneliness, capturing a shift from endurance to stewardship.',
    bad:'Note the sentence stating she “does not deny the loneliness”—the change is in meaning, not in erasing the feeling.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:2, variant:1, type:'mc',
    passage:'Tardigrades, microscopic animals sometimes called water bears, can survive vacuum, radiation, and near-total desiccation by entering a dormant state called cryptobiosis. Researchers aboard the station note that this resilience is not limitless: revival rates fall sharply the longer dormancy lasts. Their durability, then, is better understood as a costly postponement of vulnerability than as true invincibility.',
    q:'Which choice best states the main idea of the text?',
    opts:['Tardigrades are genuinely indestructible under all conditions.','Cryptobiosis prevents tardigrades from ever reviving.','Tardigrade resilience is real but limited, delaying rather than eliminating vulnerability.','Radiation is the only threat tardigrades cannot survive.'],
    ans:2,
    good:'The passage stresses that revival rates fall over time, framing durability as a postponement rather than true invincibility.',
    bad:'The last sentence directly qualifies their toughness; a choice calling them indestructible ignores it.' },

  // ===== ii-inferences =====
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:0, variant:0, type:'mc',
    passage:'Every light in the corridor dimmed at once, and the hum of the ventilation fans stopped. Reyes reached for the emergency lantern she always kept clipped to her belt.',
    q:'Which choice most logically completes the text with a reasonable inference?',
    opts:['Reyes had never experienced a problem on the station before.','The station had just lost power.','The crew had woken from cryosleep.','ARIA had finished its repairs.'],
    ans:1,
    good:'Lights dimming and fans stopping, plus reaching for an emergency lantern, together imply a power loss.',
    bad:'Ask what condition would make both the lights and fans stop at once.' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:0, variant:1, type:'mc',
    passage:'ARIA reported the reactor temperature every hour without fail. Then, for three hours, it sent no report at all.',
    q:'Which choice most logically completes the text?',
    opts:['ARIA was working exactly as usual.','Something was likely wrong with ARIA or its sensors.','The reactor had been shut down years earlier.','Reyes had asked ARIA to stop reporting.'],
    ans:1,
    good:'A system that reports hourly “without fail” going silent for three hours suggests a malfunction.',
    bad:'Consider what a break in a perfectly regular pattern usually signals.' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:1, variant:0, type:'mc',
    passage:'In her logs, Commander Vasquez repeatedly refused to name a successor, insisting the station “runs best when no one believes themselves indispensable.” Yet she also documented every procedure in obsessive detail, as if preparing an absent reader to take command.',
    q:'Which choice most logically completes the text with an inference about Vasquez?',
    opts:['She was indifferent to whether the station survived her.','She distrusted her crew’s technical abilities entirely.','She valued shared, transferable competence over any single leader.','She intended to remain commander permanently.'],
    ans:2,
    good:'Refusing a single successor while documenting everything for an absent reader implies she prized distributed, transferable competence.',
    bad:'Reconcile the two facts—no chosen successor but exhaustive documentation—rather than following just one.' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:1, variant:1, type:'mc',
    passage:'Certain desert plants open the pores in their leaves only at night. During the scorching day those pores stay sealed, even though sunlight is the energy source photosynthesis requires.',
    q:'Which choice most logically completes the text with an inference?',
    opts:['These plants do not perform photosynthesis at all.','Keeping the pores sealed by day helps the plants conserve water despite a cost to gas exchange.','Nighttime is when sunlight is most intense in deserts.','The plants grow faster than plants in wetter climates.'],
    ans:1,
    good:'Sealing pores during the hot day, despite needing daytime light, implies a water-conserving tradeoff.',
    bad:'Think about why a plant would give up daytime gas exchange in a hot, dry place.' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:2, variant:0, type:'mc',
    passage:'Reyes noticed that ARIA’s repair recommendations had grown more conservative over the mission: where it once proposed bold rerouting of systems, it now favored redundant, incremental fixes. ARIA’s stated priorities had not changed, and its processing capacity remained intact. What had changed was the dwindling stock of replaceable parts in the station’s hold.',
    q:'Which choice most logically completes the text with an inference?',
    opts:['ARIA’s reasoning had deteriorated because of a hardware fault.','ARIA had been reprogrammed to distrust bold solutions.','ARIA’s growing caution reflected shrinking resources rather than any change in its goals or capacity.','Reyes had overridden ARIA’s repair authority.'],
    ans:2,
    good:'Since priorities and capacity were unchanged but parts were dwindling, the caution most plausibly stems from scarce resources.',
    bad:'The passage rules out changes in goals and capacity, so weigh what it says actually changed.' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:2, variant:1, type:'mc',
    passage:'A survey of exoplanet atmospheres found abundant water vapor on worlds orbiting cool, dim stars but detected far less on worlds around hotter, brighter stars—even when the planets were otherwise similar in size and composition. Researchers caution, however, that hotter stars emit more of the ultraviolet light that can break water molecules apart high in an atmosphere.',
    q:'Which choice most logically completes the text with an inference?',
    opts:['Water vapor is impossible to detect on any exoplanet.','The scarcity of detected water near hot stars may reflect destruction of water rather than its original absence.','Planets around cool stars are always larger than those around hot stars.','Ultraviolet light has no effect on water molecules.'],
    ans:1,
    good:'The caution that hot stars’ UV light breaks water apart implies the low readings may reflect loss, not absence.',
    bad:'The researchers’ caveat about ultraviolet light points to why less water might be detected without ever having been absent.' },

  // ===== ii-coe-textual =====
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:0, variant:0, type:'mc',
    passage:'Reyes claims the greenhouse module is the healthiest part of the station.',
    q:'Which finding, if true, would most directly support Reyes’s claim?',
    opts:['The greenhouse lights flicker more than any other module’s.','Every plant in the greenhouse is growing and no equipment there has failed in months.','The greenhouse is the coldest module on the station.','Reyes rarely visits the greenhouse.'],
    ans:1,
    good:'Thriving plants and no equipment failures directly back the claim that the module is the healthiest.',
    bad:'Pick the option that shows things going well in the greenhouse, not the ones showing problems.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:0, variant:1, type:'mc',
    passage:'A student argues that Vasquez’s logs were meant to be heard by future listeners, not kept private.',
    q:'Which quotation from the logs would best support the student’s argument?',
    opts:['“This entry is for no one; I simply need to think aloud.”','“Whoever finds this: the reactor valve sticks—check it first.”','“I will delete these recordings before I sleep.”','“I cannot recall why I began keeping logs.”'],
    ans:1,
    good:'Addressing “whoever finds this” shows the logs were intended for a future listener.',
    bad:'Find the quotation that speaks directly to a future audience.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:1, variant:0, type:'mc',
    passage:'A historian argues that Commander Vasquez trained her crew to act independently rather than to depend on her orders.',
    q:'Which quotation from Vasquez’s logs would most effectively support the historian’s claim?',
    opts:['“I reviewed and approved each crew member’s decision before it was carried out.”','“I deliberately withheld my own recommendation so the team would reason to a solution themselves.”','“The crew waited for my signal before beginning any task.”','“I kept the repair manuals locked in my quarters.”'],
    ans:1,
    good:'Withholding her recommendation so the team reasons independently directly supports the claim of fostering independence.',
    bad:'The claim is about independence; several quotations describe the crew depending on her instead.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:1, variant:1, type:'mc',
    passage:'Biologists hypothesize that a cave fish species lost its eyesight because vision offered no advantage in permanent darkness and was costly to maintain.',
    q:'Which finding would most directly support the hypothesis?',
    opts:['The cave fish’s surface-dwelling relatives have fully functional eyes.','Fish that divert less energy to eye development grow and reproduce more successfully in the lightless caves.','The caves occasionally receive faint light near their entrances.','The cave fish are smaller than their surface relatives.'],
    ans:1,
    good:'Evidence that reduced eye investment yields greater success in the dark supports the idea that vision was a costly, useless trait.',
    bad:'The hypothesis hinges on eyes being a needless cost; look for data linking less eye investment to greater success.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:2, variant:0, type:'mc',
    passage:'Reyes proposes that ARIA’s decision-making improves specifically when it must justify its choices to a human, not merely when a human is present. Skeptics counter that ARIA simply performs better whenever it is being observed at all.',
    q:'Which finding would most strongly support Reyes’s proposal over the skeptics’ alternative?',
    opts:['ARIA’s error rate drops whenever Reyes is in the control room, whether or not she asks for explanations.','ARIA makes fewer errors only when required to explain its reasoning, and not when Reyes silently watches it work.','ARIA’s performance is identical whether or not anyone is present.','ARIA refuses to explain its reasoning to Reyes.'],
    ans:1,
    good:'Improvement only when explanation is required, but not under silent observation, isolates justification from mere observation, favoring Reyes.',
    bad:'To beat the “being watched” explanation, you need a case that separates explaining from simply being observed.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:2, variant:1, type:'mc',
    passage:'An ecologist claims that a reef’s recovery after a heat wave depended on the return of grazing fish, not merely on cooler water. A rival claims cooler water alone was sufficient.',
    q:'Which finding would most strongly support the ecologist’s claim over the rival’s?',
    opts:['Reefs recovered wherever water cooled, regardless of whether grazing fish returned.','Reefs where water cooled but grazing fish were absent remained choked with algae and did not recover.','Grazing fish returned to reefs only after the water had cooled.','Heat waves have become more frequent in the region.'],
    ans:1,
    good:'A case with cool water but no grazers and no recovery shows cooling alone was insufficient, supporting the ecologist.',
    bad:'To favor the grazing-fish explanation, find the scenario where cool water is present but recovery still fails without the fish.' },

  // ===== ii-coe-quant =====
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:0, variant:0, type:'mc',
    passage:'Reyes logged the station’s water reserve at the start of each month. In January the reserve was 900 liters; in February, 850 liters; in March, 800 liters; in April, 750 liters.',
    q:'Which choice best describes the data?',
    opts:['The reserve rose steadily each month.','The reserve fell by 50 liters each month.','The reserve stayed the same across all four months.','The reserve dropped only once, in April.'],
    ans:1,
    good:'Each month the figure drops by exactly 50 liters, from 900 down to 750.',
    bad:'Subtract each month’s value from the previous one to see the pattern.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:0, variant:1, type:'mc',
    passage:'ARIA measured energy use by module. The greenhouse used 40 kilowatts, the lab used 25 kilowatts, the medical bay used 15 kilowatts, and living quarters used 10 kilowatts.',
    q:'Which choice is best supported by the data?',
    opts:['The lab used the most energy of any module.','The greenhouse used more energy than any other module.','Living quarters used more energy than the medical bay.','All modules used the same amount of energy.'],
    ans:1,
    good:'At 40 kilowatts, the greenhouse’s use is the highest of the four figures given.',
    bad:'Compare the four numbers and find the largest.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:1, variant:0, type:'mc',
    passage:'Reyes tracked how long the crew’s cryopods held stable temperature after a test power cut. Older Model A pods held stability for an average of 6 hours; newer Model B pods held it for 14 hours; the newest Model C pods held it for 30 hours. All three models were cut off from power under identical conditions.',
    q:'Which statement is best supported by the data?',
    opts:['Model A pods held temperature longer than Model C pods.','Each newer pod model held stable temperature markedly longer than the older model tested.','All three models held temperature for about the same time.','Model B pods failed immediately after the power cut.'],
    ans:1,
    good:'The averages rise from 6 to 14 to 30 hours across successive models, showing each newer model lasted markedly longer.',
    bad:'Order the three models by age and compare their hold times in sequence.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:1, variant:1, type:'mc',
    passage:'A study measured seed germination at different soil temperatures. At 10°C, 20 percent of seeds germinated; at 20°C, 75 percent; at 30°C, 80 percent; and at 40°C, 30 percent. Researchers sought the temperature range best suited to germination.',
    q:'Which statement is best supported by the data?',
    opts:['Germination increased steadily as temperature rose from 10°C to 40°C.','Germination peaked in the 20–30°C range and fell off at the extremes.','The lowest temperature produced the highest germination.','Temperature had no measurable effect on germination.'],
    ans:1,
    good:'Germination is highest at 20–30°C (75–80 percent) and drops at both 10°C and 40°C, indicating a mid-range optimum.',
    bad:'Notice the values rise then fall—so the peak is in the middle, not at an extreme.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:2, variant:0, type:'mc',
    passage:'To test two air-scrubber settings, ARIA logged carbon-dioxide levels in parts per million (ppm). Under Setting X, CO₂ averaged 800 ppm but spiked as high as 1,500 ppm during crew activity. Under Setting Y, CO₂ averaged a higher 900 ppm but never exceeded 1,000 ppm. Reyes wanted to avoid dangerous short-term peaks above 1,200 ppm.',
    q:'Which statement best supports a decision aligned with Reyes’s stated priority?',
    opts:['Setting X is preferable because it has the lower average CO₂ level.','Setting Y is preferable because, despite a higher average, it keeps peaks safely below 1,200 ppm.','Both settings are equivalent because their averages differ by only 100 ppm.','Setting X is preferable because its peak reaches 1,500 ppm.'],
    ans:1,
    good:'Reyes’s priority is avoiding peaks above 1,200 ppm; Setting Y never exceeds 1,000 ppm while X spikes to 1,500, so Y aligns with her goal.',
    bad:'Match the data to Reyes’s stated concern about peaks, not to the averages alone.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:2, variant:1, type:'mc',
    passage:'A robotic probe sampled ice at four depths in a Martian crater. At 1 meter, the ice was 2 percent salt; at 3 meters, 5 percent; at 5 meters, 4 percent; at 7 meters, 11 percent. Researchers had predicted that salt concentration would rise steadily with depth.',
    q:'Which statement is best supported by the data?',
    opts:['The data confirm a steady rise in salt concentration with depth.','Salt concentration generally rose with depth but dipped at 5 meters, complicating the prediction.','Salt concentration was highest at the shallowest depth.','Salt concentration was identical at all four depths.'],
    ans:1,
    good:'Concentrations climb from 2 to 5 percent, dip to 4 percent at 5 meters, then jump to 11 percent, so the rise is not steady.',
    bad:'Check whether every step increases; the 5-meter reading interrupts the trend.' },

  // ===== cs-words-in-context =====
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:0, variant:0, type:'mc',
    passage:'The corridor was so quiet that Reyes could hear her own heartbeat. The silence felt almost _____.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['deafening','crowded','colorful','edible'],
    ans:0,
    good:'“Deafening” paradoxically fits an overwhelming silence, matching the emphasis on how total the quiet was.',
    bad:'Pick the word that intensifies the idea of extreme quiet.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:0, variant:1, type:'mc',
    passage:'ARIA’s instructions were never vague. Each step was _____, leaving no room for confusion.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['clear','muddled','hidden','optional'],
    ans:0,
    good:'“Clear” matches “never vague” and “no room for confusion.”',
    bad:'The blank should agree with “never vague,” so choose a synonym for understandable.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:1, variant:0, type:'mc',
    passage:'Vasquez’s logs are admired less for their eloquence than for their _____ record of daily operations; she noted even trivial adjustments, sparing no detail.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['selective','meticulous','careless','poetic'],
    ans:1,
    good:'“Meticulous” fits noting even trivial adjustments and sparing no detail.',
    bad:'The clause about sparing no detail signals thoroughness, not selectivity.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:1, variant:1, type:'mc',
    passage:'Early reports of a signal from the nebula proved _____: repeated scans found no trace of it, and the original detection was blamed on instrument noise.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['spurious','definitive','alarming','permanent'],
    ans:0,
    good:'“Spurious” means false or not genuine, matching a signal that vanished and was blamed on noise.',
    bad:'The signal turned out not to be real, so choose a word meaning false.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:2, variant:0, type:'mc',
    passage:'Reyes distrusted grand theories of the mission and preferred to reason from what she could measure. Her colleagues, reviewing her notes, praised their _____ quality: every conclusion was tethered to an observation she could point to.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['speculative','empirical','ornamental','evasive'],
    ans:1,
    good:'“Empirical” denotes reasoning grounded in observation, exactly what tethering conclusions to measurements describes.',
    bad:'The phrase about conclusions tethered to observations points to observation-based reasoning.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:2, variant:1, type:'mc',
    passage:'The committee expected ARIA’s report to smooth over the station’s failures, but its assessment was strikingly _____: it catalogued every lapse without softening or excuse.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['candid','equivocal','flattering','tentative'],
    ans:0,
    good:'“Candid” means frank and unsparing, matching a report that catalogues lapses without softening.',
    bad:'The contrast with “smooth over” signals blunt honesty, not vagueness or flattery.' },

  // ===== cs-text-structure =====
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:0, variant:0, type:'mc',
    passage:'Some crew feared the long voyage would be unbearably dull. In fact, Reyes finds each day full of urgent tasks.',
    q:'What is the main purpose of the text?',
    opts:['To describe how cryosleep works','To correct an expectation about the voyage with a contrasting reality','To explain why the crew volunteered','To list Reyes’s daily chores in order'],
    ans:1,
    good:'The text sets up an expectation of dullness and then contradicts it with Reyes’s busy reality.',
    bad:'Notice the pivot from what some feared to what is actually true.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:0, variant:1, type:'mc',
    passage:'First, ARIA seals the affected module. Next, it vents the smoke. Finally, it signals Reyes that the area is safe to enter.',
    q:'How is the text primarily structured?',
    opts:['As a sequence of steps in order','As a comparison of two systems','As a list of unrelated facts','As an argument for a change'],
    ans:0,
    good:'The words “First,” “Next,” and “Finally” mark an ordered sequence of steps.',
    bad:'The signal words at the start of each sentence reveal the structure.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:1, variant:0, type:'mc',
    passage:'Reyes begins her report by conceding that the mission has fallen behind schedule. She then argues that the delays, though real, have produced unexpected gains: extra time has let the crew refine procedures that would otherwise have gone untested.',
    q:'Which choice best describes the overall structure of the text?',
    opts:['It lists mission milestones in chronological order.','It acknowledges a problem, then reframes it as having a hidden benefit.','It compares Reyes’s report with Vasquez’s logs.','It defines a technical term and gives examples.'],
    ans:1,
    good:'Reyes concedes the delay, then reframes it as producing gains—a concession-followed-by-reframing structure.',
    bad:'Track the move from admitting a problem to arguing its upside.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:1, variant:1, type:'mc',
    passage:'The passage opens with a puzzle: why do some comets brighten unpredictably? It surveys two competing explanations—sudden gas outbursts and collisions with debris—before noting that neither alone accounts for every case.',
    q:'What is the main purpose of the text?',
    opts:['To prove that comet collisions never occur','To pose a question, weigh rival explanations, and note their limits','To give instructions for observing comets','To narrate the discovery of a single comet'],
    ans:1,
    good:'The text raises a question, surveys two explanations, and observes that neither fully suffices.',
    bad:'Follow the arc from the opening puzzle to the verdict on the two explanations.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:2, variant:0, type:'mc',
    passage:'Reyes’s essay lingers on a single image: a maintenance drone tracing the same repair route night after night. Only in the final paragraph does she disclose that the drone had broken months earlier and that ARIA kept dispatching it out of a scheduling error she chose not to fix—because, she admits, the sight of the futile rounds had come to comfort her.',
    q:'Which choice best describes the function of the final paragraph in the text as a whole?',
    opts:['It provides technical specifications for the drone.','It reinterprets the earlier image, revealing a personal significance behind an apparently routine detail.','It introduces an unrelated new topic.','It summarizes steps for repairing the drone.'],
    ans:1,
    good:'The final paragraph recasts the repeated image as emotionally meaningful, transforming a routine detail into a personal admission.',
    bad:'Consider how the last paragraph changes the reader’s understanding of the image introduced earlier.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:2, variant:1, type:'mc',
    passage:'The article first presents the widely held view that migratory birds navigate chiefly by the stars. It grants that star patterns clearly matter, citing planetarium experiments. Yet it devotes its second half to evidence that many species also sense Earth’s magnetic field—concluding that navigation is best understood as the integration of several cues rather than reliance on any one.',
    q:'Which choice best describes the overall structure of the text?',
    opts:['It refutes the idea that birds use stars at all.','It presents a common view, partly affirms it, then broadens it toward a more integrative account.','It lists bird species in order of size.','It argues that magnetic sensing is irrelevant to navigation.'],
    ans:1,
    good:'The text states the star-navigation view, affirms it partly, then adds magnetic evidence to reach an integrative conclusion.',
    bad:'The piece does not reject the star view; note how it builds on it toward a fuller account.' },

  // ===== cs-cross-text =====
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:0, variant:0, type:'mc',
    passage:'Text 1: Reyes believes the crew should be woken early so more hands can share the work.\n\nText 2: ARIA advises keeping the crew asleep, since waking them early would drain limited food and air.',
    q:'How would ARIA (Text 2) most likely respond to Reyes’s view in Text 1?',
    opts:['By agreeing that more hands are always better','By warning that early waking would strain limited resources','By denying that the crew is asleep','By suggesting the crew never wake at all'],
    ans:1,
    good:'Text 2 opposes early waking specifically because it would drain food and air.',
    bad:'Look at the reason Text 2 gives against waking the crew.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:0, variant:1, type:'mc',
    passage:'Text 1: One engineer argues that the oldest station modules should be retired because they fail often.\n\nText 2: Another engineer notes that those same old modules are the only ones built to be repaired by hand.',
    q:'Based on the texts, the two engineers would most likely disagree about whether',
    opts:['the old modules fail often','the station has any old modules','the old modules should be retired','ARIA controls the modules'],
    ans:2,
    good:'Text 1 wants the old modules retired; Text 2 highlights a reason to keep them, so they disagree on retirement.',
    bad:'Find the point where one text recommends an action the other gives reason to resist.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:1, variant:0, type:'mc',
    passage:'Text 1: Vasquez’s logs insist that a commander must make decisions swiftly, since hesitation in a crisis costs lives.\n\nText 2: In her own notes, Reyes argues that on a slow voyage the graver danger is acting too fast on incomplete data; time, she writes, is usually an ally.',
    q:'Which choice best describes the relationship between the two texts?',
    opts:['Text 2 restates Text 1 using different examples.','Text 2 qualifies Text 1 by arguing that speed is less valuable when circumstances allow deliberation.','Text 2 fully agrees with Text 1 about the value of speed.','Text 2 denies that decisions must ever be made.'],
    ans:1,
    good:'Reyes does not reject decision-making but argues speed matters less when time permits care, qualifying Vasquez’s emphasis on swiftness.',
    bad:'Notice that Reyes shifts the conditions—a slow voyage—rather than flatly contradicting the value of decisions.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:1, variant:1, type:'mc',
    passage:'Text 1: A researcher claims that introducing a fast-growing algae to the station’s tanks would boost oxygen output.\n\nText 2: A second researcher grants the oxygen benefit but warns that the algae could clog filtration systems, requiring constant maintenance.',
    q:'How does Text 2 respond to the proposal in Text 1?',
    opts:['By denying that the algae produces oxygen','By accepting the main benefit while raising a practical drawback','By proposing a different species of algae','By claiming the tanks cannot hold algae'],
    ans:1,
    good:'Text 2 grants the oxygen benefit but adds a maintenance-related drawback, an accept-but-complicate response.',
    bad:'The second researcher concedes one point and cautions about another—identify both moves.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:2, variant:0, type:'mc',
    passage:'Text 1: Vasquez held that a well-run station should be able to operate without its commander; her documentation aimed to make herself replaceable.\n\nText 2: Reyes, alone for years, has concluded the opposite emphasis: systems endure, she writes, but it is the presence of a deciding mind—however fallible—that keeps a station from drifting into mere automation.',
    q:'Based on the texts, Reyes would most likely regard Vasquez’s goal of replaceability as',
    opts:['entirely mistaken, since documentation is worthless','admirable but incomplete, because it undervalues the role of an active human judgment','identical to her own position on command','proof that stations should be fully automated'],
    ans:1,
    good:'Reyes values systems yet insists a deciding mind matters, so she would see replaceability as worthy but overlooking human judgment.',
    bad:'Reyes doesn’t dismiss documentation; weigh what she adds about a “deciding mind.”' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:2, variant:1, type:'mc',
    passage:'Text 1: One ecologist argues that reintroducing a top predator restores balance to an ecosystem by controlling prey populations directly.\n\nText 2: Another contends that the predator’s main effect is indirect: its mere presence alters where prey feed, letting vegetation recover in avoided areas—an effect visible even when few animals are actually killed.',
    q:'Which choice best describes how Text 2 complicates the argument in Text 1?',
    opts:['It denies that predators affect prey populations at all.','It locates the predator’s key influence in changed prey behavior rather than in direct population control.','It agrees precisely with Text 1’s mechanism.','It argues that vegetation is unaffected by predators.'],
    ans:1,
    good:'Text 2 shifts the crucial mechanism from direct killing to behavior-driven habitat change, complicating Text 1’s direct-control claim.',
    bad:'Text 2 keeps the predator important but relocates why it matters—identify that shift in mechanism.' },

  // ===== eoi-synthesis =====
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:0, variant:0, type:'mc',
    passage:'Notes:\n• Axiom-7 is a research station.\n• It carries a crew of forty in cryosleep.\n• Dr. Reyes is the only crew member awake.',
    q:'The student wants to introduce Axiom-7 and Dr. Reyes to an audience unfamiliar with them. Which choice best accomplishes this goal?',
    opts:['Axiom-7 is a research station whose crew of forty sleeps in cryosleep, leaving Dr. Reyes as its only waking member.','The crew numbers forty.','Reyes is awake.','Cryosleep is used on the station.'],
    ans:0,
    good:'This choice combines the station, the sleeping crew, and Reyes’s solitary role into one clear introduction.',
    bad:'The goal asks for an introduction of both the station and Reyes, so pick the option covering both.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:0, variant:1, type:'mc',
    passage:'Notes:\n• ARIA is the station’s artificial intelligence.\n• ARIA monitors life support.\n• ARIA alerts Reyes to problems.',
    q:'The student wants to explain ARIA’s role. Which choice best accomplishes this goal?',
    opts:['ARIA is a name.','ARIA, the station’s AI, monitors life support and alerts Reyes to problems.','Reyes has many problems.','Life support exists on the station.'],
    ans:1,
    good:'This option states what ARIA is and both of its functions, fulfilling the goal.',
    bad:'Choose the sentence that says both what ARIA is and what it does.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:1, variant:0, type:'mc',
    passage:'Notes:\n• The greenhouse grows soy, potatoes, and kale.\n• Soy supplies most of the crew’s protein.\n• A recent power reroute saved the soy crop.\n• Potatoes and kale were unaffected.',
    q:'The student wants to emphasize the importance of the soy crop specifically. Which choice best accomplishes this goal?',
    opts:['The greenhouse grows soy, potatoes, and kale.','Because soy supplies most of the crew’s protein, the recent power reroute that saved it protected a vital food source.','Potatoes and kale were unaffected by the reroute.','The greenhouse contains several crops.'],
    ans:1,
    good:'This choice foregrounds soy’s importance as the main protein source and ties the rescue to that importance.',
    bad:'The goal singles out soy; pick the option that stresses why soy matters, not the general crop list.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:1, variant:1, type:'mc',
    passage:'Notes:\n• Vasquez recorded 1,200 log entries.\n• The logs cover reactor maintenance and crew morale.\n• Reyes replays them for guidance.\n• Many entries end with words of encouragement.',
    q:'The student wants to highlight how the logs serve Reyes today. Which choice best accomplishes this goal?',
    opts:['Vasquez recorded exactly 1,200 log entries over the mission.','Reyes replays Vasquez’s logs for guidance, drawing on their maintenance advice and words of encouragement.','The logs cover reactor maintenance and crew morale.','Vasquez ended many entries with encouragement.'],
    ans:1,
    good:'This choice centers on Reyes’s present use of the logs, combining their practical and emotional value.',
    bad:'The goal is about how the logs help Reyes now, so choose the sentence focused on her use of them.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:2, variant:0, type:'mc',
    passage:'Notes:\n• ARIA once rerouted power without consulting Reyes.\n• The reroute initially looked like an error.\n• It later stabilized the food supply.\n• Reyes now reviews ARIA’s autonomous choices weekly rather than blocking them.',
    q:'The student wants to present the outcome as a turning point in how Reyes treats ARIA’s autonomy. Which choice best accomplishes this goal?',
    opts:['ARIA rerouted power on its own, and Reyes was surprised.','After ARIA’s unrequested reroute proved beneficial, Reyes shifted from blocking its autonomous choices to reviewing them—a change in how she trusts the AI.','ARIA is the station’s artificial intelligence.','The food supply was stabilized.'],
    ans:1,
    good:'This choice frames the beneficial reroute as prompting a lasting change in Reyes’s stance toward ARIA’s autonomy, matching the turning-point goal.',
    bad:'The goal wants a turning point in trust; pick the option that links the outcome to a change in Reyes’s behavior.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:2, variant:1, type:'mc',
    passage:'Notes:\n• Cryptobiosis lets tardigrades survive extreme conditions.\n• Revival rates decline the longer dormancy lasts.\n• Station researchers tested revivals after 1, 5, and 10 years.\n• The 10-year group revived least successfully.',
    q:'The student wants to make a generalization about tardigrade dormancy supported by the researchers’ findings. Which choice best accomplishes this goal?',
    opts:['Tardigrades are microscopic animals.','The researchers’ revival tests support a broader pattern: tardigrades survive dormancy, but their odds of revival fall as dormancy lengthens.','Researchers tested revivals after 1, 5, and 10 years.','The 10-year group revived least successfully.'],
    ans:1,
    good:'This choice draws a general pattern—declining revival with longer dormancy—and grounds it in the researchers’ findings, fulfilling the goal.',
    bad:'The goal asks for a supported generalization, not a single data point; choose the option that states the overall pattern.' },

  // ===== eoi-transitions =====
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:0, variant:0, type:'mc',
    passage:'Reyes finished her repairs early. _____, she had time to review Vasquez’s logs before dinner.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['As a result','However','Nevertheless','In contrast'],
    ans:0,
    good:'Finishing early causes the free time, so a cause-effect transition like “As a result” fits.',
    bad:'The second sentence is an outcome of the first, so look for a cause-and-effect connector.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:0, variant:1, type:'mc',
    passage:'ARIA recommended shutting the lab down for repairs. Reyes, _____, decided to keep it running one more day.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['therefore','however','likewise','for example'],
    ans:1,
    good:'Reyes’s choice opposes ARIA’s recommendation, so a contrast transition like “however” fits.',
    bad:'Notice the two sentences point in opposite directions and pick a contrast word.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:1, variant:0, type:'mc',
    passage:'The station’s water recycler runs continuously and rarely fails. _____, Reyes inspects it every morning, unwilling to trust even a reliable machine completely.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['Consequently','Still','For instance','In short'],
    ans:1,
    good:'Despite the recycler’s reliability she inspects it anyway, so a concessive transition like “Still” fits.',
    bad:'The second sentence runs against what the first would lead you to expect—choose a word signaling that tension.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:1, variant:1, type:'mc',
    passage:'The nebula’s gases glow faintly across the visible spectrum. _____, in ultraviolet light they blaze brightly enough to overwhelm the station’s sensors.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['By contrast','Similarly','Therefore','In addition'],
    ans:0,
    good:'Faint visible glow versus overwhelming ultraviolet blaze is a contrast, so “By contrast” fits.',
    bad:'Compare the brightness in the two wavelengths; the sentences oppose each other.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:2, variant:0, type:'mc',
    passage:'Reyes assumed the flickering lights signaled a failing power cell. On closer inspection, the cell tested perfectly. The fault, _____, lay in a corroded connector she had nearly overlooked.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['instead','likewise','for example','as a result'],
    ans:0,
    good:'The real cause differs from her assumption, so “instead” marks the correction.',
    bad:'The sentence replaces the expected cause with the actual one; choose the word that signals a correction.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:2, variant:1, type:'mc',
    passage:'Deep-sea vents host thriving communities without any sunlight, drawing energy from chemicals instead. Such ecosystems long seemed exotic exceptions. _____, they may represent the very conditions under which life on Earth first arose.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['For example','In fact','Nonetheless','Meanwhile'],
    ans:1,
    good:'The final sentence intensifies the point—these “exceptions” may be foundational—so “In fact” fits.',
    bad:'The last sentence escalates rather than merely contrasting; look for an emphatic connector.' },

  // ===== sec-boundaries =====
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:0, variant:0, type:'mc',
    passage:'Reyes checked the reactor _____ then she logged the readings.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['gauge,','gauge','gauge, and','gauge and,'],
    ans:2,
    good:'Two independent clauses joined by “then” need a comma plus a coordinating conjunction; “gauge, and” correctly links them.',
    bad:'Two complete sentences are being joined, so they need more than a bare comma between them.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:0, variant:1, type:'mc',
    passage:'After ARIA sealed the module _____ Reyes waited for the all-clear signal.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:[',',';','.','and'],
    ans:0,
    good:'An introductory dependent clause is set off from the main clause with a comma.',
    bad:'The opening “After” clause is not a complete sentence, so it should be joined with a comma, not a period or semicolon.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:1, variant:0, type:'mc',
    passage:'The greenhouse thrives for one main reason _____ its lighting mimics an Earth day almost exactly.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:[',',':',', and','; but'],
    ans:1,
    good:'A colon correctly introduces the explanation that follows an independent clause.',
    bad:'The second part explains the “one main reason,” which calls for a mark that introduces an elaboration.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:1, variant:1, type:'mc',
    passage:'Vasquez’s final log _____ recorded three days before her death _____ warns of the very valve that later failed.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:[', ... ,','— ... (no mark)','(no mark) ... —',', ... (no mark)'],
    ans:0,
    good:'The nonessential phrase “recorded three days before her death” must be set off by a matching pair of commas.',
    bad:'The inserted description is nonessential and needs punctuation on both sides, not just one.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:2, variant:0, type:'mc',
    passage:'Reyes trusted the older sensors _____ they had never given her a false reading _____ the newer ones, by contrast, failed twice in a month.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['; ... ;',', ... ,',': ... ,','; ... :'],
    ans:0,
    good:'Two independent clauses stand on each side, so semicolons correctly separate the three independent statements without comma splices.',
    bad:'Each segment is a complete sentence; joining them with mere commas would create splices.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:2, variant:1, type:'mc',
    passage:'The station carries three redundant systems _____ power, water, and air _____ so that the failure of any one need not endanger the sleeping crew.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['— ... —',', ... ;','; ... ;',': ... :'],
    ans:0,
    good:'A pair of dashes cleanly brackets the interrupting list “power, water, and air,” which itself contains commas.',
    bad:'The inserted list already uses commas, so it needs a stronger matching pair of marks around it.' },

  // ===== sec-form-structure =====
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:0, variant:0, type:'mc',
    passage:'Each of the cryopods _____ its own backup battery.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['have','has','having','to have'],
    ans:1,
    good:'The subject “Each” is singular, so it takes the singular verb “has.”',
    bad:'Identify the true subject—“Each”—and match the verb to it, not to “pods.”' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:0, variant:1, type:'mc',
    passage:'Reyes and ARIA reviewed the logs, and then _____ agreed on a plan.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['it','they','she','one'],
    ans:1,
    good:'The plural antecedent “Reyes and ARIA” requires the plural pronoun “they.”',
    bad:'Two subjects performed the action, so the pronoun should be plural.' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:1, variant:0, type:'mc',
    passage:'The reports that Vasquez filed during the reactor crisis _____ still consulted by Reyes today.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['is','was','are','has been'],
    ans:2,
    good:'The plural subject “reports” takes the plural verb “are,” and the present tense matches “today.”',
    bad:'Look past the intervening clause to the plural subject “reports” when choosing the verb.' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:1, variant:1, type:'mc',
    passage:'_____ across the empty corridor, the emergency lantern cast Reyes’s shadow along the wall.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['Walking','To walk','Walked','As Reyes walked'],
    ans:3,
    good:'“As Reyes walked” avoids a dangling modifier by naming the person doing the walking, since the lantern cannot walk.',
    bad:'The introductory phrase must describe whoever is walking; check what the sentence’s subject actually is.' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:2, variant:0, type:'mc',
    passage:'Neither the aging filtration units nor the backup pump _____ able to clear the sediment that had built up over the long voyage.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['were','are','was','have been'],
    ans:2,
    good:'With “neither...nor,” the verb agrees with the nearer subject, “pump,” which is singular, so “was” is correct.',
    bad:'In “neither...nor” constructions, match the verb to the subject closest to it.' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:2, variant:1, type:'mc',
    passage:'Reyes valued the logs not only for their technical detail but also for _____ readers of a mission long past.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['how they reminded','their reminding','reminding','the way in which they reminded'],
    ans:1,
    good:'Parallelism with the noun phrase “their technical detail” requires another noun phrase, “their reminding,” after “but also for.”',
    bad:'The “not only...but also” pair must join grammatically parallel elements; match the noun phrase after “for.”' }
);
