// SAT Math: Problem-Solving & Data Analysis skill bank — Axiom-7
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ---------- psda-ratios ----------
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:0, variant:0, type:'input',
    q:'The oxygen-to-nitrogen canister ratio on Axiom-7 must be <strong>3 : 5</strong>. If there are 15 oxygen canisters, how many nitrogen canisters are needed?',
    ans:25, ph:'canisters = ?',
    good:'15 is 3 × 5, so nitrogen is 5 × 5 = 25.',
    bad:'Scale the ratio: 15/3 = 5, so nitrogen = 5 · 5 = 25.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:0, variant:1, type:'input',
    q:'A surface rover travels 180 km in 3 hours at constant speed. Enter its speed in km per hour.',
    ans:60, ph:'km/h = ?',
    good:'180 / 3 = 60 km/h. Rover on schedule.',
    bad:'Rate = distance / time = 180 / 3 = 60 km/h.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:1, variant:0, type:'input',
    q:'The crew-to-drone ratio on deck is <strong>3 : 7</strong>. If there are 40 crew and drones in total, how many are drones?',
    ans:28, ph:'drones = ?',
    good:'Each ratio unit is 40/10 = 4, so drones = 7 · 4 = 28.',
    bad:'3 + 7 = 10 parts; 40/10 = 4 per part; drones = 7 · 4 = 28.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:1, variant:1, type:'input',
    q:'The fabricator prints 42 hull parts in 6 hours at a constant rate. How many parts can it print in 10 hours?',
    ans:70, ph:'parts = ?',
    good:'42/6 = 7 parts per hour; 7 · 10 = 70.',
    bad:'Find the unit rate: 42/6 = 7 parts/hour, then 7 · 10 = 70.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:2, variant:0, type:'input',
    q:'In the hydroponics bay, nutrient A to B is <strong>2 : 3</strong> and B to C is <strong>4 : 5</strong>. If there are 24 units of A, how many units of C?',
    ans:45, ph:'units of C = ?',
    good:'A : B : C = 8 : 12 : 15. With A = 24 (3 × 8), C = 3 × 15 = 45.',
    bad:'Combine ratios: A:B:C = 8:12:15. Since A = 24 = 3·8, C = 3·15 = 45.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:2, variant:1, type:'input',
    q:'Pump A fills the water reservoir at 12 liters per minute and pump B at 18 liters per minute. Running together, how many <strong>minutes</strong> to fill 600 liters?',
    ans:20, ph:'minutes = ?',
    good:'Combined rate 30 L/min; 600/30 = 20 minutes.',
    bad:'Add the rates: 12 + 18 = 30 L/min. Then 600 / 30 = 20 minutes.' },

  // ---------- psda-proportions ----------
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:0, variant:0, type:'input',
    q:'Solve the calibration proportion <strong>4/6 = x/18</strong>.',
    ans:12, ph:'x = ?',
    good:'Cross-multiply: 6x = 72, so x = 12.',
    bad:'4 · 18 = 6x, so x = 72/6 = 12.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:0, variant:1, type:'input',
    q:'On the station map, 2 cm represents 5 km of lunar surface. A crater rim is 8 cm on the map. How many km is that?',
    ans:20, ph:'km = ?',
    good:'8 cm is 4 times 2 cm, so 4 · 5 = 20 km.',
    bad:'Set up 2/5 = 8/x: x = (8 · 5)/2 = 20 km.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:1, variant:0, type:'input',
    q:'Hydroponics uses 5 units of nutrient mix per 8 plants. How many units are needed for 40 plants?',
    ans:25, ph:'units = ?',
    good:'40 plants is 5 batches of 8, so 5 · 5 = 25 units.',
    bad:'5/8 = x/40, so x = (5 · 40)/8 = 25.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:1, variant:1, type:'input',
    q:'Under the dome lights, a 2-meter pole casts a 3-meter shadow. At the same moment, the comm antenna casts a 12-meter shadow. How tall is the antenna in meters?',
    ans:8, ph:'meters = ?',
    good:'2/3 = h/12, so h = 8 meters.',
    bad:'Similar triangles: height/shadow is constant, so h = 12 · (2/3) = 8.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:2, variant:0, type:'input',
    q:'A fuel blend satisfies <strong>x/(x + 6) = 2/5</strong>. Solve for x.',
    ans:4, ph:'x = ?',
    good:'5x = 2x + 12, so 3x = 12 and x = 4.',
    bad:'Cross-multiply: 5x = 2(x + 6) = 2x + 12, so x = 4.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:2, variant:1, type:'input',
    q:'In a sealed tank, pressure and volume are <strong>inversely</strong> proportional. When the volume is 6 liters the pressure is 40 kPa. Enter the pressure (kPa) when the volume is 8 liters.',
    ans:30, ph:'kPa = ?',
    good:'P · V = 240 stays constant, so P = 240/8 = 30 kPa.',
    bad:'Inverse proportion: P·V is constant. 40 · 6 = 240, so P = 240/8 = 30.' },

  // ---------- psda-units ----------
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:0, variant:0, type:'input',
    q:'The maintenance tunnel is 3 km long. Enter its length in meters.',
    ans:3000, ph:'meters = ?',
    good:'3 · 1000 = 3000 meters.',
    bad:'1 km = 1000 m, so 3 km = 3000 m.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:0, variant:1, type:'input',
    q:'A sensor sweep takes 5 hours. Enter that in minutes.',
    ans:300, ph:'minutes = ?',
    good:'5 · 60 = 300 minutes.',
    bad:'1 hour = 60 minutes, so 5 hours = 300 minutes.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:1, variant:0, type:'input',
    q:'A supply shuttle cruises at 72 km per hour. Enter its speed in meters per second.',
    ans:20, ph:'m/s = ?',
    good:'72 · 1000 / 3600 = 20 m/s.',
    bad:'Multiply by 1000 m/km and divide by 3600 s/h: 72000/3600 = 20.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:1, variant:1, type:'input',
    q:'A ration pack has a mass of 2.5 kg. Enter its mass in grams.',
    ans:2500, ph:'grams = ?',
    good:'2.5 · 1000 = 2500 grams.',
    bad:'1 kg = 1000 g, so 2.5 kg = 2500 g.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:2, variant:0, type:'input',
    q:'The rover sprints at 15 meters per second. Enter its speed in km per hour.',
    ans:54, ph:'km/h = ?',
    good:'15 · 3600 / 1000 = 54 km/h.',
    bad:'15 m/s · 3600 s/h = 54000 m/h = 54 km/h.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:2, variant:1, type:'input',
    q:'Life support consumes oxygen at 20 liters per hour. How many <strong>liters</strong> are needed for a full 3-day mission?',
    ans:1440, ph:'liters = ?',
    good:'3 days = 72 hours; 72 · 20 = 1440 liters.',
    bad:'3 · 24 = 72 hours, then 72 · 20 = 1440 liters.' },

  // ---------- psda-percent ----------
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:0, variant:0, type:'input',
    q:'The battery bank holds 250 units and is at 20% charge. Enter the units of charge remaining.',
    ans:50, ph:'units = ?',
    good:'0.20 · 250 = 50 units.',
    bad:'20% of 250 = 0.2 · 250 = 50.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:0, variant:1, type:'input',
    q:'45 of the 180 supply crates are medical. What <strong>percent</strong> are medical?',
    ans:25, ph:'percent = ?',
    good:'45/180 = 1/4 = 25%.',
    bad:'Divide: 45/180 = 0.25, which is 25%.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:1, variant:0, type:'input',
    q:'Daily power draw rose from 80 kW to 100 kW after the lab expansion. Enter the <strong>percent increase</strong>.',
    ans:25, ph:'percent = ?',
    good:'Increase of 20 over the original 80: 20/80 = 25%.',
    bad:'Percent change = (100 − 80)/80 = 0.25 = 25%. Divide by the ORIGINAL value.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:1, variant:1, type:'input',
    q:'A replacement part lists at 240 credits, with a 30% station discount. Enter the discounted price in credits.',
    ans:168, ph:'credits = ?',
    good:'240 · 0.70 = 168 credits.',
    bad:'30% off leaves 70%: 240 · 0.7 = 168.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:2, variant:0, type:'input',
    q:'After a 20% discount, a thruster nozzle costs 96 credits. Enter the <strong>original</strong> price in credits.',
    ans:120, ph:'credits = ?',
    good:'96 is 80% of the original: 96 / 0.8 = 120.',
    bad:'Reverse the percent: original · 0.8 = 96, so original = 96/0.8 = 120.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:2, variant:1, type:'input',
    q:'After a 15% surge, the reactor output is 138 MW. Enter the output in MW <strong>before</strong> the surge.',
    ans:120, ph:'MW = ?',
    good:'138 is 115% of the original: 138 / 1.15 = 120.',
    bad:'original · 1.15 = 138, so original = 138/1.15 = 120 MW.' },

  // ---------- psda-center-spread ----------
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:0, variant:0, type:'input',
    q:'Five air-quality readings came in: <strong>4, 7, 9, 12, 8</strong>. Enter the mean.',
    ans:8, ph:'mean = ?',
    good:'Sum 40 divided by 5 readings = 8.',
    bad:'Add them (4+7+9+12+8 = 40) and divide by 5: mean = 8.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:0, variant:1, type:'input',
    q:'Radiation counts for five shifts: <strong>3, 9, 5, 11, 7</strong>. Enter the median.',
    ans:7, ph:'median = ?',
    good:'Sorted: 3, 5, 7, 9, 11. Middle value: 7.',
    bad:'Sort first: 3, 5, 7, 9, 11. The middle (third) value is 7.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:1, variant:0, type:'input',
    q:'The mean of five hull-temperature readings is 14. Four of them are <strong>10, 12, 15, 16</strong>. Enter the fifth reading.',
    ans:17, ph:'fifth = ?',
    good:'Total must be 5 · 14 = 70; the four given sum to 53, so the fifth is 17.',
    bad:'Mean 14 over 5 readings means total 70. 70 − (10+12+15+16) = 70 − 53 = 17.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:1, variant:1, type:'input',
    q:'Battery temperatures this week: <strong>22, 35, 19, 41, 28</strong>. Enter the range.',
    ans:22, ph:'range = ?',
    good:'Max 41 minus min 19 = 22.',
    bad:'Range = maximum − minimum = 41 − 19 = 22.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:2, variant:0, type:'input',
    q:'Six pressure readings have a mean of 20. One faulty reading of 50 is discarded. Enter the mean of the remaining five readings.',
    ans:14, ph:'new mean = ?',
    good:'Old total 120; removing 50 leaves 70 across 5 readings: mean 14.',
    bad:'6 · 20 = 120 total. Remove 50: 70 left, over 5 readings = 14.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:2, variant:1, type:'mc',
    q:'A dataset of 20 normal sensor pings gets one extreme outlier from a glitching sensor. Which statistic is affected the <strong>most</strong>?',
    opts:['The median','The mean','The mode','None of them change'], ans:1,
    good:'The mean uses every value, so one extreme outlier drags it; the median barely moves.',
    bad:'The mean is sensitive to outliers because it sums all values; the median and mode resist them.' },

  // ---------- psda-tables ----------
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:0, variant:0, type:'input',
    q:'Crew census:<br>Deck A — 12 humans, 8 androids<br>Deck B — 15 humans, 5 androids<br>Enter the total number of <strong>androids</strong> on the station.',
    ans:13, ph:'androids = ?',
    good:'8 + 5 = 13 androids station-wide.',
    bad:'Add the android column: 8 (Deck A) + 5 (Deck B) = 13.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:0, variant:1, type:'input',
    q:'Crew census:<br>Deck A — 12 humans, 8 androids<br>Deck B — 15 humans, 5 androids<br>Enter the total crew count on <strong>Deck B</strong>.',
    ans:20, ph:'crew = ?',
    good:'15 + 5 = 20 on Deck B.',
    bad:'Sum the Deck B row: 15 humans + 5 androids = 20.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:1, variant:0, type:'input',
    q:'Crew census:<br>Deck A — 12 humans, 8 androids<br>Deck B — 15 humans, 5 androids<br>How many <strong>more humans than androids</strong> are on the station overall?',
    ans:14, ph:'difference = ?',
    good:'Humans 27, androids 13; difference 14.',
    bad:'Humans: 12 + 15 = 27. Androids: 8 + 5 = 13. Difference: 27 − 13 = 14.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:1, variant:1, type:'mc',
    q:'Crew census:<br>Deck A — 12 humans, 8 androids<br>Deck B — 15 humans, 5 androids<br>What fraction of the <strong>Deck A</strong> crew are androids?',
    opts:['8/13','1/4','2/5','8/40'], ans:2,
    good:'8 of 20 Deck A crew: 8/20 = 2/5.',
    bad:'Deck A total is 12 + 8 = 20; androids are 8/20 = 2/5.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:2, variant:0, type:'mc',
    q:'Crew census:<br>Deck A — 12 humans, 8 androids<br>Deck B — 15 humans, 5 androids<br>A crew member is picked at random and is known to be on <strong>Deck B</strong>. What is the probability they are human?',
    opts:['3/4','15/40','1/2','27/40'], ans:0,
    good:'Condition on Deck B: 15 humans out of 20 crew = 3/4.',
    bad:'Given Deck B, the sample space is only the 20 Deck B crew: 15/20 = 3/4.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:2, variant:1, type:'input',
    q:'Lab log of 60 samples:<br>Bacterial — 18 mutated, 6 not mutated<br>Non-bacterial — 12 mutated, 24 not mutated<br>What <strong>percent</strong> of the mutated samples are bacterial?',
    ans:60, ph:'percent = ?',
    good:'Mutated total 30; bacterial mutated 18; 18/30 = 60%.',
    bad:'Restrict to mutated samples: 18 + 12 = 30. Bacterial share: 18/30 = 60%.' },

  // ---------- psda-scatter ----------
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:0, variant:0, type:'input',
    q:'A scatterplot of solar exposure vs. power has a line of best fit <strong>y = 2.5x + 10</strong>. Enter the predicted y when x = 4.',
    ans:20, ph:'y = ?',
    good:'2.5 · 4 + 10 = 20.',
    bad:'Substitute x = 4: 2.5(4) + 10 = 10 + 10 = 20.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:0, variant:1, type:'mc',
    q:'A scatterplot of crew exercise hours vs. bone density has a best-fit line with <strong>positive slope</strong>. Which is the best description?',
    opts:['As exercise hours increase, bone density tends to increase','As exercise hours increase, bone density tends to decrease','Exercise hours and bone density are unrelated','Bone density causes exercise hours to increase'], ans:0,
    good:'Positive slope means the two variables rise together (a positive association).',
    bad:'A positive slope means larger x values pair with larger y values on average.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:1, variant:0, type:'input',
    q:'The best-fit line for drill depth vs. core samples is <strong>y = 3x − 5</strong>. For what x does the line predict y = 25?',
    ans:10, ph:'x = ?',
    good:'25 = 3x − 5, so 3x = 30 and x = 10.',
    bad:'Solve 3x − 5 = 25: 3x = 30, so x = 10.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:1, variant:1, type:'input',
    q:'The best-fit line is <strong>y = 2x + 10</strong>. At x = 14, the actual sensor reading was 42. Enter the residual (actual minus predicted).',
    ans:4, ph:'residual = ?',
    good:'Predicted 2(14) + 10 = 38; residual 42 − 38 = 4.',
    bad:'Prediction: 2·14 + 10 = 38. Residual = actual − predicted = 42 − 38 = 4.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:2, variant:0, type:'input',
    q:'Hull temperature vs. shade time fits <strong>y = −4x + 90</strong>. Enter the predicted temperature y when x = 15.',
    ans:30, ph:'y = ?',
    good:'−4 · 15 + 90 = −60 + 90 = 30.',
    bad:'Substitute: y = −4(15) + 90 = 30.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:2, variant:1, type:'mc',
    q:'Coolant temperature (°C) vs. hours in shadow fits <strong>y = −4x + 90</strong>. What does the slope −4 mean in context?',
    opts:['The coolant starts at 4 °C','After 4 hours the temperature is 90 °C','The temperature rises 4 °C each hour in shadow','The temperature drops about 4 °C for each additional hour in shadow'], ans:3,
    good:'Slope is change in y per unit x: about −4 °C per extra hour in shadow.',
    bad:'The slope gives the predicted change in y for each 1-unit increase in x: a 4 °C drop per hour.' },

  // ---------- psda-probability ----------
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:0, variant:0, type:'input',
    q:'A storage rack holds 20 canisters; 5 are marked red for emergencies. If one is grabbed at random, what is the probability it is red, as a <strong>percent</strong>?',
    ans:25, ph:'percent = ?',
    good:'5/20 = 1/4 = 25%.',
    bad:'Favorable over total: 5/20 = 25%.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:0, variant:1, type:'mc',
    q:'A parts bin has 3 blue chips and 7 green chips. What is the probability of drawing a blue chip at random?',
    opts:['3/7','3/10','7/10','1/3'], ans:1,
    good:'3 blue out of 10 total chips: 3/10.',
    bad:'Total chips = 3 + 7 = 10, so P(blue) = 3/10.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:1, variant:0, type:'mc',
    q:'Quality control finds 4 defective seals in a batch of 25. If one seal is tested at random, what is the probability it is <strong>not</strong> defective?',
    opts:['4/25','1/4','21/25','24/25'], ans:2,
    good:'25 − 4 = 21 good seals: 21/25.',
    bad:'P(not defective) = 1 − 4/25 = 21/25.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:1, variant:1, type:'input',
    q:'Each meteor-shield ping has a 3/8 chance of logging debris. In 40 pings, how many debris logs are <strong>expected</strong>?',
    ans:15, ph:'expected = ?',
    good:'(3/8) · 40 = 15.',
    bad:'Multiply probability by trials: (3/8)(40) = 15.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:2, variant:0, type:'mc',
    q:'Of 50 alerts last cycle, 30 came from Sensor A (12 of them critical) and 20 from Sensor B (8 of them critical). Given that an alert is <strong>critical</strong>, what is the probability it came from Sensor A?',
    opts:['3/5','12/50','12/30','2/5'], ans:0,
    good:'Critical alerts: 12 + 8 = 20. From A: 12/20 = 3/5.',
    bad:'Condition on critical: 20 critical total, 12 from Sensor A, so 12/20 = 3/5.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:2, variant:1, type:'input',
    q:'The primary comm array fails with probability 0.2 and the independent backup fails with probability 0.1. What is the probability <strong>both</strong> fail, as a percent?',
    ans:2, ph:'percent = ?',
    good:'Independent events multiply: 0.2 · 0.1 = 0.02 = 2%.',
    bad:'For independent events, multiply: 0.2 × 0.1 = 0.02, which is 2%.' },

  // ---------- psda-statistics ----------
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:0, variant:0, type:'mc',
    q:'Mission Control wants a more precise estimate of average crew sleep. Which change most reliably <strong>decreases</strong> the margin of error?',
    opts:['Surveying only the captains','Using a smaller random sample','Using a larger random sample','Rounding the results'], ans:2,
    good:'Bigger random samples give tighter estimates: smaller margin of error.',
    bad:'Margin of error shrinks as random sample size grows.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:0, variant:1, type:'mc',
    q:'Why should the crew wellness survey select respondents <strong>at random</strong>?',
    opts:['It guarantees every answer is honest','It reduces bias so results can generalize to the whole crew','It makes the sample larger','It removes the margin of error entirely'], ans:1,
    good:'Random selection fights selection bias, letting the sample represent the crew.',
    bad:'Randomization does not guarantee honesty or remove error; it reduces selection bias so results generalize.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:1, variant:0, type:'mc',
    q:'A random sample of ration packs has a mean mass of 40 grams with a margin of error of 3 grams. Which is a plausible value for the true mean mass of all packs?',
    opts:['38 grams','35 grams','44 grams','50 grams'], ans:0,
    good:'The plausible interval is 37 to 43 grams; 38 fits.',
    bad:'40 ± 3 gives the interval 37–43. Only 38 falls inside it.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:1, variant:1, type:'mc',
    q:'To estimate average fatigue across all 200 crew, an engineer surveys only the <strong>night-shift</strong> crew. What is the main problem?',
    opts:['The sample is too large','Night crew cannot compute averages','The margin of error becomes zero','The sample is not representative, so results may be biased'], ans:3,
    good:'Night-shift fatigue likely differs from the crew overall — a biased, non-random sample.',
    bad:'Sampling only one shift is a convenience sample; it cannot generalize to all 200 crew.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:2, variant:0, type:'mc',
    q:'Two air filters were tested on random samples. Filter X removed a mean of 82% of particles (margin of error 5%); Filter Y removed 86% (margin of error 5%). What is the best conclusion?',
    opts:['Filter Y is definitely better','The intervals overlap, so the data do not establish which filter is better','Filter X is definitely better','Both filters remove exactly 84%'], ans:1,
    good:'77–87 and 81–91 overlap, so the difference could be sampling noise.',
    bad:'X spans 77–87 and Y spans 81–91; overlapping intervals mean no confident winner.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:2, variant:1, type:'mc',
    q:'An observational study finds crew who drink more hydro-tea have fewer headaches. What conclusion is justified?',
    opts:['Hydro-tea prevents headaches','Headaches cause crew to avoid hydro-tea','There is an association, but the study cannot establish that hydro-tea causes fewer headaches','The study proves no relationship exists'], ans:2,
    good:'Observational data shows association only; causation needs a randomized experiment.',
    bad:'Without random assignment, confounders may explain the link — only association is supported.' }
);
