// SAT Math: Algebra skill bank — Axiom-7
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ===== alg-linear-1var =====
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:0, variant:0, type:'input',
    q:'The reactor coupling equation reads <strong>3x − 7 = 2x + 11</strong>. Solve for x to align the coupling.',
    ans:18, ph:'x = ?',
    good:'Subtract 2x from both sides to get x − 7 = 11, then add 7 to both sides: x = 18.',
    bad:'Move all the x terms to one side by subtracting 2x from both sides, then isolate x.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:0, variant:1, type:'mc',
    q:'The airlock pressure valve satisfies <strong>5x + 4 = 39</strong>. What is the value of x?',
    opts:['5','7','8','9'], ans:1,
    good:'Subtract 4 from both sides: 5x = 35. Divide by 5: x = 7.',
    bad:'Undo the +4 first, then undo the multiplication by 5.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:1, variant:0, type:'input',
    q:'A coolant flow controller obeys <strong>4(2x − 3) = 5x + 18</strong>. Solve for x.',
    ans:10, ph:'x = ?',
    good:'Distribute: 8x − 12 = 5x + 18. Subtract 5x: 3x − 12 = 18. Add 12: 3x = 30, so x = 10.',
    bad:'Distribute the 4 across the parentheses first, then gather x terms on one side.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'The fuel-mix computer reports <strong>x/3 + x/6 = 12</strong>. What is x?',
    opts:['18','20','24','36'], ans:2,
    good:'Multiply everything by 6: 2x + x = 72, so 3x = 72 and x = 24.',
    bad:'Clear the fractions by multiplying both sides by the least common denominator, 6.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:2, variant:0, type:'input',
    q:'The gyroscope calibration equation is <strong>6(x − 4) = 3(2x − 8) + x</strong>. Solve for x.',
    ans:0, ph:'x = ?',
    good:'Left side: 6x − 24. Right side: 6x − 24 + x = 7x − 24. So 6x − 24 = 7x − 24, which gives 0 = x. The answer is x = 0.',
    bad:'Expand both sides fully — notice how much of each side cancels before you panic.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:2, variant:1, type:'mc',
    q:'The thruster sync equation <strong>kx + 5 = 6x − 7</strong> has <em>no solution</em>. What is the value of k?',
    opts:['−6','0','6','12'], ans:2,
    good:'A linear equation has no solution when the x-coefficients match but the constants differ. Here k = 6 gives 6x + 5 = 6x − 7, i.e. 5 = −7, which is never true.',
    bad:'No solution means the x terms cancel completely, leaving a false statement about the constants.' },

  // ===== alg-linear-2var =====
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:0, variant:0, type:'input',
    q:'Power routing on Deck 4 satisfies <strong>2x + y = 14</strong>, where x is reactor output and y is solar output. If x = 3, what is y?',
    ans:8, ph:'y = ?',
    good:'Substitute x = 3: 2(3) + y = 14, so 6 + y = 14 and y = 8.',
    bad:'Plug in x = 3 and solve the resulting one-variable equation for y.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:0, variant:1, type:'mc',
    q:'The cargo manifest satisfies <strong>x − 3y = 6</strong>. If y = 2, what is x?',
    opts:['0','6','12','18'], ans:2,
    good:'Substitute y = 2: x − 6 = 6, so x = 12.',
    bad:'Replace y with 2, then isolate x.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:1, variant:0, type:'input',
    q:'The station orbit model is <strong>5x − 2y = 26</strong>. The trajectory passes through the point (4, y). What is y?',
    ans:-3, ph:'y = ?',
    good:'Substitute x = 4: 20 − 2y = 26, so −2y = 6 and y = −3.',
    bad:'Substitute x = 4, then be careful with the sign when dividing by −2.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'The shield harmonics equation is <strong>3x + 4y = 24</strong>. Which point lies on its graph?',
    opts:['(2, 5)','(4, 3)','(6, 2)','(8, 1)'], ans:1,
    good:'Test (4, 3): 3(4) + 4(3) = 12 + 12 = 24. It works. The others give 26, 26, and 28.',
    bad:'Substitute each pair into 3x + 4y and see which one actually produces 24.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:2, variant:0, type:'input',
    q:'The docking beacon line <strong>ax + 2y = 10</strong> passes through the point (2, −3). What is the value of a?',
    ans:8, ph:'a = ?',
    good:'Substitute the point: a(2) + 2(−3) = 10, so 2a − 6 = 10, 2a = 16, and a = 8.',
    bad:'A point on a line makes the equation true — plug in x = 2 and y = −3 and solve for a.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:2, variant:1, type:'mc',
    q:'For what value of k do <strong>2x + ky = 8</strong> and <strong>x + 3y = 4</strong> describe the <em>same</em> supply line?',
    opts:['2','3','6','8'], ans:2,
    good:'Multiply the second equation by 2: 2x + 6y = 8. Matching coefficients with 2x + ky = 8 gives k = 6.',
    bad:'Scale the second equation so its x-coefficient and constant match the first, then compare y-coefficients.' },

  // ===== alg-linear-functions =====
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:0, variant:0, type:'input',
    q:'The reactor temperature function is <strong>f(x) = 4x + 3</strong>, where x is the power setting. What is f(5)?',
    ans:23, ph:'f(5) = ?',
    good:'f(5) = 4(5) + 3 = 20 + 3 = 23.',
    bad:'Replace x with 5 and evaluate: multiply first, then add.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:0, variant:1, type:'mc',
    q:'The hull-stress function is <strong>f(x) = 2x − 9</strong>. What is f(6)?',
    opts:['−3','3','12','21'], ans:1,
    good:'f(6) = 2(6) − 9 = 12 − 9 = 3.',
    bad:'Substitute 6 for x: double it, then subtract 9.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:1, variant:0, type:'input',
    q:'Backup battery charge is modeled by <strong>f(x) = −3x + 15</strong>, where x is hours since the outage. After how many hours does the charge reach 0?',
    ans:5, ph:'x = ?',
    good:'Set f(x) = 0: −3x + 15 = 0, so 3x = 15 and x = 5 hours.',
    bad:'Set the function equal to 0 and solve for x.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'The oxygen reserve is modeled by <strong>O(t) = 800 − 25t</strong>, where t is hours since resupply and O(t) is liters remaining. What does the 25 represent?',
    opts:['The liters of oxygen remaining after one hour','The number of liters of oxygen used each hour','The total hours the oxygen supply will last','The starting number of liters of oxygen'], ans:1,
    good:'The slope −25 means the reserve drops by 25 liters for each hour that passes — 25 is the hourly usage rate. The 800 is the starting amount.',
    bad:'In a model like start − rate × time, ask what the coefficient of t does to the total each hour.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:2, variant:0, type:'input',
    q:'A linear sensor function f satisfies <strong>f(2) = 11</strong> and <strong>f(5) = 20</strong>. What is f(10)?',
    ans:35, ph:'f(10) = ?',
    good:'Slope = (20 − 11)/(5 − 2) = 3. Then f(x) = 3x + b, and f(2) = 6 + b = 11 gives b = 5. So f(10) = 30 + 5 = 35.',
    bad:'Find the slope from the two given values first, then use one point to find the constant term.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:2, variant:1, type:'mc',
    q:'The nav computer uses <strong>f(x) = mx + 7</strong> and reports <strong>f(4) = 19</strong>. What is f(−2)?',
    opts:['−1','1','5','13'], ans:1,
    good:'f(4) = 4m + 7 = 19 gives m = 3, so f(x) = 3x + 7. Then f(−2) = −6 + 7 = 1.',
    bad:'Use f(4) = 19 to solve for m first, then evaluate the completed function at −2.' },

  // ===== alg-linear-word =====
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:0, variant:0, type:'input',
    q:'Axiom-7 has 42 fuel cells in storage and the reactor consumes 6 per day. In how many days will the supply reach exactly 0?',
    ans:7, ph:'days = ?',
    good:'Solve 42 − 6d = 0: 6d = 42, so d = 7 days.',
    bad:'Set up start − rate × days = 0 and solve for days.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:0, variant:1, type:'mc',
    q:'A cargo pallet has a base mass of 20 kg, and each supply crate loaded onto it adds 15 kg. The loaded pallet masses 95 kg. How many crates are on it?',
    opts:['4','5','6','7'], ans:1,
    good:'Solve 20 + 15c = 95: 15c = 75, so c = 5 crates.',
    bad:'Subtract the pallet base mass from the total first, then divide by the mass per crate.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:1, variant:0, type:'input',
    q:'A repair drone charges 50 credits for deployment plus 12 credits per hour of work. A hull repair bill came to 146 credits. How many hours did the drone work?',
    ans:8, ph:'hours = ?',
    good:'Solve 50 + 12h = 146: 12h = 96, so h = 8 hours.',
    bad:'Write total = flat fee + hourly rate × hours, then isolate the hours.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'The airlock reservoir holds 240 units of air, and each door cycle uses 18 units. Safety rules require exactly 60 units left in reserve. How many cycles can be run?',
    opts:['8','9','10','12'], ans:2,
    good:'Solve 240 − 18c = 60: 18c = 180, so c = 10 cycles.',
    bad:'Only 240 − 60 units are actually available to spend — divide that by the cost per cycle.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:2, variant:0, type:'input',
    q:'The comms dish rotates at 4.5 degrees per minute. It starts at 27 degrees and must reach 117 degrees to lock onto Earth. How many minutes will the slew take?',
    ans:20, ph:'minutes = ?',
    good:'Solve 27 + 4.5t = 117: 4.5t = 90, so t = 20 minutes.',
    bad:'Find how many degrees the dish must travel, then divide by the rotation rate.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:2, variant:1, type:'mc',
    q:'On Axiom-7, three-fifths of the crew are engineers and the remaining 14 crew members are not. If x is the total crew count, then <strong>x = (3/5)x + 14</strong>. How many crew are aboard?',
    opts:['21','30','35','40'], ans:2,
    good:'x − (3/5)x = 14 gives (2/5)x = 14, so x = 35.',
    bad:'Move the (3/5)x to the left side; the remaining fraction of x must equal 14.' },

  // ===== alg-graphs =====
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:0, variant:0, type:'mc',
    q:'A telemetry line passes through the points <strong>(0, 4)</strong> and <strong>(2, 10)</strong>. What is its slope?',
    opts:['2','3','4','6'], ans:1,
    good:'Slope = (10 − 4)/(2 − 0) = 6/2 = 3.',
    bad:'Slope is rise over run: change in y divided by change in x between the two points.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:0, variant:1, type:'input',
    q:'The pressure graph <strong>y = 2x − 6</strong> crosses the x-axis at the point (x, 0). What is x?',
    ans:3, ph:'x = ?',
    good:'On the x-axis, y = 0: 0 = 2x − 6 gives x = 3.',
    bad:'Set y equal to 0 and solve — crossing the x-axis means the y-value is zero.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:1, variant:0, type:'mc',
    q:'Which best describes the graph of the coolant equation <strong>y = −2x + 8</strong>?',
    opts:['A line rising from left to right that crosses the y-axis at 8','A line falling from left to right that crosses the y-axis at 8','A line falling from left to right that crosses the y-axis at −2','A horizontal line at height 8'], ans:1,
    good:'The slope −2 is negative, so the line falls from left to right, and the constant 8 is the y-intercept.',
    bad:'The sign of the slope tells you rising vs falling; the constant term tells you where it meets the y-axis.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:1, variant:1, type:'input',
    q:'A fuel-flow line passes through <strong>(1, 5)</strong> and <strong>(4, 17)</strong>. What is its slope?',
    ans:4, ph:'slope = ?',
    good:'Slope = (17 − 5)/(4 − 1) = 12/3 = 4.',
    bad:'Compute the difference in y-values over the difference in x-values.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:2, variant:0, type:'mc',
    q:'A radiation-shield line passes through <strong>(−2, 7)</strong> and <strong>(4, −5)</strong>. At what y-value does it cross the y-axis?',
    opts:['3','5','−3','11'], ans:0,
    good:'Slope = (−5 − 7)/(4 − (−2)) = −12/6 = −2. Then 7 = −2(−2) + b gives 7 = 4 + b, so b = 3.',
    bad:'Find the slope from the two points, then substitute one point into y = mx + b to solve for b.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:2, variant:1, type:'input',
    q:'A backup power line is <em>parallel</em> to the graph of <strong>y = 3x − 4</strong> and passes through the point <strong>(2, 5)</strong>. What is its y-intercept?',
    ans:-1, ph:'y-intercept = ?',
    good:'Parallel lines share the slope 3. Then 5 = 3(2) + b gives 5 = 6 + b, so b = −1.',
    bad:'Parallel means the same slope — borrow the 3, then use the given point to find b.' },

  // ===== alg-slope-intercept =====
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:0, variant:0, type:'input',
    q:'The docking approach line is <strong>y = 5x − 9</strong>. What is its slope?',
    ans:5, ph:'slope = ?',
    good:'In y = mx + b form, the slope is the coefficient of x, which is 5.',
    bad:'The equation is already in slope-intercept form — read off the number multiplying x.' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:0, variant:1, type:'mc',
    q:'What is the y-intercept of the solar-array output line <strong>y = −3x + 7</strong>?',
    opts:['−3','3','7','−7'], ans:2,
    good:'In y = mx + b form, b is the y-intercept: 7.',
    bad:'The y-intercept is the constant term, where the line meets the y-axis (x = 0).' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:1, variant:0, type:'input',
    q:'The waste-heat line is written in standard form: <strong>4x + 2y = 12</strong>. What is its slope?',
    ans:-2, ph:'slope = ?',
    good:'Solve for y: 2y = −4x + 12, so y = −2x + 6. The slope is −2.',
    bad:'Rearrange into y = mx + b form first, then read off m.' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'What is the y-intercept of the antenna alignment line <strong>3x − 6y = 18</strong>?',
    opts:['−3','3','6','18'], ans:0,
    good:'Set x = 0: −6y = 18, so y = −3. The y-intercept is −3.',
    bad:'The fastest route: plug in x = 0 and solve for y.' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:2, variant:0, type:'input',
    q:'A trajectory line through <strong>(3, k)</strong> and <strong>(5, 9)</strong> has slope 4. What is k?',
    ans:1, ph:'k = ?',
    good:'(9 − k)/(5 − 3) = 4 gives 9 − k = 8, so k = 1.',
    bad:'Write the slope formula with the unknown coordinate and set it equal to 4.' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:2, variant:1, type:'mc',
    q:'The coolant line <strong>2x + by = 12</strong> has slope <strong>−1/3</strong>. What is the value of b?',
    opts:['−6','3','6','9'], ans:2,
    good:'Solving for y gives y = (−2/b)x + 12/b, so the slope is −2/b. Set −2/b = −1/3: b = 6.',
    bad:'Convert to slope-intercept form; the slope of Ax + By = C is −A/B.' },

  // ===== alg-systems =====
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:0, variant:0, type:'input',
    q:'Two reactor readouts satisfy <strong>x + y = 10</strong> and <strong>x − y = 4</strong>. What is x?',
    ans:7, ph:'x = ?',
    good:'Add the equations: 2x = 14, so x = 7 (and y = 3).',
    bad:'Adding the two equations makes y vanish immediately.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:0, variant:1, type:'mc',
    q:'The power split satisfies <strong>y = 2x</strong> and <strong>x + y = 12</strong>. What is y?',
    opts:['4','6','8','10'], ans:2,
    good:'Substitute: x + 2x = 12 gives x = 4, so y = 2(4) = 8.',
    bad:'Replace y with 2x in the second equation and solve for x first.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:1, variant:0, type:'input',
    q:'Fuel routing satisfies <strong>2x + 3y = 21</strong> and <strong>x = 2y</strong>. What is x?',
    ans:6, ph:'x = ?',
    good:'Substitute x = 2y: 2(2y) + 3y = 7y = 21, so y = 3 and x = 6.',
    bad:'Substitute 2y for x, solve for y, then double it.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'Shield calibration requires solving <strong>3x + 2y = 16</strong> and <strong>5x − 2y = 8</strong>. What is x?',
    opts:['2','3','4','6'], ans:1,
    good:'Add the equations: 8x = 24, so x = 3.',
    bad:'The +2y and −2y are begging to be eliminated — add the equations.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:2, variant:0, type:'input',
    q:'The system <strong>3x − y = 5</strong> and <strong>6x − 2y = k</strong> has <em>infinitely many</em> solutions. What is k?',
    ans:10, ph:'k = ?',
    good:'The second equation is exactly 2 times the first, so k must be 2 × 5 = 10.',
    bad:'Infinitely many solutions means the equations are the same line — one must be a multiple of the other.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:2, variant:1, type:'mc',
    q:'For what value of k does the system <strong>kx + 4y = 8</strong> and <strong>3x + 2y = 5</strong> have <em>no</em> solution?',
    opts:['2','4','6','8'], ans:2,
    good:'Multiply the second equation by 2: 6x + 4y = 10. With k = 6 the left sides match but 8 ≠ 10 — parallel lines, no solution.',
    bad:'No solution means matching coefficients (same slope) but different constants. Scale the second equation to compare.' },

  // ===== alg-systems-word =====
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:0, variant:0, type:'mc',
    q:'The hangar holds 10 vehicles: drones and rovers. There are 4 more drones than rovers. How many drones are there?',
    opts:['3','5','7','8'], ans:2,
    good:'d + r = 10 and d = r + 4. Substituting: (r + 4) + r = 10, so r = 3 and d = 7.',
    bad:'Write one equation for the total and one for the difference, then substitute.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:0, variant:1, type:'input',
    q:'Two water tanks together hold 30 kiloliters, and the larger tank holds twice as much as the smaller. How many kiloliters are in the larger tank?',
    ans:20, ph:'kiloliters = ?',
    good:'s + 2s = 30 gives s = 10, so the larger tank holds 20.',
    bad:'Call the small tank s; the large one is 2s; their sum is 30.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:1, variant:0, type:'input',
    q:'A supply pod carries 12 containers with a total mass of 75 kg. Oxygen canisters mass 5 kg each and water packs mass 8 kg each. How many oxygen canisters are aboard?',
    ans:7, ph:'canisters = ?',
    good:'x + y = 12 and 5x + 8y = 75. From the first, x = 12 − y: 5(12 − y) + 8y = 60 + 3y = 75, so y = 5 water packs and x = 7 canisters.',
    bad:'Set up a count equation and a mass equation, then substitute one into the other.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'The commissary sold 14 ration packs for 58 credits. Type A costs 3 credits and Type B costs 5 credits. How many Type B packs were sold?',
    opts:['5','6','8','9'], ans:2,
    good:'a + b = 14 and 3a + 5b = 58. Substitute a = 14 − b: 42 − 3b + 5b = 42 + 2b = 58, so b = 8.',
    bad:'If all 14 were Type A the total would be 42 credits — each swap to Type B adds 2 credits.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:2, variant:0, type:'input',
    q:'Pump X moves 40 liters of coolant per minute and Pump Y moves 25 liters per minute. The two pumps ran one after the other for a combined 30 minutes and moved 975 liters. For how many minutes did Pump X run?',
    ans:15, ph:'minutes = ?',
    good:'x + y = 30 and 40x + 25y = 975. Substitute y = 30 − x: 40x + 750 − 25x = 975, so 15x = 225 and x = 15 minutes.',
    bad:'One equation for total minutes, one for total liters; eliminate one variable.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:2, variant:1, type:'mc',
    q:'Engineering must blend a 30% coolant solution with a 70% coolant solution to make 20 liters of a 54% solution. How many liters of the 70% solution are needed?',
    opts:['8','10','12','14'], ans:2,
    good:'a + b = 20 and 0.3a + 0.7b = 0.54(20) = 10.8. Substitute a = 20 − b: 6 − 0.3b + 0.7b = 10.8, so 0.4b = 4.8 and b = 12 liters.',
    bad:'Track the pure coolant: liters × concentration for each part must add up to 20 × 0.54.' },

  // ===== alg-inequalities =====
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:0, variant:0, type:'mc',
    q:'The reactor stays stable only when <strong>2x + 3 > 11</strong>. What is the solution set?',
    opts:['x > 4','x < 4','x > 7','x < 7'], ans:0,
    good:'Subtract 3: 2x > 8. Divide by 2: x > 4.',
    bad:'Solve it like an equation — the inequality sign only flips if you multiply or divide by a negative.' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:0, variant:1, type:'mc',
    q:'Cargo mass limits require <strong>x − 5 ≤ 2</strong>. Which describes the allowed values of x?',
    opts:['x ≥ 7','x ≤ 7','x ≤ 3','x ≥ 3'], ans:1,
    good:'Add 5 to both sides: x ≤ 7.',
    bad:'Just add 5 to both sides; the direction of the inequality does not change.' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:1, variant:0, type:'mc',
    q:'Thermal safety requires <strong>−3x + 6 < 21</strong>. What is the solution set?',
    opts:['x < −5','x > −5','x < 5','x > 5'], ans:1,
    good:'Subtract 6: −3x < 15. Dividing by −3 flips the sign: x > −5.',
    bad:'Careful — dividing both sides by a negative number reverses the inequality.' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'The airlock seal holds only when <strong>4(x − 2) ≥ 2x + 6</strong>. What is the solution set?',
    opts:['x ≥ 7','x ≤ 7','x ≥ 1','x ≤ 1'], ans:0,
    good:'Distribute: 4x − 8 ≥ 2x + 6. Then 2x ≥ 14, so x ≥ 7.',
    bad:'Distribute first, gather x terms on one side, and divide by a positive number (no flip).' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:2, variant:0, type:'mc',
    q:'Fuel margin analysis gives <strong>x/2 − 3 > x/3 + 1</strong>. What is the solution set?',
    opts:['x > 24','x < 24','x > 12','x < 12'], ans:0,
    good:'Multiply everything by 6: 3x − 18 > 2x + 6, so x > 24.',
    bad:'Clear the fractions by multiplying through by 6 before doing anything else.' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:2, variant:1, type:'input',
    q:'The relay only fires when <strong>5x − 3 > 22</strong>, where x is a whole-number power setting. What is the <em>smallest integer</em> value of x that fires the relay?',
    ans:6, ph:'x = ?',
    good:'5x > 25 gives x > 5. The smallest integer strictly greater than 5 is 6 (x = 5 itself does not satisfy the strict inequality).',
    bad:'Solve the inequality first, then note that the boundary value itself is excluded.' },

  // ===== alg-inequality-graphs =====
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:0, variant:0, type:'mc',
    q:'The safe-pressure region is all points where <strong>y > 2x + 1</strong>. Which point is in the region?',
    opts:['(0, 0)','(2, 5)','(0, 5)','(3, 1)'], ans:2,
    good:'Test (0, 5): 5 > 2(0) + 1 = 1 is true. The others fail: 0 > 1 is false, 5 > 5 is false (strict), and 1 > 7 is false.',
    bad:'Plug each point into the inequality; remember a strict > excludes points exactly on the line.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:0, variant:1, type:'mc',
    q:'The docking clearance zone is <strong>y ≤ x − 2</strong>. Which point is inside the zone?',
    opts:['(5, 1)','(0, 0)','(1, 4)','(2, 3)'], ans:0,
    good:'Test (5, 1): 1 ≤ 5 − 2 = 3 is true. The others give 0 ≤ −2, 4 ≤ −1, and 3 ≤ 0 — all false.',
    bad:'Substitute each point and check whether the y-value is at or below x − 2.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:1, variant:0, type:'mc',
    q:'Which best describes the graph of the radiation exclusion rule <strong>y > −x + 6</strong>?',
    opts:['The region below a solid line through (0, 6) with slope −1','The region above a dashed line through (0, 6) with slope −1','The region above a solid line through (0, 6) with slope 1','The region below a dashed line through (6, 0) with slope −6'], ans:1,
    good:'Strict inequality means a dashed boundary line, and y greater means the region above the line y = −x + 6, which has y-intercept 6 and slope −1.',
    bad:'Strict > means dashed boundary; "y greater than" shades the side above the line.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:1, variant:1, type:'mc',
    q:'A shuttle must sit where <strong>y < 3x</strong> AND <strong>y > x − 4</strong>. Which point satisfies both?',
    opts:['(0, 5)','(2, 3)','(−1, 0)','(6, 1)'], ans:1,
    good:'Test (2, 3): 3 < 6 is true and 3 > −2 is true. (0, 5) fails 5 < 0; (−1, 0) fails 0 < −3; (6, 1) fails 1 > 2.',
    bad:'A point in the solution region of a system must satisfy every inequality, not just one.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:2, variant:0, type:'mc',
    q:'The overlap zone of <strong>y ≤ 2x + 1</strong> and <strong>y ≥ −x + 4</strong> is bounded by two lines. At what point do those boundary lines intersect?',
    opts:['(1, 3)','(3, 1)','(2, 5)','(−1, 5)'], ans:0,
    good:'Set 2x + 1 = −x + 4: 3x = 3, so x = 1 and y = 2(1) + 1 = 3. The corner is (1, 3).',
    bad:'The boundaries are the lines y = 2x + 1 and y = −x + 4 — set them equal.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:2, variant:1, type:'mc',
    q:'The point <strong>(k, 0)</strong> lies in the solution region of <strong>y ≥ 3x − 6</strong>. Which must be true about k?',
    opts:['k ≤ 2','k ≥ 2','k ≤ 6','k ≥ 6'], ans:0,
    good:'Substitute the point: 0 ≥ 3k − 6, so 6 ≥ 3k and k ≤ 2.',
    bad:'Plug x = k and y = 0 into the inequality and solve for k — watch which direction survives.' }
);
