// SAT Math: Algebra skill bank — Axiom-7 — variants C & D (variant 2 and 3)
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ===== alg-linear-1var =====
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:0, variant:2, type:'input',
    q:'The docking clamp equation reads <strong>7x + 2 = 4x + 20</strong>. Solve for x to release the clamp.',
    ans:6, ph:'x = ?',
    good:'Subtract 4x from both sides: 3x + 2 = 20. Subtract 2: 3x = 18, so x = 6.',
    bad:'Gather the x terms on one side and the constants on the other, then divide.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:0, variant:3, type:'mc',
    q:'The life-support dial satisfies <strong>6x − 5 = 31</strong>. What is the value of x?',
    opts:['5','6','7','8'], ans:1,
    good:'Add 5 to both sides: 6x = 36. Divide by 6: x = 6.',
    bad:'Undo the −5 first, then undo the multiplication by 6.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:1, variant:2, type:'input',
    q:'A pressure regulator obeys <strong>3(x + 5) = 7x − 9</strong>. Solve for x.',
    ans:6, ph:'x = ?',
    good:'Distribute: 3x + 15 = 7x − 9. Subtract 3x: 15 = 4x − 9. Add 9: 24 = 4x, so x = 6.',
    bad:'Distribute the 3 first, then gather x terms on one side.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'The ballast computer reports <strong>x/2 + x/4 = 9</strong>. What is x?',
    opts:['6','9','12','16'], ans:2,
    good:'Multiply everything by 4: 2x + x = 36, so 3x = 36 and x = 12.',
    bad:'Clear the fractions by multiplying both sides by the least common denominator, 4.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:2, variant:2, type:'input',
    q:'The stabilizer calibration equation is <strong>4(x − 3) = 2(2x − 6) + 2x</strong>. Solve for x.',
    ans:0, ph:'x = ?',
    good:'Left: 4x − 12. Right: 4x − 12 + 2x = 6x − 12. So 4x − 12 = 6x − 12, which gives 0 = 2x, so x = 0.',
    bad:'Expand both sides fully — watch how much cancels before isolating x.' },
  { skill:'alg-linear-1var', name:'Linear equations (one variable)', domain:'m-alg', tier:2, variant:3, type:'mc',
    q:'The relay sync equation <strong>kx − 3 = 4x + 9</strong> has <em>no solution</em>. What is the value of k?',
    opts:['−4','3','4','9'], ans:2,
    good:'No solution requires matching x-coefficients but differing constants. Here k = 4 gives 4x − 3 = 4x + 9, i.e. −3 = 9, never true.',
    bad:'The x terms must cancel, leaving a false constant statement.' },

  // ===== alg-linear-2var =====
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:0, variant:2, type:'input',
    q:'Heat routing on Deck 2 satisfies <strong>3x + y = 20</strong>, where x is core output and y is vent output. If x = 4, what is y?',
    ans:8, ph:'y = ?',
    good:'Substitute x = 4: 3(4) + y = 20, so 12 + y = 20 and y = 8.',
    bad:'Plug in x = 4 and solve the resulting one-variable equation for y.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:0, variant:3, type:'mc',
    q:'The inventory ledger satisfies <strong>x − 2y = 9</strong>. If y = 3, what is x?',
    opts:['3','6','12','15'], ans:3,
    good:'Substitute y = 3: x − 6 = 9, so x = 15.',
    bad:'Replace y with 3, then isolate x.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:1, variant:2, type:'input',
    q:'The trajectory model is <strong>4x − 3y = 26</strong>. The path passes through the point (5, y). What is y?',
    ans:-2, ph:'y = ?',
    good:'Substitute x = 5: 20 − 3y = 26, so −3y = 6 and y = −2.',
    bad:'Substitute x = 5, then mind the sign when dividing by −3.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'The antenna phase equation is <strong>2x + 5y = 30</strong>. Which point lies on its graph?',
    opts:['(5, 3)','(10, 1)','(5, 4)','(0, 5)'], ans:2,
    good:'Test (5, 4): 2(5) + 5(4) = 10 + 20 = 30. It works. The others give 25, 25, and 25.',
    bad:'Substitute each pair into 2x + 5y and see which produces 30.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:2, variant:2, type:'input',
    q:'The beacon line <strong>ax − 3y = 5</strong> passes through the point (4, 1). What is the value of a?',
    ans:2, ph:'a = ?',
    good:'Substitute: a(4) − 3(1) = 5, so 4a − 3 = 5, 4a = 8, and a = 2.',
    bad:'Plug in x = 4 and y = 1 and solve for a.' },
  { skill:'alg-linear-2var', name:'Linear equations (two variables)', domain:'m-alg', tier:2, variant:3, type:'mc',
    q:'For what value of k do <strong>3x + ky = 12</strong> and <strong>x + 4y = 4</strong> describe the <em>same</em> supply line?',
    opts:['4','8','12','16'], ans:2,
    good:'Multiply the second equation by 3: 3x + 12y = 12. Matching with 3x + ky = 12 gives k = 12.',
    bad:'Scale the second equation so its x-coefficient and constant match the first, then compare y-coefficients.' },

  // ===== alg-linear-functions =====
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:0, variant:2, type:'input',
    q:'The coolant pressure function is <strong>f(x) = 6x − 5</strong>, where x is the pump setting. What is f(4)?',
    ans:19, ph:'f(4) = ?',
    good:'f(4) = 6(4) − 5 = 24 − 5 = 19.',
    bad:'Replace x with 4, multiply first, then subtract.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:0, variant:3, type:'mc',
    q:'The panel-voltage function is <strong>f(x) = 3x + 8</strong>. What is f(5)?',
    opts:['13','18','23','26'], ans:2,
    good:'f(5) = 3(5) + 8 = 15 + 8 = 23.',
    bad:'Substitute 5 for x: triple it, then add 8.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:1, variant:2, type:'input',
    q:'Reserve fuel is modeled by <strong>f(x) = −4x + 32</strong>, where x is hours of burn. After how many hours does the fuel reach 0?',
    ans:8, ph:'x = ?',
    good:'Set f(x) = 0: −4x + 32 = 0, so 4x = 32 and x = 8 hours.',
    bad:'Set the function equal to 0 and solve for x.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'The water reserve is modeled by <strong>W(t) = 500 − 12t</strong>, where t is days since resupply and W(t) is liters remaining. What does the 500 represent?',
    opts:['The liters used each day','The number of days the water lasts','The starting number of liters of water','The liters remaining after one day'], ans:2,
    good:'At t = 0, W(0) = 500, so 500 is the starting amount. The 12 is the daily usage rate.',
    bad:'The constant term is the value when t = 0 — the initial amount.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:2, variant:2, type:'input',
    q:'A linear sensor function f satisfies <strong>f(1) = 7</strong> and <strong>f(4) = 22</strong>. What is f(6)?',
    ans:32, ph:'f(6) = ?',
    good:'Slope = (22 − 7)/(4 − 1) = 15/3 = 5. Then f(x) = 5x + b, and f(1) = 5 + b = 7 gives b = 2. So f(6) = 30 + 2 = 32.',
    bad:'Find the slope from the two given values, then use one point to find the constant.' },
  { skill:'alg-linear-functions', name:'Linear functions', domain:'m-alg', tier:2, variant:3, type:'mc',
    q:'The nav computer uses <strong>f(x) = mx − 5</strong> and reports <strong>f(3) = 10</strong>. What is f(−1)?',
    opts:['−10','−5','0','5'], ans:0,
    good:'f(3) = 3m − 5 = 10 gives 3m = 15, m = 5, so f(x) = 5x − 5. Then f(−1) = −5 − 5 = −10.',
    bad:'Use f(3) = 10 to solve for m first, then evaluate at −1.' },

  // ===== alg-linear-word =====
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:0, variant:2, type:'input',
    q:'Axiom-7 stores 60 ration bars and the crew eats 5 per day. In how many days will the supply reach exactly 0?',
    ans:12, ph:'days = ?',
    good:'Solve 60 − 5d = 0: 5d = 60, so d = 12 days.',
    bad:'Set start − rate × days = 0 and solve for days.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:0, variant:3, type:'mc',
    q:'A shipping frame has a base mass of 8 kg, and each module bolted on adds 11 kg. The loaded frame masses 74 kg. How many modules are attached?',
    opts:['4','5','6','7'], ans:2,
    good:'Solve 8 + 11m = 74: 11m = 66, so m = 6 modules.',
    bad:'Subtract the base mass first, then divide by the mass per module.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:1, variant:2, type:'input',
    q:'A survey probe charges 30 credits for launch plus 9 credits per scan. A survey bill came to 138 credits. How many scans were performed?',
    ans:12, ph:'scans = ?',
    good:'Solve 30 + 9s = 138: 9s = 108, so s = 12 scans.',
    bad:'Write total = flat fee + rate × scans, then isolate the scans.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'A coolant tank holds 300 units, and each flush uses 22 units. Regulations require exactly 80 units left in reserve. How many flushes can be run?',
    opts:['8','9','10','11'], ans:2,
    good:'Solve 300 − 22f = 80: 22f = 220, so f = 10 flushes.',
    bad:'Only 300 − 80 units are available to spend — divide that by the cost per flush.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:2, variant:2, type:'input',
    q:'The solar array rotates at 3.5 degrees per minute. It starts at 12 degrees and must reach 96 degrees to face the sun. How many minutes will the slew take?',
    ans:24, ph:'minutes = ?',
    good:'Solve 12 + 3.5t = 96: 3.5t = 84, so t = 24 minutes.',
    bad:'Find how many degrees to travel, then divide by the rotation rate.' },
  { skill:'alg-linear-word', name:'Linear equation word problems', domain:'m-alg', tier:2, variant:3, type:'mc',
    q:'On Axiom-7, three-fourths of the stored crates are sealed and the remaining 18 crates are open. If x is the total number of crates, then <strong>x = (3/4)x + 18</strong>. How many crates are there?',
    opts:['54','60','72','80'], ans:2,
    good:'x − (3/4)x = 18 gives (1/4)x = 18, so x = 72.',
    bad:'Move the (3/4)x to the left; the remaining fraction of x must equal 18.' },

  // ===== alg-graphs =====
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:0, variant:2, type:'mc',
    q:'A telemetry line passes through the points <strong>(0, 3)</strong> and <strong>(4, 15)</strong>. What is its slope?',
    opts:['2','3','4','12'], ans:1,
    good:'Slope = (15 − 3)/(4 − 0) = 12/4 = 3.',
    bad:'Slope is rise over run: change in y over change in x.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:0, variant:3, type:'input',
    q:'The pressure graph <strong>y = 3x − 12</strong> crosses the x-axis at the point (x, 0). What is x?',
    ans:4, ph:'x = ?',
    good:'On the x-axis, y = 0: 0 = 3x − 12 gives x = 4.',
    bad:'Set y equal to 0 and solve — the x-axis means y is zero.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:1, variant:2, type:'mc',
    q:'Which best describes the graph of the venting equation <strong>y = 4x − 5</strong>?',
    opts:['A line falling from left to right that crosses the y-axis at −5','A line rising from left to right that crosses the y-axis at −5','A line rising from left to right that crosses the y-axis at 4','A horizontal line at height −5'], ans:1,
    good:'The slope 4 is positive, so the line rises from left to right, and the constant −5 is the y-intercept.',
    bad:'The sign of the slope gives rising vs falling; the constant term gives the y-intercept.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:1, variant:3, type:'input',
    q:'A power-flow line passes through <strong>(2, 7)</strong> and <strong>(5, 22)</strong>. What is its slope?',
    ans:5, ph:'slope = ?',
    good:'Slope = (22 − 7)/(5 − 2) = 15/3 = 5.',
    bad:'Compute the difference in y-values over the difference in x-values.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:2, variant:2, type:'mc',
    q:'A shield line passes through <strong>(−1, 8)</strong> and <strong>(3, −4)</strong>. At what y-value does it cross the y-axis?',
    opts:['2','5','−1','8'], ans:1,
    good:'Slope = (−4 − 8)/(3 − (−1)) = −12/4 = −3. Then 8 = −3(−1) + b gives 8 = 3 + b, so b = 5.',
    bad:'Find the slope, then substitute a point into y = mx + b to solve for b.' },
  { skill:'alg-graphs', name:'Graphs of linear equations', domain:'m-alg', tier:2, variant:3, type:'input',
    q:'A backup line is <em>parallel</em> to the graph of <strong>y = −2x + 5</strong> and passes through the point <strong>(3, 4)</strong>. What is its y-intercept?',
    ans:10, ph:'y-intercept = ?',
    good:'Parallel lines share the slope −2. Then 4 = −2(3) + b gives 4 = −6 + b, so b = 10.',
    bad:'Parallel means the same slope — borrow the −2, then use the point to find b.' },

  // ===== alg-slope-intercept =====
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:0, variant:2, type:'input',
    q:'The approach line is <strong>y = 7x + 2</strong>. What is its slope?',
    ans:7, ph:'slope = ?',
    good:'In y = mx + b form, the slope is the coefficient of x, which is 7.',
    bad:'Read off the number multiplying x.' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:0, variant:3, type:'mc',
    q:'What is the y-intercept of the array output line <strong>y = 4x − 11</strong>?',
    opts:['4','11','−4','−11'], ans:3,
    good:'In y = mx + b form, b is the y-intercept: −11.',
    bad:'The y-intercept is the constant term (where x = 0).' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:1, variant:2, type:'input',
    q:'The exhaust line is in standard form: <strong>6x + 3y = 15</strong>. What is its slope?',
    ans:-2, ph:'slope = ?',
    good:'Solve for y: 3y = −6x + 15, so y = −2x + 5. The slope is −2.',
    bad:'Rearrange into y = mx + b form, then read off m.' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'What is the y-intercept of the alignment line <strong>5x − 2y = 14</strong>?',
    opts:['−7','7','−2','14'], ans:0,
    good:'Set x = 0: −2y = 14, so y = −7. The y-intercept is −7.',
    bad:'Plug in x = 0 and solve for y.' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:2, variant:2, type:'input',
    q:'A trajectory line through <strong>(2, k)</strong> and <strong>(6, 20)</strong> has slope 3. What is k?',
    ans:8, ph:'k = ?',
    good:'(20 − k)/(6 − 2) = 3 gives 20 − k = 12, so k = 8.',
    bad:'Write the slope formula with the unknown coordinate and set it equal to 3.' },
  { skill:'alg-slope-intercept', name:'Slope and intercepts', domain:'m-alg', tier:2, variant:3, type:'mc',
    q:'The coolant line <strong>3x + by = 15</strong> has slope <strong>−1/2</strong>. What is the value of b?',
    opts:['2','3','6','9'], ans:2,
    good:'Solving for y gives slope −3/b. Set −3/b = −1/2: b = 6.',
    bad:'The slope of Ax + By = C is −A/B.' },

  // ===== alg-systems =====
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:0, variant:2, type:'input',
    q:'Two readouts satisfy <strong>x + y = 15</strong> and <strong>x − y = 3</strong>. What is x?',
    ans:9, ph:'x = ?',
    good:'Add the equations: 2x = 18, so x = 9 (and y = 6).',
    bad:'Adding the two equations makes y vanish.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:0, variant:3, type:'mc',
    q:'The load split satisfies <strong>y = 3x</strong> and <strong>x + y = 16</strong>. What is y?',
    opts:['4','8','12','16'], ans:2,
    good:'Substitute: x + 3x = 16 gives x = 4, so y = 3(4) = 12.',
    bad:'Replace y with 3x in the second equation and solve for x first.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:1, variant:2, type:'input',
    q:'Power routing satisfies <strong>2x + 3y = 14</strong> and <strong>y = x − 2</strong>. What is x?',
    ans:4, ph:'x = ?',
    good:'Substitute y = x − 2: 2x + 3(x − 2) = 5x − 6 = 14, so 5x = 20 and x = 4 (with y = 2).',
    bad:'Substitute x − 2 for y and solve for x.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'Calibration requires solving <strong>4x + 3y = 27</strong> and <strong>2x − 3y = 3</strong>. What is x?',
    opts:['3','4','5','6'], ans:2,
    good:'Add the equations: 6x = 30, so x = 5.',
    bad:'The +3y and −3y eliminate when you add the equations.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:2, variant:2, type:'input',
    q:'The system <strong>2x − y = 7</strong> and <strong>8x − 4y = k</strong> has <em>infinitely many</em> solutions. What is k?',
    ans:28, ph:'k = ?',
    good:'The second equation is 4 times the first, so k = 4 × 7 = 28.',
    bad:'Infinitely many solutions means one equation is a multiple of the other.' },
  { skill:'alg-systems', name:'Systems of two linear equations', domain:'m-alg', tier:2, variant:3, type:'mc',
    q:'For what value of k does the system <strong>kx + 6y = 10</strong> and <strong>2x + 3y = 4</strong> have <em>no</em> solution?',
    opts:['2','3','4','6'], ans:2,
    good:'Multiply the second equation by 2: 4x + 6y = 8. With k = 4 the left sides match but 10 ≠ 8 — parallel lines, no solution.',
    bad:'No solution means matching coefficients but different constants. Scale to compare.' },

  // ===== alg-systems-word =====
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:0, variant:2, type:'mc',
    q:'The bay holds 12 units: probes and landers. There are 2 more probes than landers. How many probes are there?',
    opts:['5','6','7','8'], ans:2,
    good:'p + l = 12 and p = l + 2. Substituting: (l + 2) + l = 12, so l = 5 and p = 7.',
    bad:'Write a total equation and a difference equation, then substitute.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:0, variant:3, type:'input',
    q:'Two fuel pods together hold 48 liters, and the larger holds three times as much as the smaller. How many liters are in the larger pod?',
    ans:36, ph:'liters = ?',
    good:'s + 3s = 48 gives 4s = 48, s = 12, so the larger holds 36.',
    bad:'Call the small pod s; the large one is 3s; their sum is 48.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:1, variant:2, type:'input',
    q:'A cargo crate holds 10 items with a total mass of 66 kg. Tools mass 5 kg each and kits mass 9 kg each. How many tools are aboard?',
    ans:6, ph:'tools = ?',
    good:'x + y = 10 and 5x + 9y = 66. Substitute x = 10 − y: 5(10 − y) + 9y = 50 + 4y = 66, so y = 4 kits and x = 6 tools.',
    bad:'Set up a count equation and a mass equation, then substitute.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'The depot sold 16 kits for 70 credits. Type A costs 4 credits and Type B costs 6 credits. How many Type B kits were sold?',
    opts:['3','4','5','6'], ans:0,
    good:'a + b = 16 and 4a + 6b = 70. Substitute a = 16 − b: 64 − 4b + 6b = 64 + 2b = 70, so b = 3.',
    bad:'If all 16 were Type A the total would be 64 — each swap to Type B adds 2 credits.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:2, variant:2, type:'input',
    q:'Pump A moves 30 liters per minute and Pump B moves 20 liters per minute. The two pumps ran one after the other for a combined 25 minutes and moved 640 liters. For how many minutes did Pump A run?',
    ans:14, ph:'minutes = ?',
    good:'x + y = 25 and 30x + 20y = 640. Substitute y = 25 − x: 30x + 500 − 20x = 640, so 10x = 140 and x = 14 minutes.',
    bad:'One equation for total minutes, one for total liters; eliminate one variable.' },
  { skill:'alg-systems-word', name:'Systems word problems', domain:'m-alg', tier:2, variant:3, type:'mc',
    q:'Engineering blends a 20% coolant solution with a 60% coolant solution to make 40 liters of a 35% solution. How many liters of the 60% solution are needed?',
    opts:['10','12','15','18'], ans:2,
    good:'a + b = 40 and 0.2a + 0.6b = 0.35(40) = 14. Substitute a = 40 − b: 8 − 0.2b + 0.6b = 14, so 0.4b = 6 and b = 15 liters.',
    bad:'Track the pure coolant: liters × concentration for each part must add to 40 × 0.35.' },

  // ===== alg-inequalities =====
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:0, variant:2, type:'mc',
    q:'The core stays stable only when <strong>3x − 4 > 14</strong>. What is the solution set?',
    opts:['x > 6','x < 6','x > 10','x < 10'], ans:0,
    good:'Add 4: 3x > 18. Divide by 3: x > 6.',
    bad:'Solve it like an equation — the sign only flips for a negative multiply/divide.' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:0, variant:3, type:'mc',
    q:'Mass limits require <strong>x + 4 ≤ 9</strong>. Which describes the allowed values of x?',
    opts:['x ≥ 5','x ≤ 5','x ≤ 13','x ≥ 13'], ans:1,
    good:'Subtract 4 from both sides: x ≤ 5.',
    bad:'Just subtract 4; the direction of the inequality does not change.' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:1, variant:2, type:'mc',
    q:'Thermal safety requires <strong>−2x + 5 < 17</strong>. What is the solution set?',
    opts:['x < −6','x > −6','x < 6','x > 6'], ans:1,
    good:'Subtract 5: −2x < 12. Dividing by −2 flips the sign: x > −6.',
    bad:'Dividing both sides by a negative reverses the inequality.' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'The hatch seal holds only when <strong>5(x − 1) ≥ 3x + 7</strong>. What is the solution set?',
    opts:['x ≥ 6','x ≤ 6','x ≥ 4','x ≤ 4'], ans:0,
    good:'Distribute: 5x − 5 ≥ 3x + 7. Then 2x ≥ 12, so x ≥ 6.',
    bad:'Distribute first, gather x terms, divide by a positive (no flip).' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:2, variant:2, type:'mc',
    q:'Fuel analysis gives <strong>x/3 − 2 > x/4 + 1</strong>. What is the solution set?',
    opts:['x > 36','x < 36','x > 12','x < 12'], ans:0,
    good:'Multiply everything by 12: 4x − 24 > 3x + 12, so x > 36.',
    bad:'Clear the fractions by multiplying through by 12 first.' },
  { skill:'alg-inequalities', name:'Linear inequalities', domain:'m-alg', tier:2, variant:3, type:'input',
    q:'The valve only opens when <strong>4x − 7 > 25</strong>, where x is a whole-number setting. What is the <em>smallest integer</em> value of x that opens the valve?',
    ans:9, ph:'x = ?',
    good:'4x > 32 gives x > 8. The smallest integer strictly greater than 8 is 9 (x = 8 itself does not satisfy the strict inequality).',
    bad:'Solve the inequality, then note the boundary value is excluded.' },

  // ===== alg-inequality-graphs =====
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:0, variant:2, type:'mc',
    q:'The safe zone is all points where <strong>y > 3x − 2</strong>. Which point is in the region?',
    opts:['(1, 0)','(2, 3)','(0, 5)','(1, 1)'], ans:2,
    good:'Test (0, 5): 5 > 3(0) − 2 = −2 is true. (1,0): 0 > 1 false; (2,3): 3 > 4 false; (1,1): 1 > 1 false (strict).',
    bad:'Plug each point in; a strict > excludes points exactly on the line.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:0, variant:3, type:'mc',
    q:'The clearance zone is <strong>y ≤ x − 3</strong>. Which point is inside the zone?',
    opts:['(8, 2)','(0, 0)','(2, 1)','(3, 4)'], ans:0,
    good:'Test (8, 2): 2 ≤ 8 − 3 = 5 is true. The others give 0 ≤ −3, 1 ≤ −1, 4 ≤ 0 — all false.',
    bad:'Check whether the y-value is at or below x − 3.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:1, variant:2, type:'mc',
    q:'Which best describes the graph of the exclusion rule <strong>y < 2x + 3</strong>?',
    opts:['The region above a dashed line through (0, 3) with slope 2','The region below a dashed line through (0, 3) with slope 2','The region below a solid line through (0, 3) with slope 2','The region above a solid line through (3, 0) with slope 2'], ans:1,
    good:'Strict inequality means a dashed boundary, and y less means the region below the line y = 2x + 3, which has y-intercept 3 and slope 2.',
    bad:'Strict < means dashed boundary; "y less than" shades below the line.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:1, variant:3, type:'mc',
    q:'A pod must sit where <strong>y < 2x</strong> AND <strong>y > x − 3</strong>. Which point satisfies both?',
    opts:['(0, 4)','(3, 2)','(−2, 0)','(5, 0)'], ans:1,
    good:'Test (3, 2): 2 < 6 is true and 2 > 0 is true. (0,4) fails 4 < 0; (−2,0) fails 0 < −4; (5,0) fails 0 > 2.',
    bad:'A solution point must satisfy every inequality, not just one.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:2, variant:2, type:'mc',
    q:'The overlap zone of <strong>y ≤ 3x − 2</strong> and <strong>y ≥ −2x + 8</strong> is bounded by two lines. At what point do those boundary lines intersect?',
    opts:['(2, 4)','(4, 2)','(1, 1)','(3, 2)'], ans:0,
    good:'Set 3x − 2 = −2x + 8: 5x = 10, so x = 2 and y = 3(2) − 2 = 4. The corner is (2, 4).',
    bad:'Set the two boundary lines equal to each other.' },
  { skill:'alg-inequality-graphs', name:'Inequality solution regions', domain:'m-alg', tier:2, variant:3, type:'mc',
    q:'The point <strong>(k, 0)</strong> lies in the solution region of <strong>y ≥ 2x − 8</strong>. Which must be true about k?',
    opts:['k ≤ 4','k ≥ 4','k ≤ 8','k ≥ 8'], ans:0,
    good:'Substitute the point: 0 ≥ 2k − 8, so 8 ≥ 2k and k ≤ 4.',
    bad:'Plug x = k and y = 0 into the inequality and solve for k.' }
);
