// SAT Math: Geometry & Trigonometry skill bank — Axiom-7
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ── geo-area: Area & perimeter ─────────────────────────────
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:0, variant:0, type:'input',
    q:'A hull panel on Axiom-7 is a rectangle <em>12 m</em> by <em>7 m</em>. What is its area in square meters?', ans:84, ph:'m²',
    good:'Panel logged: 12 × 7 = 84 m². The fabricator prints it perfectly.',
    bad:'Area of a rectangle is length × width: 12 × 7 = 84 m².' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:0, variant:1, type:'input',
    q:'A triangular solar-sail brace has a base of <em>10 m</em> and a height of <em>8 m</em>. What is its area in square meters?', ans:40, ph:'m²',
    good:'½ × 10 × 8 = 40 m². Brace area confirmed.',
    bad:'Triangle area is ½ × base × height = ½ × 10 × 8 = 40 m².' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:1, variant:0, type:'input',
    q:'A rectangular airlock door has an area of <em>48 m²</em> and a width of <em>6 m</em>. How many meters of sealing tape are needed for its perimeter?', ans:28, ph:'m',
    good:'Length = 48 ÷ 6 = 8, so perimeter = 2(8 + 6) = 28 m of tape.',
    bad:'First find the length: 48 ÷ 6 = 8 m. Then perimeter = 2(8 + 6) = 28 m.' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:1, variant:1, type:'input',
    q:'A square docking pad has a perimeter of <em>36 m</em>. What is its area in square meters?', ans:81, ph:'m²',
    good:'Side = 36 ÷ 4 = 9, so area = 9² = 81 m². Pad certified.',
    bad:'Each side is 36 ÷ 4 = 9 m, so the area is 9 × 9 = 81 m².' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:2, variant:0, type:'input',
    q:'An L-shaped cargo-bay floor is a <em>10 m × 6 m</em> rectangle with a <em>3 m × 2 m</em> rectangular corner cut out for a conduit shaft. What is the floor area in square meters?', ans:54, ph:'m²',
    good:'60 − 6 = 54 m². The conduit shaft fits and the floor plates ship out.',
    bad:'Full rectangle: 10 × 6 = 60 m². Subtract the notch: 3 × 2 = 6 m². Area = 54 m².' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:2, variant:1, type:'input',
    q:'An observation-deck window is a <em>14 m × 9 m</em> rectangle with a right triangle attached along one edge; the triangle&rsquo;s legs are <em>6 m</em> and <em>4 m</em>. What is the total window area in square meters?', ans:138, ph:'m²',
    good:'126 + 12 = 138 m² of starlight-grade glass. Beautiful.',
    bad:'Rectangle: 14 × 9 = 126. Triangle: ½ × 6 × 4 = 12. Total = 138 m².' },

  // ── geo-volume: Volume & surface area ──────────────────────
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:0, variant:0, type:'input',
    q:'A supply crate is a rectangular box <em>5 m × 4 m × 3 m</em>. What is its volume in cubic meters?', ans:60, ph:'m³',
    good:'5 × 4 × 3 = 60 m³. The crate slots into cargo bay two.',
    bad:'Volume of a box = length × width × height = 5 × 4 × 3 = 60 m³.' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:0, variant:1, type:'mc',
    q:'A cylindrical water tank has radius <em>3 m</em> and height <em>10 m</em>. What is its volume in cubic meters?',
    opts:['30π','60π','90π','120π'], ans:2,
    good:'V = πr²h = π(9)(10) = 90π m³. Hydration secured.',
    bad:'V = πr²h = π × 3² × 10 = 90π m³.' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:1, variant:0, type:'input',
    q:'A sensor housing is a box <em>4 m × 3 m × 2 m</em>. How many square meters of radiation shielding cover its entire surface?', ans:52, ph:'m²',
    good:'2(12 + 8 + 6) = 52 m² of shielding. Sensors protected.',
    bad:'Surface area = 2(lw + lh + wh) = 2(12 + 8 + 6) = 52 m².' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:1, variant:1, type:'mc',
    q:'A fuel cylinder has diameter <em>4 m</em> and height <em>7 m</em>. What is its volume in cubic meters?',
    opts:['14π','28π','56π','112π'], ans:1,
    good:'Radius = 2, so V = π(4)(7) = 28π m³. Careful — that was a diameter!',
    bad:'The radius is half the diameter: r = 2. V = πr²h = π × 4 × 7 = 28π m³.' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:2, variant:0, type:'input',
    q:'A cubic reactor core has a volume of <em>125 m³</em>. What is its total surface area in square meters?', ans:150, ph:'m²',
    good:'Side = ∛125 = 5, so surface area = 6 × 25 = 150 m². Core sealed.',
    bad:'Cube root of 125 is 5 m per side. Surface area = 6 × 5² = 150 m².' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:2, variant:1, type:'mc',
    q:'A closed cylindrical oxygen tank has radius <em>3 m</em> and height <em>5 m</em>. What is its total surface area (including both circular ends) in square meters?',
    opts:['30π','39π','45π','48π'], ans:3,
    good:'2πr² + 2πrh = 18π + 30π = 48π m². Tank coating ordered.',
    bad:'Two ends: 2π(3²) = 18π. Side: 2π(3)(5) = 30π. Total = 48π m².' },

  // ── geo-lines-angles: Lines & angles ───────────────────────
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:0, variant:0, type:'input',
    q:'Two support struts cross at a point. One of the angles formed measures <em>38°</em>. What is the measure, in degrees, of the angle directly opposite it?', ans:38, ph:'degrees',
    good:'Vertical angles are equal: 38°. Struts aligned.',
    bad:'Angles opposite each other at an intersection (vertical angles) are congruent: 38°.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:0, variant:1, type:'input',
    q:'An antenna arm meets the hull along a straight line, forming two angles. One measures <em>65°</em>. What is the other angle, in degrees?', ans:115, ph:'degrees',
    good:'180 − 65 = 115°. Antenna angle logged.',
    bad:'Angles on a straight line are supplementary: 180 − 65 = 115°.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:1, variant:0, type:'input',
    q:'Two parallel guide rails are crossed by a laser sightline (a transversal). The sightline makes a <em>110°</em> angle with the first rail. What is the measure, in degrees, of the same-side interior angle at the second rail?', ans:70, ph:'degrees',
    good:'Same-side interior angles sum to 180°: 180 − 110 = 70°.',
    bad:'Co-interior (same-side interior) angles between parallel lines are supplementary: 180 − 110 = 70°.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:1, variant:1, type:'input',
    q:'Three angles lie along a straight docking rail: <em>x°</em>, <em>2x°</em>, and <em>60°</em>. What is the value of x?', ans:40, ph:'x',
    good:'x + 2x + 60 = 180 → 3x = 120 → x = 40.',
    bad:'Angles on a line sum to 180: 3x + 60 = 180, so x = 40.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:2, variant:0, type:'input',
    q:'Two parallel conduits are cut by a transversal beam. Two same-side interior angles measure <em>(3x + 10)°</em> and <em>(2x − 15)°</em>. What is the value of x?', ans:37, ph:'x',
    good:'(3x+10) + (2x−15) = 180 → 5x − 5 = 180 → x = 37.',
    bad:'Same-side interior angles are supplementary: 5x − 5 = 180, so x = 37.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:2, variant:1, type:'input',
    q:'Four thruster mounts surround a pivot point, with angles <em>x°</em>, <em>(x + 20)°</em>, <em>2x°</em>, and <em>100°</em> making a full turn around the point. What is the value of x?', ans:60, ph:'x',
    good:'4x + 120 = 360 → x = 60. Thrusters balanced.',
    bad:'Angles around a point sum to 360: x + (x+20) + 2x + 100 = 360 → 4x = 240 → x = 60.' },

  // ── geo-triangles: Triangle properties ─────────────────────
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:0, variant:0, type:'input',
    q:'A triangular truss has two angles measuring <em>35°</em> and <em>65°</em>. What is the third angle, in degrees?', ans:80, ph:'degrees',
    good:'180 − 35 − 65 = 80°. Truss geometry checks out.',
    bad:'Triangle angles sum to 180°: 180 − 35 − 65 = 80°.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:0, variant:1, type:'input',
    q:'An isosceles antenna bracket has a vertex angle of <em>40°</em>. What is the measure, in degrees, of each base angle?', ans:70, ph:'degrees',
    good:'(180 − 40) ÷ 2 = 70° each. Symmetric and stable.',
    bad:'The two base angles are equal: (180 − 40) ÷ 2 = 70°.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:1, variant:0, type:'input',
    q:'A blueprint triangle has sides <em>6</em>, <em>8</em>, and <em>10</em>. A similar full-size brace has shortest side <em>9 m</em>. What is the length, in meters, of its longest side?', ans:15, ph:'m',
    good:'Scale factor 9/6 = 1.5, so 10 × 1.5 = 15 m.',
    bad:'Similar triangles keep side ratios: 9/6 = 1.5, so the longest side is 10 × 1.5 = 15 m.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:1, variant:1, type:'input',
    q:'One side of a triangular panel is extended past a vertex, forming an exterior angle. The two remote interior angles measure <em>45°</em> and <em>60°</em>. What is the exterior angle, in degrees?', ans:105, ph:'degrees',
    good:'Exterior angle = sum of remote interior angles = 45 + 60 = 105°.',
    bad:'An exterior angle equals the sum of the two remote interior angles: 45 + 60 = 105°.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:2, variant:0, type:'input',
    q:'A scale model of a support fin has sides <em>5</em>, <em>12</em>, and <em>13</em>. The full-size fin is similar and has a perimeter of <em>90 m</em>. What is the length, in meters, of its longest side?', ans:39, ph:'m',
    good:'Model perimeter = 30, so scale = 3. Longest side = 13 × 3 = 39 m.',
    bad:'Model perimeter is 5+12+13 = 30, so the scale factor is 90/30 = 3. Longest side = 13 × 3 = 39 m.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:2, variant:1, type:'input',
    q:'A triangular viewport has angles in the ratio <em>1 : 2 : 3</em>, so they measure <em>x°</em>, <em>2x°</em>, and <em>3x°</em>. What is the measure, in degrees, of the largest angle?', ans:90, ph:'degrees',
    good:'6x = 180 → x = 30 → largest = 3(30) = 90°. It&rsquo;s a right triangle!',
    bad:'x + 2x + 3x = 180 → x = 30, so the largest angle is 3 × 30 = 90°.' },

  // ── geo-right-triangles: Pythagorean theorem ───────────────
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:0, variant:0, type:'input',
    q:'A right-triangular brace has legs of <em>3 m</em> and <em>4 m</em>. How long, in meters, is its hypotenuse?', ans:5, ph:'m',
    good:'√(9 + 16) = √25 = 5 m. Classic 3-4-5.',
    bad:'a² + b² = c²: 9 + 16 = 25, so c = 5 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:0, variant:1, type:'input',
    q:'A maintenance drone flies <em>5 m</em> along one hull edge, then <em>12 m</em> along a perpendicular edge. How far, in meters, is it from its start point in a straight line?', ans:13, ph:'m',
    good:'√(25 + 144) = √169 = 13 m. The 5-12-13 family strikes again.',
    bad:'√(5² + 12²) = √169 = 13 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:1, variant:0, type:'input',
    q:'A support cable of length <em>17 m</em> runs from the top of a vertical mast to the deck. Its anchor point is <em>8 m</em> from the base of the mast. How tall, in meters, is the mast?', ans:15, ph:'m',
    good:'√(289 − 64) = √225 = 15 m. That&rsquo;s the 8-15-17 triple.',
    bad:'Leg = √(17² − 8²) = √225 = 15 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:1, variant:1, type:'input',
    q:'A cargo ramp <em>29 m</em> long rises from the deck to a hatch. The horizontal distance along the deck is <em>21 m</em>. What is the vertical height, in meters, of the hatch?', ans:20, ph:'m',
    good:'√(841 − 441) = √400 = 20 m. The 20-21-29 triple, deep cut.',
    bad:'Height = √(29² − 21²) = √400 = 20 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:2, variant:0, type:'input',
    q:'A <em>25 m</em> tether runs from the top of a <em>20 m</em> vertical comms mast to an anchor on the flat deck. During a storm drill, how far, in meters, is the anchor from the base of the mast?', ans:15, ph:'m',
    good:'√(625 − 400) = √225 = 15 m — a scaled 3-4-5 (15-20-25).',
    bad:'√(25² − 20²) = √225 = 15 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:2, variant:1, type:'input',
    q:'A rectangular blast door measures <em>16 m</em> by <em>30 m</em>. A reinforcing beam runs corner to corner. How long, in meters, is the beam?', ans:34, ph:'m',
    good:'√(256 + 900) = √1156 = 34 m — the 8-15-17 family doubled.',
    bad:'Diagonal = √(16² + 30²) = √1156 = 34 m.' },

  // ── geo-trig: Right-triangle trigonometry ──────────────────
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:0, variant:0, type:'mc',
    q:'In a right triangle inside the nav array, sin θ = 3/5. What is cos θ?',
    opts:['3/4','4/5','5/4','4/3'], ans:1,
    good:'3-4-5 triangle: opposite 3, hypotenuse 5, so adjacent = 4 and cos θ = 4/5.',
    bad:'If sin θ = 3/5, the sides are 3-4-5; cos θ = adjacent/hypotenuse = 4/5.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:0, variant:1, type:'mc',
    q:'A right triangle on the antenna schematic has legs <em>8</em> (opposite angle θ) and <em>15</em> (adjacent to θ), with hypotenuse <em>17</em>. What is tan θ?',
    opts:['8/17','15/17','8/15','15/8'], ans:2,
    good:'TOA: tan θ = opposite/adjacent = 8/15.',
    bad:'Tangent is opposite over adjacent: tan θ = 8/15.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:1, variant:0, type:'mc',
    q:'In a right triangle, cos θ = 12/13. What is tan θ?',
    opts:['5/13','12/5','5/12','13/12'], ans:2,
    good:'Adjacent 12, hypotenuse 13, so opposite = 5 (5-12-13). tan θ = 5/12.',
    bad:'The missing side is √(13² − 12²) = 5, so tan θ = opposite/adjacent = 5/12.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:1, variant:1, type:'input',
    q:'A landing beacon&rsquo;s beam makes angle θ with the deck, where tan θ = 3/4. The beam&rsquo;s hypotenuse path is <em>20 m</em>. What is the vertical rise, in meters (the side opposite θ)?', ans:12, ph:'m',
    good:'tan θ = 3/4 means a 3-4-5 shape; scale ×4 gives 12-16-20. Rise = 12 m.',
    bad:'tan θ = 3/4 gives a 3-4-5 triangle; hypotenuse 20 = 5 × 4, so the opposite side is 3 × 4 = 12 m.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:2, variant:0, type:'input',
    q:'The nav computer reports sin(2k + 10)° = cos(3k − 40)° for two acute angles. What is the value of k?', ans:24, ph:'k',
    good:'sin x = cos(90 − x), so (2k+10) + (3k−40) = 90 → 5k = 120 → k = 24.',
    bad:'Sine and cosine of complementary angles are equal: the angles sum to 90. 5k − 30 = 90 → k = 24.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:2, variant:1, type:'input',
    q:'For acute angles, sin 34° = cos w°. What is the value of w?', ans:56, ph:'w',
    good:'sin x = cos(90 − x): w = 90 − 34 = 56.',
    bad:'Complementary angle identity: sin 34° = cos(90° − 34°) = cos 56°, so w = 56.' },

  // ── geo-circles: Circles ───────────────────────────────────
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:0, variant:0, type:'mc',
    q:'A circular docking port has radius <em>6 m</em>. What is its circumference in meters?',
    opts:['6π','12π','24π','36π'], ans:1,
    good:'C = 2πr = 12π m. Port ring measured.',
    bad:'Circumference = 2πr = 2 × π × 6 = 12π m.' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:0, variant:1, type:'mc',
    q:'A circular radiation shield has radius <em>9 m</em>. What is its area in square meters?',
    opts:['18π','81π','9π','162π'], ans:1,
    good:'A = πr² = 81π m² of shielding.',
    bad:'Area = πr² = π × 9² = 81π m².' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:1, variant:0, type:'mc',
    q:'A shuttle traces an arc along a circular orbit of radius <em>12 km</em>, sweeping a central angle of <em>60°</em>. How long is the arc, in kilometers?',
    opts:['2π','4π','6π','8π'], ans:1,
    good:'Arc = (60/360) × 2π(12) = (1/6)(24π) = 4π km.',
    bad:'Arc length = (central angle/360) × circumference = (1/6) × 24π = 4π km.' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:1, variant:1, type:'mc',
    q:'A ring corridor has circumference <em>20π m</em>. What is the area of the circle it encloses, in square meters?',
    opts:['100π','40π','400π','20π'], ans:0,
    good:'2πr = 20π → r = 10, so A = 100π m².',
    bad:'From C = 2πr = 20π, r = 10. Area = πr² = 100π m².' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:2, variant:0, type:'mc',
    q:'A pie-slice sensor sweep covers a <em>45°</em> sector of a circle with radius <em>8 km</em>. What area, in square kilometers, does the sweep cover?',
    opts:['4π','8π','16π','32π'], ans:1,
    good:'(45/360) × π(64) = (1/8)(64π) = 8π km².',
    bad:'Sector area = (45/360) × πr² = (1/8) × 64π = 8π km².' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:2, variant:1, type:'input',
    q:'On a circular orbit of radius <em>9 km</em>, a probe travels an arc of length <em>5π km</em>. What central angle, in degrees, does the arc subtend?', ans:100, ph:'degrees',
    good:'Circumference = 18π; (5π/18π) × 360 = 100°.',
    bad:'Angle = (arc/circumference) × 360 = (5π / 18π) × 360 = 100°.' },

  // ── geo-circle-eq: Circle equations ────────────────────────
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:0, variant:0, type:'mc',
    q:'A shield perimeter is modeled by (x − 3)² + (y + 2)² = 25 on the station grid. What are the coordinates of its center?',
    opts:['(3, −2)','(−3, 2)','(3, 2)','(−3, −2)'], ans:0,
    good:'(x − h)² + (y − k)² = r² gives center (3, −2) — signs flip!',
    bad:'The standard form (x − h)² + (y − k)² = r² means the center is (3, −2).' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:0, variant:1, type:'input',
    q:'A comms range circle is (x + 1)² + (y − 4)² = 49. What is its radius, in grid units?', ans:7, ph:'units',
    good:'r² = 49 → r = 7 units. Range confirmed.',
    bad:'The right side equals r², so r = √49 = 7.' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:1, variant:0, type:'mc',
    q:'A patrol drone circles the point (2, −5) at a constant distance of <em>6</em> grid units. Which equation models its path?',
    opts:['(x + 2)² + (y − 5)² = 6','(x − 2)² + (y + 5)² = 6','(x − 2)² + (y + 5)² = 36','(x + 2)² + (y − 5)² = 36'], ans:2,
    good:'Center (2, −5) and r = 6: (x − 2)² + (y + 5)² = 36. Remember to square the radius.',
    bad:'Use (x − h)² + (y − k)² = r² with h = 2, k = −5, r² = 36.' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:1, variant:1, type:'input',
    q:'A defense ring is centered at (0, 3) and passes through the beacon at (4, 6). What is the ring&rsquo;s radius, in grid units?', ans:5, ph:'units',
    good:'r = √((4−0)² + (6−3)²) = √(16 + 9) = 5 units.',
    bad:'Radius is the distance from center to a point on the circle: √(4² + 3²) = 5.' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:2, variant:0, type:'input',
    q:'A debris field boundary satisfies x² + y² − 6x + 4y − 12 = 0. What is the radius of the boundary circle, in grid units?', ans:5, ph:'units',
    good:'Completing the square: (x − 3)² + (y + 2)² = 12 + 9 + 4 = 25, so r = 5.',
    bad:'Complete the square: (x² − 6x + 9) + (y² + 4y + 4) = 12 + 9 + 4, giving (x−3)² + (y+2)² = 25. r = 5.' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:2, variant:1, type:'mc',
    q:'A tractor-beam field satisfies x² + y² + 8x − 2y + 8 = 0. What are the coordinates of its center?',
    opts:['(4, −1)','(−4, 1)','(−8, 2)','(8, −2)'], ans:1,
    good:'Completing the square: (x + 4)² + (y − 1)² = 9, so the center is (−4, 1).',
    bad:'(x² + 8x + 16) + (y² − 2y + 1) = −8 + 16 + 1 = 9, so (x+4)² + (y−1)² = 9. Center (−4, 1).' }
);
