// SAT Math: Geometry & Trigonometry skill bank — Axiom-7 — variants C & D
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ── geo-area: Area & perimeter ─────────────────────────────
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:0, variant:2, type:'input',
    q:'A rectangular viewport gasket is <em>15 m</em> long and <em>4 m</em> wide. What is its area in square meters?', ans:60, ph:'m²',
    good:'15 × 4 = 60 m². Gasket cut and fitted.',
    bad:'Area of a rectangle = length × width = 15 × 4 = 60 m².' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:0, variant:3, type:'input',
    q:'A triangular deflector plate has a base of <em>14 m</em> and a height of <em>9 m</em>. What is its area in square meters?', ans:63, ph:'m²',
    good:'½ × 14 × 9 = 63 m². Deflector plate logged.',
    bad:'Triangle area = ½ × base × height = ½ × 14 × 9 = 63 m².' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:1, variant:2, type:'input',
    q:'A rectangular coolant panel has an area of <em>72 m²</em> and a length of <em>12 m</em>. How many meters of edge trim are needed for its perimeter?', ans:36, ph:'m',
    good:'Width = 72 ÷ 12 = 6, so perimeter = 2(12 + 6) = 36 m of trim.',
    bad:'Width = 72 ÷ 12 = 6 m. Perimeter = 2(12 + 6) = 36 m.' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:1, variant:3, type:'input',
    q:'A square hangar hatch has a perimeter of <em>44 m</em>. What is its area in square meters?', ans:121, ph:'m²',
    good:'Side = 44 ÷ 4 = 11, so area = 11² = 121 m². Hatch certified.',
    bad:'Each side is 44 ÷ 4 = 11 m, so area = 11 × 11 = 121 m².' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:2, variant:2, type:'input',
    q:'An L-shaped maintenance walkway is a <em>12 m × 8 m</em> rectangle with a <em>5 m × 4 m</em> rectangular corner removed for a ladder well. What is the walkway area in square meters?', ans:76, ph:'m²',
    good:'96 − 20 = 76 m². The ladder well clears and the plates ship.',
    bad:'Full rectangle: 12 × 8 = 96 m². Subtract the well: 5 × 4 = 20 m². Area = 76 m².' },
  { skill:'geo-area', name:'Area & perimeter', domain:'m-geo', tier:2, variant:3, type:'input',
    q:'A signal-dish backing is a <em>20 m × 8 m</em> rectangle with a right triangle attached along one edge; the triangle&rsquo;s legs are <em>8 m</em> and <em>5 m</em>. What is the total backing area in square meters?', ans:180, ph:'m²',
    good:'160 + 20 = 180 m² of backing. Dish mounted.',
    bad:'Rectangle: 20 × 8 = 160. Triangle: ½ × 8 × 5 = 20. Total = 180 m².' },

  // ── geo-volume: Volume & surface area ──────────────────────
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:0, variant:2, type:'input',
    q:'A ration locker is a rectangular box <em>6 m × 5 m × 2 m</em>. What is its volume in cubic meters?', ans:60, ph:'m³',
    good:'6 × 5 × 2 = 60 m³. Locker stowed in the galley.',
    bad:'Volume of a box = length × width × height = 6 × 5 × 2 = 60 m³.' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:0, variant:3, type:'mc',
    q:'A cylindrical coolant reservoir has radius <em>5 m</em> and height <em>4 m</em>. What is its volume in cubic meters?',
    opts:['20π','40π','100π','200π'], ans:2,
    good:'V = πr²h = π(25)(4) = 100π m³. Coolant loaded.',
    bad:'V = πr²h = π × 5² × 4 = 100π m³.' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:1, variant:2, type:'input',
    q:'A relay module is a box <em>5 m × 4 m × 3 m</em>. How many square meters of thermal wrap cover its entire surface?', ans:94, ph:'m²',
    good:'2(20 + 15 + 12) = 94 m² of wrap. Module insulated.',
    bad:'Surface area = 2(lw + lh + wh) = 2(20 + 15 + 12) = 94 m².' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:1, variant:3, type:'mc',
    q:'A pressurized gas cylinder has diameter <em>6 m</em> and height <em>8 m</em>. What is its volume in cubic meters?',
    opts:['24π','48π','72π','144π'], ans:2,
    good:'Radius = 3, so V = π(9)(8) = 72π m³. Watch the diameter!',
    bad:'The radius is half the diameter: r = 3. V = πr²h = π × 9 × 8 = 72π m³.' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:2, variant:2, type:'input',
    q:'A cubic shielding block has a volume of <em>216 m³</em>. What is its total surface area in square meters?', ans:216, ph:'m²',
    good:'Side = ∛216 = 6, so surface area = 6 × 36 = 216 m². Block sealed.',
    bad:'Cube root of 216 is 6 m per side. Surface area = 6 × 6² = 216 m².' },
  { skill:'geo-volume', name:'Volume & surface area', domain:'m-geo', tier:2, variant:3, type:'mc',
    q:'A closed cylindrical nitrogen tank has radius <em>4 m</em> and height <em>6 m</em>. What is its total surface area (including both circular ends) in square meters?',
    opts:['48π','56π','80π','96π'], ans:2,
    good:'2πr² + 2πrh = 32π + 48π = 80π m². Coating ordered.',
    bad:'Two ends: 2π(4²) = 32π. Side: 2π(4)(6) = 48π. Total = 80π m².' },

  // ── geo-lines-angles: Lines & angles ───────────────────────
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:0, variant:2, type:'input',
    q:'Two conduit runs cross at a junction. One of the angles formed measures <em>52°</em>. What is the measure, in degrees, of the angle directly opposite it?', ans:52, ph:'degrees',
    good:'Vertical angles are equal: 52°. Conduits aligned.',
    bad:'Vertical (opposite) angles at an intersection are congruent: 52°.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:0, variant:3, type:'input',
    q:'A gauge needle meets a straight scale line, forming two angles. One measures <em>73°</em>. What is the other angle, in degrees?', ans:107, ph:'degrees',
    good:'180 − 73 = 107°. Needle angle logged.',
    bad:'Angles on a straight line are supplementary: 180 − 73 = 107°.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:1, variant:2, type:'input',
    q:'Two parallel deck rails are crossed by a transversal cable. The cable makes an <em>85°</em> angle with the first rail. What is the measure, in degrees, of the corresponding angle at the second rail?', ans:85, ph:'degrees',
    good:'Corresponding angles between parallel lines are equal: 85°.',
    bad:'Corresponding angles formed by a transversal across parallel lines are congruent: 85°.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:1, variant:3, type:'input',
    q:'Three angles lie along a straight guide bar: <em>x°</em>, <em>3x°</em>, and <em>40°</em>. What is the value of x?', ans:35, ph:'x',
    good:'x + 3x + 40 = 180 → 4x = 140 → x = 35.',
    bad:'Angles on a line sum to 180: 4x + 40 = 180, so x = 35.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:2, variant:2, type:'input',
    q:'Two parallel beams are cut by a transversal strut. Two corresponding angles measure <em>(4x − 5)°</em> and <em>(2x + 35)°</em>. What is the value of x?', ans:20, ph:'x',
    good:'Corresponding angles are equal: 4x − 5 = 2x + 35 → 2x = 40 → x = 20.',
    bad:'Set the corresponding angles equal: 4x − 5 = 2x + 35, so x = 20.' },
  { skill:'geo-lines-angles', name:'Lines & angles', domain:'m-geo', tier:2, variant:3, type:'input',
    q:'Four gyro arms surround a pivot, with angles <em>2x°</em>, <em>(x + 10)°</em>, <em>3x°</em>, and <em>50°</em> making a full turn around the point. What is the value of x?', ans:50, ph:'x',
    good:'6x + 60 = 360 → x = 50. Gyros balanced.',
    bad:'Angles around a point sum to 360: 2x + (x+10) + 3x + 50 = 360 → 6x = 300 → x = 50.' },

  // ── geo-triangles: Triangle properties ─────────────────────
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:0, variant:2, type:'input',
    q:'A triangular gusset has two angles measuring <em>48°</em> and <em>57°</em>. What is the third angle, in degrees?', ans:75, ph:'degrees',
    good:'180 − 48 − 57 = 75°. Gusset geometry checks out.',
    bad:'Triangle angles sum to 180°: 180 − 48 − 57 = 75°.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:0, variant:3, type:'input',
    q:'An isosceles mounting bracket has a vertex angle of <em>50°</em>. What is the measure, in degrees, of each base angle?', ans:65, ph:'degrees',
    good:'(180 − 50) ÷ 2 = 65° each. Symmetric and stable.',
    bad:'The base angles are equal: (180 − 50) ÷ 2 = 65°.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:1, variant:2, type:'input',
    q:'A blueprint triangle has sides <em>5</em>, <em>12</em>, and <em>13</em>. A similar full-size brace has shortest side <em>15 m</em>. What is the length, in meters, of its longest side?', ans:39, ph:'m',
    good:'Scale factor 15/5 = 3, so 13 × 3 = 39 m.',
    bad:'Similar triangles keep side ratios: 15/5 = 3, so the longest side is 13 × 3 = 39 m.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:1, variant:3, type:'input',
    q:'One side of a triangular fin is extended past a vertex, forming an exterior angle. The two remote interior angles measure <em>52°</em> and <em>73°</em>. What is the exterior angle, in degrees?', ans:125, ph:'degrees',
    good:'Exterior angle = sum of remote interior angles = 52 + 73 = 125°.',
    bad:'An exterior angle equals the sum of the two remote interior angles: 52 + 73 = 125°.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:2, variant:2, type:'input',
    q:'A scale model of a strut has sides <em>3</em>, <em>4</em>, and <em>5</em>. The full-size strut is similar and has a perimeter of <em>60 m</em>. What is the length, in meters, of its longest side?', ans:25, ph:'m',
    good:'Model perimeter = 12, so scale = 5. Longest side = 5 × 5 = 25 m.',
    bad:'Model perimeter is 3+4+5 = 12, so the scale factor is 60/12 = 5. Longest side = 5 × 5 = 25 m.' },
  { skill:'geo-triangles', name:'Triangle properties', domain:'m-geo', tier:2, variant:3, type:'input',
    q:'A triangular hatch frame has angles in the ratio <em>2 : 3 : 4</em>, so they measure <em>2x°</em>, <em>3x°</em>, and <em>4x°</em>. What is the measure, in degrees, of the largest angle?', ans:80, ph:'degrees',
    good:'9x = 180 → x = 20 → largest = 4(20) = 80°.',
    bad:'2x + 3x + 4x = 180 → x = 20, so the largest angle is 4 × 20 = 80°.' },

  // ── geo-right-triangles: Pythagorean theorem ───────────────
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:0, variant:2, type:'input',
    q:'A right-triangular gusset has legs of <em>6 m</em> and <em>8 m</em>. How long, in meters, is its hypotenuse?', ans:10, ph:'m',
    good:'√(36 + 64) = √100 = 10 m. A scaled 3-4-5.',
    bad:'a² + b² = c²: 36 + 64 = 100, so c = 10 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:0, variant:3, type:'input',
    q:'A repair pod moves <em>9 m</em> along one bulkhead, then <em>12 m</em> along a perpendicular bulkhead. How far, in meters, is it from its start point in a straight line?', ans:15, ph:'m',
    good:'√(81 + 144) = √225 = 15 m. Another 3-4-5 multiple (9-12-15).',
    bad:'√(9² + 12²) = √225 = 15 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:1, variant:2, type:'input',
    q:'A guy wire of length <em>25 m</em> runs from the top of a vertical pylon to the deck. Its anchor is <em>7 m</em> from the base. How tall, in meters, is the pylon?', ans:24, ph:'m',
    good:'√(625 − 49) = √576 = 24 m. That&rsquo;s the 7-24-25 triple.',
    bad:'Leg = √(25² − 7²) = √576 = 24 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:1, variant:3, type:'input',
    q:'A boarding ramp <em>41 m</em> long rises from the deck to a hatch. The horizontal run along the deck is <em>40 m</em>. What is the vertical height, in meters, of the hatch?', ans:9, ph:'m',
    good:'√(1681 − 1600) = √81 = 9 m. The 9-40-41 triple.',
    bad:'Height = √(41² − 40²) = √81 = 9 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:2, variant:2, type:'input',
    q:'A <em>26 m</em> tether runs from the top of a <em>24 m</em> vertical sensor mast to an anchor on the flat deck. How far, in meters, is the anchor from the base of the mast?', ans:10, ph:'m',
    good:'√(676 − 576) = √100 = 10 m — a scaled 5-12-13 (10-24-26).',
    bad:'√(26² − 24²) = √100 = 10 m.' },
  { skill:'geo-right-triangles', name:'Right triangles & Pythagorean theorem', domain:'m-geo', tier:2, variant:3, type:'input',
    q:'A rectangular bulkhead panel measures <em>9 m</em> by <em>40 m</em>. A diagonal brace runs corner to corner. How long, in meters, is the brace?', ans:41, ph:'m',
    good:'√(81 + 1600) = √1681 = 41 m — the 9-40-41 triple.',
    bad:'Diagonal = √(9² + 40²) = √1681 = 41 m.' },

  // ── geo-trig: Right-triangle trigonometry ──────────────────
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:0, variant:2, type:'mc',
    q:'In a right triangle inside the guidance array, cos θ = 3/5. What is sin θ?',
    opts:['3/4','4/5','5/3','4/3'], ans:1,
    good:'3-4-5 triangle: adjacent 3, hypotenuse 5, so opposite = 4 and sin θ = 4/5.',
    bad:'If cos θ = 3/5, the sides are 3-4-5; sin θ = opposite/hypotenuse = 4/5.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:0, variant:3, type:'mc',
    q:'A right triangle on the strut schematic has legs <em>7</em> (opposite angle θ) and <em>24</em> (adjacent to θ), with hypotenuse <em>25</em>. What is sin θ?',
    opts:['7/24','24/25','7/25','24/7'], ans:2,
    good:'SOH: sin θ = opposite/hypotenuse = 7/25.',
    bad:'Sine is opposite over hypotenuse: sin θ = 7/25.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:1, variant:2, type:'mc',
    q:'In a right triangle, sin θ = 8/17. What is tan θ?',
    opts:['8/15','15/17','15/8','17/8'], ans:0,
    good:'Opposite 8, hypotenuse 17, so adjacent = 15 (8-15-17). tan θ = 8/15.',
    bad:'The missing side is √(17² − 8²) = 15, so tan θ = opposite/adjacent = 8/15.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:1, variant:3, type:'input',
    q:'A tracking laser makes angle θ with the deck, where tan θ = 5/12. The beam&rsquo;s hypotenuse path is <em>26 m</em>. What is the vertical rise, in meters (the side opposite θ)?', ans:10, ph:'m',
    good:'tan θ = 5/12 means a 5-12-13 shape; scale ×2 gives 10-24-26. Rise = 10 m.',
    bad:'tan θ = 5/12 gives a 5-12-13 triangle; hypotenuse 26 = 13 × 2, so the opposite side is 5 × 2 = 10 m.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:2, variant:2, type:'input',
    q:'The nav computer reports sin(3k − 6)° = cos(k + 20)° for two acute angles. What is the value of k?', ans:19, ph:'k',
    good:'sin x = cos(90 − x), so (3k−6) + (k+20) = 90 → 4k = 76 → k = 19.',
    bad:'Complementary angles sum to 90: (3k−6) + (k+20) = 90 → 4k + 14 = 90 → k = 19.' },
  { skill:'geo-trig', name:'Right-triangle trigonometry', domain:'m-geo', tier:2, variant:3, type:'input',
    q:'For acute angles, cos 61° = sin p°. What is the value of p?', ans:29, ph:'p',
    good:'cos x = sin(90 − x): p = 90 − 61 = 29.',
    bad:'Complementary angle identity: cos 61° = sin(90° − 61°) = sin 29°, so p = 29.' },

  // ── geo-circles: Circles ───────────────────────────────────
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:0, variant:2, type:'mc',
    q:'A circular access hatch has radius <em>8 m</em>. What is its circumference in meters?',
    opts:['8π','16π','32π','64π'], ans:1,
    good:'C = 2πr = 16π m. Hatch ring measured.',
    bad:'Circumference = 2πr = 2 × π × 8 = 16π m.' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:0, variant:3, type:'mc',
    q:'A circular heat shield has radius <em>10 m</em>. What is its area in square meters?',
    opts:['20π','100π','10π','50π'], ans:1,
    good:'A = πr² = 100π m² of shielding.',
    bad:'Area = πr² = π × 10² = 100π m².' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:1, variant:2, type:'mc',
    q:'A shuttle traces an arc along a circular orbit of radius <em>18 km</em>, sweeping a central angle of <em>120°</em>. How long is the arc, in kilometers?',
    opts:['6π','12π','18π','24π'], ans:1,
    good:'Arc = (120/360) × 2π(18) = (1/3)(36π) = 12π km.',
    bad:'Arc length = (central angle/360) × circumference = (1/3) × 36π = 12π km.' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:1, variant:3, type:'mc',
    q:'A ring habitat has circumference <em>28π m</em>. What is the area of the circle it encloses, in square meters?',
    opts:['196π','49π','784π','28π'], ans:0,
    good:'2πr = 28π → r = 14, so A = 196π m².',
    bad:'From C = 2πr = 28π, r = 14. Area = πr² = 196π m².' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:2, variant:2, type:'mc',
    q:'A radar sweep covers a <em>135°</em> sector of a circle with radius <em>8 km</em>. What area, in square kilometers, does the sweep cover?',
    opts:['16π','24π','32π','48π'], ans:1,
    good:'(135/360) × π(64) = (3/8)(64π) = 24π km².',
    bad:'Sector area = (135/360) × πr² = (3/8) × 64π = 24π km².' },
  { skill:'geo-circles', name:'Circles: circumference, area & arcs', domain:'m-geo', tier:2, variant:3, type:'input',
    q:'On a circular orbit of radius <em>12 km</em>, a probe travels an arc of length <em>8π km</em>. What central angle, in degrees, does the arc subtend?', ans:120, ph:'degrees',
    good:'Circumference = 24π; (8π/24π) × 360 = 120°.',
    bad:'Angle = (arc/circumference) × 360 = (8π / 24π) × 360 = 120°.' },

  // ── geo-circle-eq: Circle equations ────────────────────────
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:0, variant:2, type:'mc',
    q:'A containment field is modeled by (x − 5)² + (y + 7)² = 36 on the station grid. What are the coordinates of its center?',
    opts:['(5, −7)','(−5, 7)','(5, 7)','(−5, −7)'], ans:0,
    good:'(x − h)² + (y − k)² = r² gives center (5, −7) — signs flip!',
    bad:'The standard form (x − h)² + (y − k)² = r² means the center is (5, −7).' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:0, variant:3, type:'input',
    q:'A scanner range circle is (x + 6)² + (y − 2)² = 64. What is its radius, in grid units?', ans:8, ph:'units',
    good:'r² = 64 → r = 8 units. Range confirmed.',
    bad:'The right side equals r², so r = √64 = 8.' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:1, variant:2, type:'mc',
    q:'A survey drone circles the point (−3, 4) at a constant distance of <em>7</em> grid units. Which equation models its path?',
    opts:['(x − 3)² + (y + 4)² = 7','(x + 3)² + (y − 4)² = 49','(x − 3)² + (y + 4)² = 49','(x + 3)² + (y − 4)² = 7'], ans:1,
    good:'Center (−3, 4) and r = 7: (x + 3)² + (y − 4)² = 49. Square the radius.',
    bad:'Use (x − h)² + (y − k)² = r² with h = −3, k = 4, r² = 49.' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:1, variant:3, type:'input',
    q:'A patrol ring is centered at (1, −2) and passes through the marker at (9, 4). What is the ring&rsquo;s radius, in grid units?', ans:10, ph:'units',
    good:'r = √((9−1)² + (4−(−2))²) = √(64 + 36) = 10 units.',
    bad:'Radius is the distance from center to a point: √(8² + 6²) = √100 = 10.' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:2, variant:2, type:'input',
    q:'A quarantine boundary satisfies x² + y² − 10x + 6y + 18 = 0. What is the radius of the boundary circle, in grid units?', ans:4, ph:'units',
    good:'Completing the square: (x − 5)² + (y + 3)² = −18 + 25 + 9 = 16, so r = 4.',
    bad:'Complete the square: (x² − 10x + 25) + (y² + 6y + 9) = −18 + 25 + 9, giving (x−5)² + (y+3)² = 16. r = 4.' },
  { skill:'geo-circle-eq', name:'Circle equations in the coordinate plane', domain:'m-geo', tier:2, variant:3, type:'mc',
    q:'A shield field satisfies x² + y² − 4x + 10y + 20 = 0. What are the coordinates of its center?',
    opts:['(2, −5)','(−2, 5)','(4, −10)','(−4, 10)'], ans:0,
    good:'Completing the square: (x − 2)² + (y + 5)² = 9, so the center is (2, −5).',
    bad:'(x² − 4x + 4) + (y² + 10y + 25) = −20 + 4 + 25 = 9, so (x−2)² + (y+5)² = 9. Center (2, −5).' }
);
