// SAT Math: Problem-Solving & Data Analysis skill bank — Axiom-7 — variants C & D
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ---------- psda-ratios ----------
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:0, variant:2, type:'input',
    q:'The coolant-to-solvent mixing ratio in the reactor loop must be <strong>2 : 7</strong>. If there are 14 liters of coolant, how many liters of solvent are needed?',
    ans:49, ph:'liters = ?',
    good:'14 is 2 × 7, so solvent is 7 × 7 = 49.',
    bad:'Scale the ratio: 14/2 = 7, so solvent = 7 · 7 = 49.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:0, variant:3, type:'input',
    q:'A cargo lift raises 240 kg of supplies in 4 minutes at a constant rate. Enter its rate in kg per minute.',
    ans:60, ph:'kg/min = ?',
    good:'240 / 4 = 60 kg per minute.',
    bad:'Rate = mass / time = 240 / 4 = 60 kg/min.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:1, variant:2, type:'input',
    q:'The technician-to-engineer ratio in the hangar is <strong>5 : 3</strong>. If there are 48 personnel in total, how many are engineers?',
    ans:18, ph:'engineers = ?',
    good:'Each ratio unit is 48/8 = 6, so engineers = 3 · 6 = 18.',
    bad:'5 + 3 = 8 parts; 48/8 = 6 per part; engineers = 3 · 6 = 18.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:1, variant:3, type:'input',
    q:'A recycler processes 54 kg of waste in 9 hours at a constant rate. How many kg can it process in 15 hours?',
    ans:90, ph:'kg = ?',
    good:'54/9 = 6 kg per hour; 6 · 15 = 90.',
    bad:'Find the unit rate: 54/9 = 6 kg/hour, then 6 · 15 = 90.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:2, variant:2, type:'input',
    q:'In the fuel lab, additive X to Y is <strong>3 : 4</strong> and Y to Z is <strong>2 : 5</strong>. If there are 18 units of X, how many units of Z?',
    ans:60, ph:'units of Z = ?',
    good:'X : Y : Z = 6 : 8 : 20. With X = 18 (3 × 6), Z = 3 × 20 = 60.',
    bad:'Combine ratios: X:Y:Z = 6:8:20. Since X = 18 = 3·6, Z = 3·20 = 60.' },
  { skill:'psda-ratios', name:'Ratios & rates', domain:'m-psda', tier:2, variant:3, type:'input',
    q:'Conveyor A moves 25 crates per hour and conveyor B moves 35 crates per hour. Running together, how many <strong>hours</strong> to move 300 crates?',
    ans:5, ph:'hours = ?',
    good:'Combined rate 60 crates/hour; 300/60 = 5 hours.',
    bad:'Add the rates: 25 + 35 = 60 crates/hour. Then 300 / 60 = 5 hours.' },

  // ---------- psda-proportions ----------
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:0, variant:2, type:'input',
    q:'Solve the alignment proportion <strong>3/7 = x/28</strong>.',
    ans:12, ph:'x = ?',
    good:'Cross-multiply: 7x = 84, so x = 12.',
    bad:'3 · 28 = 7x, so x = 84/7 = 12.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:0, variant:3, type:'input',
    q:'On the sector schematic, 3 cm represents 12 km of terrain. A ridge measures 7 cm on the schematic. How many km is that?',
    ans:28, ph:'km = ?',
    good:'Each cm is 4 km, so 7 · 4 = 28 km.',
    bad:'Set up 3/12 = 7/x: x = (7 · 12)/3 = 28 km.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:1, variant:2, type:'input',
    q:'The greenhouse uses 7 grams of fertilizer per 4 seed trays. How many grams are needed for 20 seed trays?',
    ans:35, ph:'grams = ?',
    good:'20 trays is 5 groups of 4, so 5 · 7 = 35 grams.',
    bad:'7/4 = x/20, so x = (7 · 20)/4 = 35.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:1, variant:3, type:'input',
    q:'Under the floodlights, a 3-meter mast casts a 5-meter shadow. At the same moment, the radar tower casts a 30-meter shadow. How tall is the tower in meters?',
    ans:18, ph:'meters = ?',
    good:'3/5 = h/30, so h = 18 meters.',
    bad:'Similar triangles: height/shadow is constant, so h = 30 · (3/5) = 18.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:2, variant:2, type:'input',
    q:'A coolant blend satisfies <strong>x/(x + 8) = 3/7</strong>. Solve for x.',
    ans:6, ph:'x = ?',
    good:'7x = 3x + 24, so 4x = 24 and x = 6.',
    bad:'Cross-multiply: 7x = 3(x + 8) = 3x + 24, so x = 6.' },
  { skill:'psda-proportions', name:'Proportions', domain:'m-psda', tier:2, variant:3, type:'input',
    q:'For a fixed job, the number of drones and the time to finish are <strong>inversely</strong> proportional. With 4 drones the job takes 45 minutes. Enter the time (minutes) with 6 drones.',
    ans:30, ph:'minutes = ?',
    good:'Drones · time = 180 stays constant, so time = 180/6 = 30 minutes.',
    bad:'Inverse proportion: drones·time is constant. 4 · 45 = 180, so time = 180/6 = 30.' },

  // ---------- psda-units ----------
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:0, variant:2, type:'input',
    q:'A coolant line holds 4 liters. Enter its volume in milliliters.',
    ans:4000, ph:'milliliters = ?',
    good:'4 · 1000 = 4000 milliliters.',
    bad:'1 L = 1000 mL, so 4 L = 4000 mL.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:0, variant:3, type:'input',
    q:'A docking procedure lasts 4 minutes. Enter that duration in seconds.',
    ans:240, ph:'seconds = ?',
    good:'4 · 60 = 240 seconds.',
    bad:'1 minute = 60 seconds, so 4 minutes = 240 seconds.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:1, variant:2, type:'input',
    q:'A maglev pod cruises at 108 km per hour. Enter its speed in meters per second.',
    ans:30, ph:'m/s = ?',
    good:'108 · 1000 / 3600 = 30 m/s.',
    bad:'Multiply by 1000 m/km and divide by 3600 s/h: 108000/3600 = 30.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:1, variant:3, type:'input',
    q:'A fuel cell has a mass of 3.2 kg. Enter its mass in grams.',
    ans:3200, ph:'grams = ?',
    good:'3.2 · 1000 = 3200 grams.',
    bad:'1 kg = 1000 g, so 3.2 kg = 3200 g.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:2, variant:2, type:'input',
    q:'A transport pod glides at 25 meters per second. Enter its speed in km per hour.',
    ans:90, ph:'km/h = ?',
    good:'25 · 3600 / 1000 = 90 km/h.',
    bad:'25 m/s · 3600 s/h = 90000 m/h = 90 km/h.' },
  { skill:'psda-units', name:'Unit conversion', domain:'m-psda', tier:2, variant:3, type:'input',
    q:'A scrubber uses 15 grams of filtrate per hour. How many <strong>grams</strong> are needed for a full 5-day run?',
    ans:1800, ph:'grams = ?',
    good:'5 days = 120 hours; 120 · 15 = 1800 grams.',
    bad:'5 · 24 = 120 hours, then 120 · 15 = 1800 grams.' },

  // ---------- psda-percent ----------
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:0, variant:2, type:'input',
    q:'A water tank holds 400 liters and is at 15% capacity. Enter the liters currently in the tank.',
    ans:60, ph:'liters = ?',
    good:'0.15 · 400 = 60 liters.',
    bad:'15% of 400 = 0.15 · 400 = 60.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:0, variant:3, type:'input',
    q:'56 of the 160 stored modules are flagged for repair. What <strong>percent</strong> are flagged?',
    ans:35, ph:'percent = ?',
    good:'56/160 = 0.35 = 35%.',
    bad:'Divide: 56/160 = 0.35, which is 35%.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:1, variant:2, type:'input',
    q:'Daily data throughput fell from 150 GB to 120 GB after a routing fix. Enter the <strong>percent decrease</strong>.',
    ans:20, ph:'percent = ?',
    good:'Decrease of 30 over the original 150: 30/150 = 20%.',
    bad:'Percent change = (150 − 120)/150 = 0.20 = 20%. Divide by the ORIGINAL value.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:1, variant:3, type:'input',
    q:'A sensor module lists at 350 credits, with a 40% clearance discount. Enter the discounted price in credits.',
    ans:210, ph:'credits = ?',
    good:'350 · 0.60 = 210 credits.',
    bad:'40% off leaves 60%: 350 · 0.6 = 210.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:2, variant:2, type:'input',
    q:'After a 25% discount, a coolant pump costs 150 credits. Enter the <strong>original</strong> price in credits.',
    ans:200, ph:'credits = ?',
    good:'150 is 75% of the original: 150 / 0.75 = 200.',
    bad:'Reverse the percent: original · 0.75 = 150, so original = 150/0.75 = 200.' },
  { skill:'psda-percent', name:'Percentages', domain:'m-psda', tier:2, variant:3, type:'input',
    q:'After a 25% boost, the array generates 250 kW. Enter the output in kW <strong>before</strong> the boost.',
    ans:200, ph:'kW = ?',
    good:'250 is 125% of the original: 250 / 1.25 = 200.',
    bad:'original · 1.25 = 250, so original = 250/1.25 = 200 kW.' },

  // ---------- psda-center-spread ----------
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:0, variant:2, type:'input',
    q:'Six humidity readings came in: <strong>11, 9, 14, 10, 8, 20</strong>. Enter the mean.',
    ans:12, ph:'mean = ?',
    good:'Sum 72 divided by 6 readings = 12.',
    bad:'Add them (11+9+14+10+8+20 = 72) and divide by 6: mean = 12.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:0, variant:3, type:'input',
    q:'Signal strengths for five relays: <strong>14, 6, 10, 2, 18</strong>. Enter the median.',
    ans:10, ph:'median = ?',
    good:'Sorted: 2, 6, 10, 14, 18. Middle value: 10.',
    bad:'Sort first: 2, 6, 10, 14, 18. The middle (third) value is 10.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:1, variant:2, type:'input',
    q:'The mean of six coolant-flow readings is 25. Five of them are <strong>20, 22, 28, 30, 24</strong>. Enter the sixth reading.',
    ans:26, ph:'sixth = ?',
    good:'Total must be 6 · 25 = 150; the five given sum to 124, so the sixth is 26.',
    bad:'Mean 25 over 6 readings means total 150. 150 − (20+22+28+30+24) = 150 − 124 = 26.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:1, variant:3, type:'input',
    q:'Reactor pressures this cycle: <strong>58, 31, 47, 62, 24</strong>. Enter the range.',
    ans:38, ph:'range = ?',
    good:'Max 62 minus min 24 = 38.',
    bad:'Range = maximum − minimum = 62 − 24 = 38.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:2, variant:2, type:'input',
    q:'Eight voltage readings have a mean of 15. Two faulty readings of 40 and 30 are discarded. Enter the mean of the remaining six readings.',
    ans:8, ph:'new mean = ?',
    good:'Old total 120; removing 40 and 30 leaves 50 across 6 readings: mean 8.',
    bad:'8 · 15 = 120 total. Remove 40 + 30 = 70: 50 left, over 6 readings = 8.' },
  { skill:'psda-center-spread', name:'Mean, median, mode & range', domain:'m-psda', tier:2, variant:3, type:'mc',
    q:'A technician adds a constant 5 to every value in a dataset of sensor readings. Which statistic stays <strong>unchanged</strong>?',
    opts:['The mean','The median','The range','All of them increase by 5'], ans:2,
    good:'Shifting every value by the same amount moves center measures but leaves the spread (range) fixed.',
    bad:'Adding a constant shifts mean and median up by 5, but max − min is unchanged, so the range stays the same.' },

  // ---------- psda-tables ----------
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:0, variant:2, type:'input',
    q:'Bay inventory:<br>Sector 1 — 14 probes, 9 beacons<br>Sector 2 — 11 probes, 6 beacons<br>Enter the total number of <strong>probes</strong> in the bay.',
    ans:25, ph:'probes = ?',
    good:'14 + 11 = 25 probes overall.',
    bad:'Add the probe column: 14 (Sector 1) + 11 (Sector 2) = 25.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:0, variant:3, type:'input',
    q:'Bay inventory:<br>Sector 1 — 14 probes, 9 beacons<br>Sector 2 — 11 probes, 6 beacons<br>Enter the total item count in <strong>Sector 1</strong>.',
    ans:23, ph:'items = ?',
    good:'14 + 9 = 23 in Sector 1.',
    bad:'Sum the Sector 1 row: 14 probes + 9 beacons = 23.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:1, variant:2, type:'input',
    q:'Bay inventory:<br>Sector 1 — 14 probes, 9 beacons<br>Sector 2 — 11 probes, 6 beacons<br>How many <strong>more probes than beacons</strong> are in the bay overall?',
    ans:10, ph:'difference = ?',
    good:'Probes 25, beacons 15; difference 10.',
    bad:'Probes: 14 + 11 = 25. Beacons: 9 + 6 = 15. Difference: 25 − 15 = 10.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:1, variant:3, type:'mc',
    q:'Bay inventory:<br>Sector 2 — 11 probes, 6 beacons, 3 relays (20 items total)<br>What fraction of the <strong>Sector 2</strong> items are beacons?',
    opts:['6/11','3/10','6/17','6/20'], ans:1,
    good:'6 of 20 Sector 2 items: 6/20 = 3/10.',
    bad:'Sector 2 total is 20 items; beacons are 6/20 = 3/10.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:2, variant:2, type:'mc',
    q:'Repair log:<br>Bay X — 18 units, 6 needing service<br>Bay Y — 12 units, 9 needing service<br>A unit needing service is chosen at random. What is the probability it is in <strong>Bay Y</strong>?',
    opts:['9/12','3/5','9/30','1/2'], ans:1,
    good:'Units needing service: 6 + 9 = 15. In Bay Y: 9/15 = 3/5.',
    bad:'Condition on needing service: 15 total, 9 in Bay Y, so 9/15 = 3/5.' },
  { skill:'psda-tables', name:'Data from tables', domain:'m-psda', tier:2, variant:3, type:'input',
    q:'Assay log of 80 specimens:<br>Type-A — 15 reactive, 25 inert<br>Type-B — 21 reactive, 19 inert<br>What <strong>percent</strong> of the reactive specimens are Type-B?',
    ans:58, ph:'percent = ?',
    good:'Reactive total 36; Type-B reactive 21; 21/36 ≈ 58%.',
    bad:'Restrict to reactive: 15 + 21 = 36. Type-B share: 21/36 ≈ 0.583 = 58%.' },

  // ---------- psda-scatter ----------
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:0, variant:2, type:'input',
    q:'A scatterplot of altitude vs. temperature has a line of best fit <strong>y = 3x + 6</strong>. Enter the predicted y when x = 5.',
    ans:21, ph:'y = ?',
    good:'3 · 5 + 6 = 21.',
    bad:'Substitute x = 5: 3(5) + 6 = 15 + 6 = 21.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:0, variant:3, type:'mc',
    q:'A scatterplot of shield age vs. energy efficiency has a best-fit line with <strong>negative slope</strong>. Which is the best description?',
    opts:['As shield age increases, efficiency tends to increase','As shield age increases, efficiency tends to decrease','Shield age and efficiency are unrelated','Efficiency causes shields to age faster'], ans:1,
    good:'Negative slope means the two variables move in opposite directions (a negative association).',
    bad:'A negative slope means larger x values pair with smaller y values on average.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:1, variant:2, type:'input',
    q:'The best-fit line for pressure vs. yield is <strong>y = 4x + 7</strong>. For what x does the line predict y = 43?',
    ans:9, ph:'x = ?',
    good:'43 = 4x + 7, so 4x = 36 and x = 9.',
    bad:'Solve 4x + 7 = 43: 4x = 36, so x = 9.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:1, variant:3, type:'input',
    q:'The best-fit line is <strong>y = 3x + 5</strong>. At x = 8, the actual sensor reading was 35. Enter the residual (actual minus predicted).',
    ans:6, ph:'residual = ?',
    good:'Predicted 3(8) + 5 = 29; residual 35 − 29 = 6.',
    bad:'Prediction: 3·8 + 5 = 29. Residual = actual − predicted = 35 − 29 = 6.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:2, variant:2, type:'input',
    q:'Battery voltage vs. discharge time fits <strong>y = −5x + 100</strong>. Enter the predicted voltage y when x = 12.',
    ans:40, ph:'y = ?',
    good:'−5 · 12 + 100 = −60 + 100 = 40.',
    bad:'Substitute: y = −5(12) + 100 = 40.' },
  { skill:'psda-scatter', name:'Scatterplots & line of best fit', domain:'m-psda', tier:2, variant:3, type:'mc',
    q:'Cabin pressure (kPa) vs. altitude (km) fits <strong>y = −6x + 101</strong>. What does the intercept 101 mean in context?',
    opts:['The pressure drops 6 kPa per km','At 0 km altitude the predicted pressure is 101 kPa','The pressure is 101 kPa at every altitude','At 101 km the pressure is 0 kPa'], ans:1,
    good:'The y-intercept is the predicted y when x = 0: about 101 kPa at sea level (0 km).',
    bad:'The intercept gives the predicted value of y at x = 0, i.e. 101 kPa at 0 km altitude.' },

  // ---------- psda-probability ----------
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:0, variant:2, type:'input',
    q:'A tool drawer holds 40 fasteners; 6 are titanium. If one is grabbed at random, what is the probability it is titanium, as a <strong>percent</strong>?',
    ans:15, ph:'percent = ?',
    good:'6/40 = 0.15 = 15%.',
    bad:'Favorable over total: 6/40 = 15%.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:0, variant:3, type:'mc',
    q:'A cargo bin has 4 amber pods and 6 violet pods. What is the probability of drawing a violet pod at random?',
    opts:['4/10','6/10','4/6','1/6'], ans:1,
    good:'6 violet out of 10 total pods: 6/10.',
    bad:'Total pods = 4 + 6 = 10, so P(violet) = 6/10.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:1, variant:2, type:'mc',
    q:'Inspection finds 7 cracked tiles in a batch of 28. If one tile is checked at random, what is the probability it is <strong>not</strong> cracked?',
    opts:['7/28','1/4','21/28','27/28'], ans:2,
    good:'28 − 7 = 21 intact tiles: 21/28.',
    bad:'P(not cracked) = 1 − 7/28 = 21/28.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:1, variant:3, type:'input',
    q:'Each atmospheric scan has a 2/9 chance of detecting a trace gas. In 45 scans, how many detections are <strong>expected</strong>?',
    ans:10, ph:'expected = ?',
    good:'(2/9) · 45 = 10.',
    bad:'Multiply probability by trials: (2/9)(45) = 10.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:2, variant:2, type:'mc',
    q:'Of 60 fault reports, 36 came from Module P (9 of them severe) and 24 from Module Q (15 of them severe). Given that a report is <strong>severe</strong>, what is the probability it came from Module Q?',
    opts:['15/24','5/8','15/60','2/5'], ans:1,
    good:'Severe reports: 9 + 15 = 24. From Q: 15/24 = 5/8.',
    bad:'Condition on severe: 24 severe total, 15 from Module Q, so 15/24 = 5/8.' },
  { skill:'psda-probability', name:'Probability', domain:'m-psda', tier:2, variant:3, type:'input',
    q:'The main thruster misfires with probability 0.3 and the independent auxiliary thruster misfires with probability 0.2. What is the probability <strong>both</strong> misfire, as a percent?',
    ans:6, ph:'percent = ?',
    good:'Independent events multiply: 0.3 · 0.2 = 0.06 = 6%.',
    bad:'For independent events, multiply: 0.3 × 0.2 = 0.06, which is 6%.' },

  // ---------- psda-statistics ----------
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:0, variant:2, type:'mc',
    q:'A research team wants their estimate of average reactor uptime to be more precise. Which change most reliably <strong>decreases</strong> the margin of error?',
    opts:['Collecting more random measurements','Discarding low readings','Rounding to whole hours','Measuring only on weekends'], ans:0,
    good:'A larger random sample tightens the estimate: smaller margin of error.',
    bad:'Margin of error shrinks as the random sample size grows.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:0, variant:3, type:'mc',
    q:'A poll of crew satisfaction is conducted only among volunteers who chose to respond. What is the main concern with this method?',
    opts:['The sample is too random','Volunteers may differ systematically, biasing the results','It removes the margin of error','It makes the confidence interval too wide'], ans:1,
    good:'Self-selected volunteers can differ from the crew as a whole, creating response bias.',
    bad:'Voluntary-response samples over-represent those with strong opinions, so results may not generalize.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:1, variant:2, type:'mc',
    q:'A random sample of oxygen cells has a mean life of 500 hours with a margin of error of 20 hours. Which is a plausible value for the true mean life of all cells?',
    opts:['515 hours','475 hours','525 hours','460 hours'], ans:0,
    good:'The plausible interval is 480 to 520 hours; 515 fits.',
    bad:'500 ± 20 gives the interval 480–520. Only 515 falls inside it.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:1, variant:3, type:'mc',
    q:'To estimate average daily water use across all 300 crew, an analyst surveys only crew in the <strong>medical wing</strong>. What is the main problem?',
    opts:['The sample is too random','Medical staff cannot report water use','The margin of error drops to zero','The sample is not representative, so results may be biased'], ans:3,
    good:'Medical-wing water use likely differs from the crew overall — a biased, non-random sample.',
    bad:'Surveying only one wing is a convenience sample; it cannot generalize to all 300 crew.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:2, variant:2, type:'mc',
    q:'Two thrusters were tested on random samples. Thruster M had a mean efficiency of 70% (margin of error 4%); Thruster N had 79% (margin of error 4%). What is the best conclusion?',
    opts:['The intervals do not overlap, so the data support N being more efficient','The intervals overlap, so no conclusion is possible','Both thrusters are exactly 74.5% efficient','Thruster M is more efficient'], ans:0,
    good:'66–74 and 75–83 do not overlap, so the data support a real difference favoring N.',
    bad:'M spans 66–74 and N spans 75–83; non-overlapping intervals support N being more efficient.' },
  { skill:'psda-statistics', name:'Sample statistics & margin of error', domain:'m-psda', tier:2, variant:3, type:'mc',
    q:'A randomized controlled experiment assigns crew to a new light-therapy schedule or the old one and finds the new group reports better mood. What conclusion is justified?',
    opts:['Only an association exists, never causation','Because assignment was randomized, the data support that the therapy caused better mood','Mood caused crew to be assigned to therapy','The experiment proves nothing'], ans:1,
    good:'Random assignment controls confounders, so a randomized experiment can support a causal claim.',
    bad:'Unlike observational studies, a randomized controlled experiment can justify a cause-and-effect conclusion.' }
);
