// SAT Math: Advanced Math skill bank — Axiom-7
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ---------- adv-equiv-expr ----------
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:0, variant:0, type:'mc',
    q:'The reactor output on Axiom-7 is modeled by <strong>3(x + 4) − 2x</strong>. Which expression is equivalent?',
    opts:['x + 12','x + 4','5x + 12','x − 12'], ans:0,
    good:'Distribute: 3x + 12 − 2x = x + 12. Reactor math checks out.',
    bad:'Distribute first: 3(x + 4) = 3x + 12, then subtract 2x to get x + 12.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:0, variant:1, type:'mc',
    q:'A fuel-mix routine computes <strong>5(2x − 3) + 4</strong>. Which expression is equivalent?',
    opts:['10x + 1','7x − 11','10x − 11','10x − 15'], ans:2,
    good:'10x − 15 + 4 = 10x − 11. The routine simplifies cleanly.',
    bad:'Distribute: 5(2x − 3) = 10x − 15, then add 4 to get 10x − 11.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:1, variant:0, type:'mc',
    q:'A shield calibration uses <strong>(x + 3)(x − 3) + 9</strong>. Which expression is equivalent?',
    opts:['x² + 9','x²','x² − 18','x² + 6x'], ans:1,
    good:'Difference of squares: x² − 9, plus 9 leaves exactly x².',
    bad:'(x + 3)(x − 3) = x² − 9. Adding 9 cancels the constant, leaving x².' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:1, variant:1, type:'mc',
    q:'The gravity ring firmware evaluates <strong>2x(x − 4) + 3(x² − 1)</strong>. Which expression is equivalent?',
    opts:['5x² − 8x + 3','2x² − 8x − 3','5x² + 8x − 3','5x² − 8x − 3'], ans:3,
    good:'2x² − 8x + 3x² − 3 = 5x² − 8x − 3. Firmware verified.',
    bad:'Expand both parts: 2x² − 8x and 3x² − 3, then combine: 5x² − 8x − 3.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:2, variant:0, type:'mc',
    q:'For x ≠ −3, a sensor ratio is <strong>(x² − 9)/(x + 3)</strong>. Which expression is equivalent?',
    opts:['x − 3','x + 3','x − 9','x² − 3'], ans:0,
    good:'Factor the numerator: (x + 3)(x − 3), cancel (x + 3) to get x − 3.',
    bad:'x² − 9 = (x + 3)(x − 3). Cancel the common factor (x + 3), leaving x − 3.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:2, variant:1, type:'mc',
    q:'For 2x + 3 ≠ 0, the coolant flow ratio is <strong>(6x² + 7x − 3)/(2x + 3)</strong>. Which expression is equivalent?',
    opts:['3x + 1','2x − 1','3x − 1','6x − 1'], ans:2,
    good:'6x² + 7x − 3 = (2x + 3)(3x − 1), so the ratio is 3x − 1.',
    bad:'Factor: (2x + 3)(3x − 1) = 6x² + 7x − 3. Cancel (2x + 3) to get 3x − 1.' },

  // ---------- adv-polynomials ----------
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:0, variant:0, type:'mc',
    q:'Two thruster outputs sum to <strong>(3x² + 2x) + (x² − 5x)</strong>. Which expression is the total?',
    opts:['4x² + 7x','4x² − 3x','3x² − 3x','4x² − 5x'], ans:1,
    good:'Combine like terms: 4x² and −3x. Total thrust locked in.',
    bad:'Add the x² terms (3 + 1 = 4) and the x terms (2 − 5 = −3): 4x² − 3x.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:0, variant:1, type:'mc',
    q:'The lab computes <strong>(5x² − 4x + 2) − (2x² + x − 3)</strong>. Which expression is the result?',
    opts:['3x² − 3x − 1','3x² − 5x − 1','3x² − 5x + 5','7x² − 3x + 5'], ans:2,
    good:'Distribute the minus sign: 5x² − 2x² = 3x², −4x − x = −5x, 2 + 3 = 5.',
    bad:'Subtracting flips every sign of the second polynomial: 3x² − 5x + 5.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:1, variant:0, type:'mc',
    q:'A cargo bay area expands as <strong>(x + 5)(x − 2)</strong>. Which expression is equivalent?',
    opts:['x² + 3x − 10','x² − 3x − 10','x² + 3x + 10','x² − 10'], ans:0,
    good:'FOIL: x² − 2x + 5x − 10 = x² + 3x − 10.',
    bad:'Multiply out: x·x + x·(−2) + 5·x + 5·(−2) = x² + 3x − 10.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:1, variant:1, type:'input',
    q:'A pressure model is <strong>p(x) = 2x³ − x + 4</strong>. To unlock the airlock, enter <strong>p(2)</strong>.',
    ans:18, ph:'p(2) = ?',
    good:'p(2) = 2(8) − 2 + 4 = 16 − 2 + 4 = 18. Airlock cycles open.',
    bad:'Substitute x = 2: 2(2)³ − 2 + 4 = 16 − 2 + 4 = 18.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:2, variant:0, type:'mc',
    q:'A solar panel side is (2x − 3) meters, so its area is <strong>(2x − 3)²</strong>. Which expression is equivalent?',
    opts:['4x² + 9','4x² − 6x + 9','2x² − 12x + 9','4x² − 12x + 9'], ans:3,
    good:'(2x − 3)² = 4x² − 12x + 9. Middle term is 2·(2x)·(−3).',
    bad:'Square the binomial: (2x)² − 2(2x)(3) + 3² = 4x² − 12x + 9.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:2, variant:1, type:'mc',
    q:'The nav computer multiplies <strong>(x² + 2x − 1)(x − 3)</strong>. Which expression is the product?',
    opts:['x³ − x² + 7x + 3','x³ − x² − 7x + 3','x³ + x² − 7x − 3','x³ − 5x² − 7x + 3'], ans:1,
    good:'x³ + 2x² − x − 3x² − 6x + 3 = x³ − x² − 7x + 3.',
    bad:'Distribute each term of x − 3 through the trinomial, then combine: x³ − x² − 7x + 3.' },

  // ---------- adv-factoring ----------
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:0, variant:0, type:'mc',
    q:'The lab needs to factor <strong>x² + 7x + 12</strong> to split a bacterial culture grid. Which is the factored form?',
    opts:['(x + 3)(x + 4)','(x + 2)(x + 6)','(x + 1)(x + 12)','(x − 3)(x − 4)'], ans:0,
    good:'3 + 4 = 7 and 3 × 4 = 12. Grid split confirmed.',
    bad:'Find two numbers that multiply to 12 and add to 7: that is 3 and 4.' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:0, variant:1, type:'mc',
    q:'A hull stress term is <strong>x² − 9</strong>. Which is the factored form?',
    opts:['(x − 3)²','(x + 9)(x − 1)','(x + 3)(x − 3)','(x − 9)(x + 1)'], ans:2,
    good:'Difference of squares: x² − 9 = (x + 3)(x − 3).',
    bad:'x² − 9 is a difference of squares: (x + 3)(x − 3).' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:1, variant:0, type:'mc',
    q:'Factor the sensor drift polynomial <strong>x² − 2x − 15</strong>.',
    opts:['(x + 5)(x − 3)','(x − 5)(x + 3)','(x − 15)(x + 1)','(x − 5)(x − 3)'], ans:1,
    good:'−5 + 3 = −2 and −5 × 3 = −15. Drift decomposed.',
    bad:'You need a pair multiplying to −15 and summing to −2: −5 and 3.' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:1, variant:1, type:'input',
    q:'The polynomial <strong>x² − 10x + 21</strong> factors as (x − 3)(x − k). The maintenance hatch code is <strong>k</strong>.',
    ans:7, ph:'k = ?',
    good:'3 × 7 = 21 and 3 + 7 = 10, so k = 7. Hatch open.',
    bad:'Since 3 · k = 21 and 3 + k = 10, k = 7.' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:2, variant:0, type:'mc',
    q:'Factor the antenna gain polynomial <strong>2x² + 7x + 3</strong>.',
    opts:['(2x + 3)(x + 1)','(2x − 1)(x − 3)','(x + 3)(x + 1)','(2x + 1)(x + 3)'], ans:3,
    good:'(2x + 1)(x + 3) = 2x² + 6x + x + 3 = 2x² + 7x + 3.',
    bad:'Check by expanding: (2x + 1)(x + 3) gives 2x² + 7x + 3.' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:2, variant:1, type:'mc',
    q:'The docking clamp torque is <strong>6x² − x − 12</strong>. Which is the factored form?',
    opts:['(3x + 4)(2x − 3)','(3x − 4)(2x + 3)','(6x + 4)(x − 3)','(3x + 2)(2x − 6)'], ans:0,
    good:'(3x + 4)(2x − 3) = 6x² − 9x + 8x − 12 = 6x² − x − 12.',
    bad:'Expand each option; only (3x + 4)(2x − 3) yields 6x² − x − 12.' },

  // ---------- adv-solve-quad ----------
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:0, variant:0, type:'input',
    q:'A hull panel has area x² = 49 square meters. Enter the positive solution of <strong>x² = 49</strong> to size the replacement panel.',
    ans:7, ph:'x = ?',
    good:'√49 = 7. Panel fabricated at 7 meters.',
    bad:'Take the square root of both sides: x = 7 (the positive root).' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:0, variant:1, type:'input',
    q:'The vault code is the positive solution of <strong>x² − 5x − 24 = 0</strong>.',
    ans:8, ph:'x = ?',
    good:'(x − 8)(x + 3) = 0, so x = 8 or x = −3. Code: 8.',
    bad:'Factor: (x − 8)(x + 3) = 0. The positive solution is 8.' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:1, variant:0, type:'input',
    q:'A drone stabilizes when <strong>x² − 6x + 8 = 0</strong>. Enter the <strong>larger</strong> solution.',
    ans:4, ph:'x = ?',
    good:'(x − 2)(x − 4) = 0; solutions 2 and 4. Larger: 4.',
    bad:'Factor: (x − 2)(x − 4) = 0, giving x = 2 or x = 4. The larger is 4.' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:1, variant:1, type:'input',
    q:'The coolant valve opens at the positive solution of <strong>2x² − 18 = 0</strong>.',
    ans:3, ph:'x = ?',
    good:'2x² = 18, x² = 9, so x = 3. Valve open.',
    bad:'Divide by 2: x² = 9, so the positive solution is x = 3.' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:2, variant:0, type:'input',
    q:'A trajectory satisfies <strong>x² − 12x + 27 = 0</strong>. The uplink key is the <strong>sum</strong> of its two solutions.',
    ans:12, ph:'sum = ?',
    good:'For x² + bx + c, the solutions sum to −b = 12. (They are 3 and 9.)',
    bad:'The solutions are 3 and 9 (or use sum = −b/a = 12). Sum: 12.' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:2, variant:1, type:'input',
    q:'The equation <strong>x² + kx + 9 = 0</strong> has exactly one real solution. Enter the <strong>positive</strong> value of k.',
    ans:6, ph:'k = ?',
    good:'Discriminant zero: k² − 36 = 0, so k = 6.',
    bad:'One solution means the discriminant k² − 4(1)(9) = 0, so k² = 36 and k = 6.' },

  // ---------- adv-quad-graphs ----------
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:0, variant:0, type:'mc',
    q:'A probe arc follows <strong>y = (x − 3)² + 2</strong>. What is the vertex of the graph?',
    opts:['(−3, 2)','(3, 2)','(3, −2)','(2, 3)'], ans:1,
    good:'Vertex form y = (x − h)² + k has vertex (h, k) = (3, 2).',
    bad:'In vertex form y = (x − h)² + k, the vertex is (h, k). Here h = 3, k = 2.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:0, variant:1, type:'mc',
    q:'The antenna signal curve is <strong>y = −2x² + 5x + 1</strong>. Which describes the graph?',
    opts:['It opens downward','It opens upward','It is a straight line','It has no maximum or minimum'], ans:0,
    good:'The x² coefficient is −2 (negative), so the parabola opens downward.',
    bad:'A negative leading coefficient (−2) makes the parabola open downward.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:1, variant:0, type:'input',
    q:'A cargo pod arc is <strong>y = x² − 8x + 7</strong>. Enter the <strong>larger</strong> x-intercept.',
    ans:7, ph:'x = ?',
    good:'y = (x − 1)(x − 7), so intercepts at x = 1 and x = 7. Larger: 7.',
    bad:'Set y = 0 and factor: (x − 1)(x − 7) = 0. The larger x-intercept is 7.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:1, variant:1, type:'input',
    q:'Power draw follows <strong>y = x² − 6x + 5</strong>. Enter the x-coordinate of the vertex (the minimum-draw time).',
    ans:3, ph:'x = ?',
    good:'x = −b/(2a) = 6/2 = 3. Minimum draw at t = 3.',
    bad:'The vertex x-coordinate is −b/(2a) = 6/2 = 3.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:2, variant:0, type:'input',
    q:'Signal strength is <strong>y = −(x − 4)² + 9</strong>. Enter the <strong>maximum</strong> value of y.',
    ans:9, ph:'max y = ?',
    good:'The vertex (4, 9) is the highest point since the parabola opens downward. Max: 9.',
    bad:'Vertex form shows the peak at (4, 9); with a negative lead coefficient the maximum is 9.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:2, variant:1, type:'mc',
    q:'The reactor curve is <strong>y = x² + 4x + 7</strong>. Which statement is true about its graph?',
    opts:['It has two x-intercepts and a maximum value','It has one x-intercept at x = −2','It has no x-intercepts and a minimum value of 3','It has no x-intercepts and a minimum value of 7'], ans:2,
    good:'Complete the square: y = (x + 2)² + 3. Minimum 3, never reaches 0.',
    bad:'y = (x + 2)² + 3, so the vertex is (−2, 3): minimum value 3, and since 3 > 0 there are no x-intercepts.' },

  // ---------- adv-exponential ----------
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:0, variant:0, type:'input',
    q:'A bacterial culture in the Axiom-7 lab starts with 5 colonies and <strong>doubles every hour</strong>. How many colonies after 3 hours?',
    ans:40, ph:'colonies = ?',
    good:'5 → 10 → 20 → 40. That is 5 · 2³ = 40.',
    bad:'Doubling three times: 5 · 2³ = 5 · 8 = 40.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:0, variant:1, type:'mc',
    q:'Which function models a battery that <strong>loses 15% of its charge</strong> each cycle, starting at 100 units?',
    opts:['y = 100(1.15)^t','y = 100 − 15t','y = 100(0.15)^t','y = 100(0.85)^t'], ans:3,
    good:'Keeping 85% each cycle means multiplying by 0.85 repeatedly.',
    bad:'Losing 15% leaves 85%, so the decay factor is 0.85: y = 100(0.85)^t.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:1, variant:0, type:'input',
    q:'Spore count follows <strong>P = 200(3)^t</strong> where t is days. Enter P when t = 2.',
    ans:1800, ph:'P = ?',
    good:'200 · 9 = 1800 spores. Quarantine the sample!',
    bad:'3² = 9, and 200 · 9 = 1800.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:1, variant:1, type:'input',
    q:'An isotope in the reactor <strong>halves every 6 hours</strong>. Starting at 320 grams, how many grams remain after 18 hours?',
    ans:40, ph:'grams = ?',
    good:'18 hours = 3 half-lives: 320 → 160 → 80 → 40.',
    bad:'18 / 6 = 3 half-lives, so 320 · (1/2)³ = 40 grams.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:2, variant:0, type:'input',
    q:'A microbe colony grows <strong>20% per day</strong>, compounding daily, from 500 cells. Enter the cell count after 2 days.',
    ans:720, ph:'cells = ?',
    good:'500 · 1.2² = 500 · 1.44 = 720. Compound growth, not 500 + 40%.',
    bad:'Apply the factor twice: 500 · 1.2 = 600, then 600 · 1.2 = 720.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:2, variant:1, type:'mc',
    q:'A culture of 150 cells <strong>doubles every 8 hours</strong>. Which expression gives the count after t hours?',
    opts:['150 · 2^(8t)','150 · 2^(t/8)','150 · 8^(t/2)','150 + 2^(t/8)'], ans:1,
    good:'t/8 counts the number of doubling periods, so 150 · 2^(t/8).',
    bad:'After t hours there have been t/8 doublings: 150 · 2^(t/8). Check t = 8 gives 300.' },

  // ---------- adv-radicals ----------
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:0, variant:0, type:'input',
    q:'The airlock code is <strong>√64 + √36</strong>.',
    ans:14, ph:'code = ?',
    good:'8 + 6 = 14. Airlock sealed.',
    bad:'√64 = 8 and √36 = 6, so the code is 14.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:0, variant:1, type:'mc',
    q:'For x > 0, which is equivalent to <strong>x^(1/2)</strong>?',
    opts:['√x','x/2','1/x²','2x'], ans:0,
    good:'A 1/2 exponent is exactly a square root.',
    bad:'A rational exponent of 1/2 means the square root: x^(1/2) = √x.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:1, variant:0, type:'input',
    q:'A sensor gain is <strong>∛27 · √25</strong>. Enter the gain.',
    ans:15, ph:'gain = ?',
    good:'3 · 5 = 15. Sensor calibrated.',
    bad:'∛27 = 3 and √25 = 5, so the product is 15.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:1, variant:1, type:'mc',
    q:'Which is equivalent to <strong>√50</strong>?',
    opts:['25√2','2√5','5√2','10√5'], ans:2,
    good:'√50 = √25 · √2 = 5√2.',
    bad:'Pull out the largest perfect square: 50 = 25 · 2, so √50 = 5√2.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:2, variant:0, type:'input',
    q:'The encryption key is <strong>16^(3/4)</strong>.',
    ans:8, ph:'key = ?',
    good:'Fourth root of 16 is 2; 2³ = 8. Key accepted.',
    bad:'16^(3/4) = (16^(1/4))³ = 2³ = 8.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:2, variant:1, type:'mc',
    q:'For x > 0, which is equivalent to <strong>√(x⁶)</strong>?',
    opts:['x⁴','x^(1/6)','x²','x³'], ans:3,
    good:'√(x⁶) = x^(6/2) = x³.',
    bad:'Halve the exponent under a square root: x^(6/2) = x³.' },

  // ---------- adv-rational-eq ----------
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:0, variant:0, type:'input',
    q:'A ration split satisfies <strong>12/x = 3</strong>. Solve for x, the number of crew.',
    ans:4, ph:'x = ?',
    good:'12 = 3x, so x = 4 crew members.',
    bad:'Multiply both sides by x: 12 = 3x, so x = 4.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:0, variant:1, type:'input',
    q:'A telemetry check requires <strong>√x = 5</strong>. Solve for x.',
    ans:25, ph:'x = ?',
    good:'Square both sides: x = 25.',
    bad:'Square both sides of √x = 5 to get x = 25.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:1, variant:0, type:'input',
    q:'Coolant flow satisfies <strong>6/(x − 2) = 2</strong>. Solve for x.',
    ans:5, ph:'x = ?',
    good:'6 = 2(x − 2), so x − 2 = 3 and x = 5.',
    bad:'Multiply both sides by (x − 2): 6 = 2x − 4, so x = 5.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:1, variant:1, type:'input',
    q:'The docking beacon fires when <strong>√(2x + 7) = 5</strong>. Solve for x.',
    ans:9, ph:'x = ?',
    good:'2x + 7 = 25, so 2x = 18 and x = 9.',
    bad:'Square both sides: 2x + 7 = 25, giving x = 9.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:2, variant:0, type:'input',
    q:'The oxygen mix satisfies <strong>x/(x − 3) = 4</strong>. Solve for x.',
    ans:4, ph:'x = ?',
    good:'x = 4x − 12, so 3x = 12 and x = 4 (and 4 ≠ 3, so it is valid).',
    bad:'Cross-multiply: x = 4(x − 3) = 4x − 12, so 3x = 12 and x = 4.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:2, variant:1, type:'input',
    q:'The vault opens when <strong>√(x + 11) = x − 1</strong>. Enter the valid solution. (Watch for the extraneous one!)',
    ans:5, ph:'x = ?',
    good:'Squaring gives x² − 3x − 10 = 0, so x = 5 or x = −2. Only x = 5 checks: √16 = 4 = 5 − 1.',
    bad:'Square both sides: x + 11 = x² − 2x + 1, so x² − 3x − 10 = 0 and x = 5 or −2. x = −2 fails the original equation, so x = 5.' },

  // ---------- adv-absolute ----------
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:0, variant:0, type:'input',
    q:'Temperature drift satisfies <strong>|x − 4| = 6</strong>. Enter the <strong>larger</strong> solution.',
    ans:10, ph:'x = ?',
    good:'x − 4 = ±6, so x = 10 or x = −2. Larger: 10.',
    bad:'Split into x − 4 = 6 and x − 4 = −6: x = 10 or x = −2. The larger is 10.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:0, variant:1, type:'input',
    q:'A sensor reads <strong>|x| + 3 = 8</strong>. Enter the positive solution.',
    ans:5, ph:'x = ?',
    good:'|x| = 5, so the positive solution is 5.',
    bad:'Subtract 3: |x| = 5, so x = 5 or −5. Positive: 5.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:1, variant:0, type:'input',
    q:'Gyro error satisfies <strong>|2x − 6| = 10</strong>. Enter the <strong>larger</strong> solution.',
    ans:8, ph:'x = ?',
    good:'2x − 6 = ±10, so x = 8 or x = −2. Larger: 8.',
    bad:'Two cases: 2x − 6 = 10 gives x = 8; 2x − 6 = −10 gives x = −2. Larger: 8.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:1, variant:1, type:'mc',
    q:'Safe cabin pressure satisfies <strong>|x − 5| &lt; 3</strong>. Which describes all solutions?',
    opts:['x < 2 or x > 8','2 < x < 8','x < 8','−3 < x < 3'], ans:1,
    good:'Within 3 of 5 means between 2 and 8.',
    bad:'|x − 5| < 3 means −3 < x − 5 < 3, so 2 < x < 8.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:2, variant:0, type:'input',
    q:'Two beacons match when <strong>|3x + 2| = |x + 10|</strong>. Enter the <strong>positive</strong> solution.',
    ans:4, ph:'x = ?',
    good:'3x + 2 = x + 10 gives x = 4; 3x + 2 = −(x + 10) gives x = −3. Positive: 4.',
    bad:'Set the insides equal or opposite: x = 4 or x = −3. The positive solution is 4.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:2, variant:1, type:'mc',
    q:'The radiation alarm triggers when <strong>|x − 7| ≥ 2</strong>. Which describes the alarm zone?',
    opts:['5 ≤ x ≤ 9','x ≥ 9 only','x ≤ 5 or x ≥ 9','x ≤ 5 only'], ans:2,
    good:'At least 2 away from 7 means x ≤ 5 or x ≥ 9.',
    bad:'|x − 7| ≥ 2 splits into x − 7 ≥ 2 or x − 7 ≤ −2: x ≥ 9 or x ≤ 5.' },

  // ---------- adv-functions ----------
  { skill:'adv-functions', name:'Function notation & composition', domain:'m-adv', tier:0, variant:0, type:'input',
    q:'The shield function is <strong>f(x) = x² + 1</strong>. Enter f(3) to set shield strength.',
    ans:10, ph:'f(3) = ?',
    good:'f(3) = 9 + 1 = 10. Shields at full.',
    bad:'Substitute x = 3: 3² + 1 = 10.' },
  { skill:'adv-functions', name:'Function notation & composition', domain:'m-adv', tier:0, variant:1, type:'input',
    q:'Given <strong>f(x) = 2x − 3</strong> and <strong>g(x) = x²</strong>, enter <strong>g(f(3))</strong>.',
    ans:9, ph:'g(f(3)) = ?',
    good:'f(3) = 3, then g(3) = 9. Composition complete.',
    bad:'Work inside out: f(3) = 2(3) − 3 = 3, then g(3) = 3² = 9.' },
  { skill:'adv-functions', name:'Function notation & composition', domain:'m-adv', tier:1, variant:0, type:'input',
    q:'Nav routines: <strong>g(x) = x + 5</strong>, <strong>f(x) = x² − 1</strong>. Enter <strong>f(g(2))</strong>.',
    ans:48, ph:'f(g(2)) = ?',
    good:'g(2) = 7, then f(7) = 49 − 1 = 48.',
    bad:'Inside first: g(2) = 7. Then f(7) = 7² − 1 = 48.' },
  { skill:'adv-functions', name:'Function notation & composition', domain:'m-adv', tier:1, variant:1, type:'mc',
    q:'If <strong>f(x) = x²</strong> and <strong>g(x) = x + 3</strong>, which is <strong>f(g(x))</strong>?',
    opts:['(x + 3)²','x² + 3','x² + 9','x² + 3x'], ans:0,
    good:'Plug g into f: f(x + 3) = (x + 3)².',
    bad:'f(g(x)) means substitute g(x) into f: (x + 3)².' },
  { skill:'adv-functions', name:'Nonlinear systems', domain:'m-adv', tier:2, variant:0, type:'input',
    q:'Two flight paths meet where <strong>y = x²</strong> and <strong>y = 2x + 8</strong>. Enter the y-coordinate of the intersection with <strong>positive</strong> x.',
    ans:16, ph:'y = ?',
    good:'x² − 2x − 8 = 0 gives x = 4 or −2. At x = 4, y = 16.',
    bad:'Set x² = 2x + 8: (x − 4)(x + 2) = 0, so x = 4. Then y = 4² = 16.' },
  { skill:'adv-functions', name:'Nonlinear systems', domain:'m-adv', tier:2, variant:1, type:'input',
    q:'The curves <strong>y = x² − 6x + 10</strong> and <strong>y = x + 4</strong> intersect at two points. Enter the <strong>sum</strong> of their x-coordinates.',
    ans:7, ph:'sum = ?',
    good:'x² − 7x + 6 = 0 has roots 1 and 6; sum 7 (also −b/a).',
    bad:'Set equal: x² − 7x + 6 = 0, so (x − 1)(x − 6) = 0. Sum: 1 + 6 = 7.' }
);
