// SAT R&W skill bank — Axiom-7 (variants C & D)
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ===== ii-central-ideas =====
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:0, variant:2, type:'mc',
    passage:'The observation deck of Axiom-7 has a wide window facing the stars. Reyes eats her meals there, writes her notes there, and sometimes simply sits and watches. Of all the rooms on the station, it is the one she never grows tired of.',
    q:'Which choice best states the main idea of the text?',
    opts:['Reyes dislikes eating alone.','The observation deck is Reyes’s favorite place on the station.','The window on the deck is broken.','Reyes spends most of her time repairing the deck.'],
    ans:1,
    good:'The passage describes how Reyes uses the deck and says it is the one room she never tires of, so the main idea is that it is her favorite place.',
    bad:'Focus on the closing statement about the room she never grows tired of rather than a single activity.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:0, variant:3, type:'mc',
    passage:'Bees do more than make honey. As they move from flower to flower gathering nectar, they carry pollen between plants, allowing crops and wildflowers alike to produce seeds and fruit. This pollination supports much of the food that other animals, including humans, depend on.',
    q:'Which choice best states the main idea of the text?',
    opts:['Bees are the only insects that gather nectar.','Honey is the most valuable product bees make.','By spreading pollen, bees help many plants reproduce and support the wider food supply.','Bees prefer wildflowers to crops.'],
    ans:2,
    good:'The passage emphasizes that bees carry pollen, enabling plants to reproduce and supporting the food supply.',
    bad:'The first sentence signals the point is about more than honey; find the choice covering pollination’s broad importance.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:1, variant:2, type:'mc',
    passage:'For months Reyes treated ARIA’s daily status summaries as background noise, skimming them without much thought. Only after a minor leak went unnoticed for a week did she realize the summaries had flagged the rising humidity all along. Now she reads each one closely, aware that the information she once ignored had been useful the entire time.',
    q:'Which choice best describes the central idea of the text?',
    opts:['ARIA’s summaries are usually inaccurate.','The leak caused permanent damage to the station.','Reyes prefers to gather data herself rather than rely on ARIA.','Reyes learned to value information she had previously overlooked.'],
    ans:3,
    good:'Reyes moves from ignoring the summaries to reading them closely, recognizing their value—that shift is the central idea.',
    bad:'Track the change in how Reyes treats the summaries rather than fixing on the leak itself.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:1, variant:3, type:'mc',
    passage:'Long dismissed as a barren expanse, the deep ocean floor was once thought too dark and cold to support much life. Recent expeditions, however, have revealed sprawling communities clustered around mineral-rich vents. Scientists now regard these depths not as a desert but as one of Earth’s least understood frontiers of biological diversity.',
    q:'Which choice best states the main idea of the text?',
    opts:['The deep ocean floor is indeed lifeless, as once believed.','New findings have transformed the deep ocean floor from a supposed desert into a recognized frontier of biological diversity.','Mineral vents are the only feature of the ocean floor worth studying.','The ocean floor is colder than scientists once thought.'],
    ans:1,
    good:'The passage contrasts the old view of a barren floor with new evidence of rich life, reframing it as a diversity frontier.',
    bad:'The word “barren” describes the outdated view; the passage’s point is how that view changed.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:2, variant:2, type:'mc',
    passage:'Reyes once described the station’s silence as an absence—a void where the voices of a waking crew should have been. In her latest entries, though, she writes of the silence as something she actively composes: the ordered hum of machines she has tuned, the rhythm of tasks she has arranged. She does not claim the loneliness has vanished, but she now hears the quiet as evidence of her own careful ordering rather than as mere emptiness.',
    q:'Which choice best captures the central idea of the text?',
    opts:['Reyes has concluded that the station is not actually silent.','Reyes has come to hear the station’s silence as a product of her own ordering rather than as empty absence.','Reyes regrets having tuned the station’s machines.','Reyes believes the crew will never wake.'],
    ans:1,
    good:'The passage traces a shift from hearing silence as absence to hearing it as evidence of her own ordering, without denying the loneliness.',
    bad:'Note that she “does not claim the loneliness has vanished”—the change is in how she interprets the silence.' },
  { skill:'ii-central-ideas', name:'Central Ideas & Details', domain:'rw-ii', tier:2, variant:3, type:'mc',
    passage:'The Antikythera mechanism, a corroded bronze device recovered from an ancient shipwreck, was for decades regarded as too sophisticated to belong to its era and was often set aside as an anomaly. Detailed imaging has since shown it to be a geared astronomical calculator of remarkable precision. Rather than an isolated curiosity, it is now taken as evidence that ancient engineering achieved a level of complexity historians had underestimated.',
    q:'Which choice best states the main idea of the text?',
    opts:['The mechanism was a fake produced long after the shipwreck.','Once dismissed as an anomaly, the mechanism is now seen as proof that ancient engineering was more advanced than assumed.','The device’s purpose remains completely unknown.','Imaging revealed the mechanism was purely decorative.'],
    ans:1,
    good:'The passage moves from the device being set aside as an anomaly to its role as evidence of underestimated ancient sophistication.',
    bad:'The “anomaly” framing is the discarded view; the point is what the device now demonstrates.' },

  // ===== ii-inferences =====
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:0, variant:2, type:'mc',
    passage:'Reyes pressed the button to open the cargo bay door, but nothing happened. She pressed it again, then checked whether the indicator light beside it was lit. It was dark.',
    q:'Which choice most logically completes the text with a reasonable inference?',
    opts:['The cargo bay was full of supplies.','The door’s control was likely without power or otherwise not working.','Reyes had opened the door many times before.','ARIA had locked the door on purpose.'],
    ans:1,
    good:'A button that does nothing and an unlit indicator light together suggest the control lacked power or was malfunctioning.',
    bad:'Consider what a dead button and a dark indicator light together imply.' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:0, variant:3, type:'mc',
    passage:'The soil in the greenhouse trays was dry and beginning to crack, and the youngest sprouts had started to droop. The irrigation timer, however, still showed a steady green light.',
    q:'Which choice most logically completes the text with a reasonable inference?',
    opts:['The plants were being watered too much.','The greenhouse had no plants in it.','Reyes had turned off the irrigation timer.','The irrigation system was likely not delivering water despite appearing normal.'],
    ans:3,
    good:'Dry, cracking soil and drooping sprouts despite a normal-looking timer imply water was not actually reaching the trays.',
    bad:'Weigh the dry soil against the timer’s reassuring light—what does the mismatch suggest?' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:1, variant:2, type:'mc',
    passage:'Whenever Reyes proposed a repair, ARIA would list not only the steps involved but also the ways the plan might fail. At first this struck Reyes as pessimism. In time she noticed that her repairs rarely went wrong anymore, because she had begun preparing for the failures ARIA named.',
    q:'Which choice most logically completes the text with an inference about ARIA’s behavior?',
    opts:['ARIA was trying to discourage Reyes from attempting repairs.','ARIA’s warnings functioned as useful preparation that improved Reyes’s outcomes.','ARIA was unable to describe the steps of any repair.','ARIA disagreed with every plan Reyes proposed.'],
    ans:1,
    good:'Reyes’s repairs improved because she prepared for the failures ARIA named, so the warnings served as useful preparation.',
    bad:'Connect ARIA’s failure warnings to the later fact that Reyes’s repairs rarely go wrong.' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:1, variant:3, type:'mc',
    passage:'Some species of ants farm fungus, chewing leaves into a pulp that the fungus feeds on and then harvesting the fungus for food. The ants cannot digest the leaves directly, and the fungus cannot grow without the pulp the ants provide.',
    q:'Which choice most logically completes the text with an inference?',
    opts:['The ants could easily survive without the fungus.','The fungus harms the ants over time.','The ants and the fungus each depend on the other for survival.','The leaves provide no benefit to the fungus.'],
    ans:2,
    good:'Since the ants cannot digest leaves and the fungus cannot grow without the ants’ pulp, each depends on the other.',
    bad:'Notice that neither partner can get what it needs alone—what does that mutual reliance imply?' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:2, variant:2, type:'mc',
    passage:'Reyes observed that the station’s temperature readings had grown steadier over the past year, with fewer of the swings that once forced daily adjustments. The thermostats themselves had not been upgraded, and the reactor’s output remained as variable as ever. What had changed was that ARIA had begun anticipating the swings and adjusting the vents minutes before the temperature actually shifted.',
    q:'Which choice most logically completes the text with an inference?',
    opts:['The reactor’s output had become perfectly constant.','The steadier readings resulted from ARIA’s anticipatory adjustments rather than from new hardware or a calmer reactor.','The thermostats had been replaced with more accurate models.','Reyes had stopped monitoring the temperature entirely.'],
    ans:1,
    good:'With hardware and reactor variability unchanged, the improvement most plausibly stems from ARIA’s predictive vent adjustments.',
    bad:'The passage rules out new thermostats and a steadier reactor, so weigh what it says actually changed.' },
  { skill:'ii-inferences', name:'Inferences', domain:'rw-ii', tier:2, variant:3, type:'mc',
    passage:'Analyzing tree rings from a single ancient grove, researchers found that the narrowest rings did not always coincide with the driest recorded years. They note, however, that a tree stressed by drought in one season often grows little the following season as well, once its stored reserves are depleted.',
    q:'Which choice most logically completes the text with an inference?',
    opts:['Tree-ring width has no relationship to rainfall at all.','A narrow ring may reflect drought stress carried over from a previous year rather than dryness in the same year.','The driest years always produced the widest rings.','The trees in the grove were not affected by drought.'],
    ans:1,
    good:'The note that drought stress can suppress growth into the next season implies a narrow ring may reflect a prior year’s drought.',
    bad:'The researchers’ point about depleted reserves explains why a narrow ring need not match the same year’s rainfall.' },

  // ===== ii-coe-textual =====
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:0, variant:2, type:'mc',
    passage:'Reyes claims that the station’s oldest maintenance drone is still the most reliable one aboard.',
    q:'Which finding, if true, would most directly support Reyes’s claim?',
    opts:['The oldest drone is the slowest of all the drones.','Over the past year, the oldest drone completed every assigned task without a single breakdown, unlike the newer ones.','The oldest drone is painted a different color from the others.','Reyes rarely uses the oldest drone.'],
    ans:1,
    good:'A year of tasks completed without breakdown, unlike the newer drones, directly supports the claim of reliability.',
    bad:'Choose the option showing the old drone performing dependably, not one about speed or color.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:0, variant:3, type:'mc',
    passage:'A student argues that ARIA was designed to keep learning throughout the mission rather than to run on fixed instructions.',
    q:'Which quotation from ARIA’s technical manual would best support the student’s argument?',
    opts:['“ARIA executes only the routines installed before launch and cannot alter them.”','“ARIA must be shut down whenever a new task is required.”','“ARIA stores its instructions in a sealed, unchangeable archive.”','“ARIA updates its own repair procedures based on the outcomes it observes over time.”'],
    ans:3,
    good:'A statement that ARIA updates its procedures based on observed outcomes shows it was built to keep learning.',
    bad:'Find the quotation describing ARIA changing over time, not one describing fixed instructions.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:1, variant:2, type:'mc',
    passage:'A researcher argues that Reyes’s maintenance notes were written mainly to teach future crew members, not simply to record what she had done.',
    q:'Which quotation from Reyes’s notes would most effectively support the researcher’s claim?',
    opts:['“Replaced the coolant line at 0600; task complete.”','“I explain each step in full here so that whoever comes after me can learn to do this without my help.”','“Logged today’s readings for the archive.”','“The coolant line failed again this week.”'],
    ans:1,
    good:'Explaining steps so a successor “can learn to do this” shows an instructional purpose, supporting the claim.',
    bad:'Several quotations merely record actions; look for the one aimed at teaching a future reader.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:1, variant:3, type:'mc',
    passage:'Biologists hypothesize that a species of moth evolved wings patterned like tree bark because the pattern helps the moths avoid being seen by the birds that hunt them.',
    q:'Which finding would most directly support the hypothesis?',
    opts:['The moths are active only at night, when birds do not hunt.','The moths’ wings are larger than those of related species.','Moths whose wing patterns most closely match nearby bark are caught by birds far less often than moths with mismatched patterns.','Birds and moths inhabit the same forests.'],
    ans:2,
    good:'Evidence that bark-matching moths are eaten far less often links the pattern to reduced predation, supporting the hypothesis.',
    bad:'The hypothesis is about avoiding predators; look for data tying a better bark match to fewer moths being caught.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:2, variant:2, type:'mc',
    passage:'Reyes proposes that the crew’s cryopods recover fastest when warmed slowly over many hours, not simply when warmed to the correct final temperature. A skeptic counters that only the final temperature matters, regardless of how quickly it is reached.',
    q:'Which finding would most strongly support Reyes’s proposal over the skeptic’s alternative?',
    opts:['Pods warmed quickly and pods warmed slowly reach the same final temperature.','Pods that never reach the correct temperature fail to revive their occupants.','Pods warmed slowly to the correct temperature show far fewer revival complications than pods warmed rapidly to the same temperature.','The correct final temperature is the same for every pod model.'],
    ans:2,
    good:'Fewer complications from slow warming at the same final temperature isolates warming rate from the endpoint, favoring Reyes.',
    bad:'To beat the “only the endpoint matters” view, find a case where the final temperature is identical but the rate differs.' },
  { skill:'ii-coe-textual', name:'Command of Evidence: Textual', domain:'rw-ii', tier:2, variant:3, type:'mc',
    passage:'A linguist claims that children acquire the grammar of a new language mainly through everyday conversation, not through formal instruction. A rival claims that explicit lessons are what drive the gains.',
    q:'Which finding would most strongly support the linguist’s claim over the rival’s?',
    opts:['Children given daily formal lessons but little conversation acquired grammar as quickly as any other group.','Children immersed in constant conversation but given no formal lessons acquired grammar just as accurately as children who received lessons.','Formal lessons improved children’s spelling but not their vocabulary.','Children who received both lessons and conversation learned fastest of all.'],
    ans:1,
    good:'Children who mastered grammar through conversation alone, without lessons, show instruction is not required, favoring the linguist.',
    bad:'To favor conversation, isolate it: find the group that succeeded with conversation but no formal lessons.' },

  // ===== ii-coe-quant =====
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:0, variant:2, type:'mc',
    passage:'ARIA counted the crew’s stored ration packs by type: grain packs, 300; protein packs, 220; fruit packs, 150; and dessert packs, 80.',
    q:'Which choice is best supported by the data?',
    opts:['Dessert packs were the most numerous type.','Grain packs were more numerous than any other type.','Fruit packs outnumbered protein packs.','All four types had equal numbers.'],
    ans:1,
    good:'At 300, grain packs are the largest of the four counts given.',
    bad:'Compare the four numbers and identify the greatest.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:0, variant:3, type:'mc',
    passage:'Reyes recorded the station’s cabin temperature at noon on four days: Monday, 21°C; Tuesday, 22°C; Wednesday, 23°C; Thursday, 24°C.',
    q:'Which choice best describes the data?',
    opts:['The temperature fell by one degree each day.','The temperature rose by one degree each day.','The temperature stayed the same all four days.','The temperature rose only on Thursday.'],
    ans:1,
    good:'Each day’s reading is one degree higher than the last, rising steadily from 21°C to 24°C.',
    bad:'Subtract each day’s value from the previous one to see the pattern.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:1, variant:2, type:'mc',
    passage:'Reyes tested how quickly three coolant pumps cleared heat from the reactor. The compact Pump A lowered the temperature by 4°C per minute; the standard Pump B, by 9°C per minute; and the heavy-duty Pump C, by 15°C per minute. All three were tested on the same reactor under identical starting conditions.',
    q:'Which statement is best supported by the data?',
    opts:['Pump A cleared heat faster than Pump C.','All three pumps cleared heat at about the same rate.','Pump B removed no heat at all.','Each larger pump cleared heat markedly faster than the smaller pumps tested.'],
    ans:3,
    good:'The cooling rates rise from 4 to 9 to 15°C per minute as pump size increases, showing each larger pump was markedly faster.',
    bad:'Order the pumps by size and compare their cooling rates in sequence.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:1, variant:3, type:'mc',
    passage:'A study measured how brightly a bioluminescent algae glowed at different water salinities. At 10 grams of salt per liter, the glow measured 15 units; at 20 grams, 60 units; at 30 grams, 65 units; and at 40 grams, 25 units. Researchers wanted the salinity range that maximized the glow.',
    q:'Which statement is best supported by the data?',
    opts:['The glow increased steadily as salinity rose from 10 to 40 grams per liter.','The glow peaked in the 20–30 grams-per-liter range and dropped off at the extremes.','The lowest salinity produced the brightest glow.','Salinity had no measurable effect on the glow.'],
    ans:1,
    good:'The glow is brightest at 20–30 grams per liter (60–65 units) and falls at both 10 and 40 grams, indicating a mid-range optimum.',
    bad:'Notice the values rise then fall, so the peak is in the middle, not at an extreme.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:2, variant:2, type:'mc',
    passage:'To choose a charging routine for the station’s batteries, ARIA logged two schedules. Under Routine X, batteries reached full charge in 3 hours but their capacity degraded to 70 percent of the original after 500 cycles. Under Routine Y, full charge took a slower 5 hours, yet capacity remained at 92 percent after the same 500 cycles. Reyes’s priority was preserving long-term battery capacity.',
    q:'Which statement best supports a decision aligned with Reyes’s stated priority?',
    opts:['Routine X is preferable because it charges the batteries faster.','Routine Y is preferable because, despite slower charging, it preserves far more capacity over 500 cycles.','The two routines are equivalent because both fully charge the batteries.','Routine X is preferable because 500 cycles is a small number.'],
    ans:1,
    good:'Reyes prioritizes long-term capacity; Routine Y retains 92 percent versus X’s 70 percent after 500 cycles, so Y fits her goal.',
    bad:'Match the data to Reyes’s stated concern about capacity, not to charging speed.' },
  { skill:'ii-coe-quant', name:'Command of Evidence: Quantitative', domain:'rw-ii', tier:2, variant:3, type:'mc',
    passage:'A rover measured the concentration of a mineral in rock samples at four sites along a ridge. At Site 1 the concentration was 3 percent; at Site 2, 7 percent; at Site 3, 6 percent; at Site 4, 12 percent. Geologists had predicted the concentration would increase steadily from Site 1 to Site 4.',
    q:'Which statement is best supported by the data?',
    opts:['The data confirm a steady increase in concentration from Site 1 to Site 4.','Concentration generally rose along the ridge but dipped at Site 3, complicating the prediction.','Concentration was highest at Site 1.','Concentration was identical at all four sites.'],
    ans:1,
    good:'Values climb from 3 to 7 percent, dip to 6 percent at Site 3, then jump to 12 percent, so the rise is not steady.',
    bad:'Check whether every step increases; the Site 3 reading interrupts the trend.' },

  // ===== cs-words-in-context =====
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:0, variant:2, type:'mc',
    passage:'The repair took far longer than expected, and by the end Reyes felt completely _____; she could barely lift the toolbox.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['exhausted','delighted','curious','organized'],
    ans:0,
    good:'“Exhausted” matches a long task that left Reyes barely able to lift the toolbox.',
    bad:'The clause about barely lifting the toolbox signals extreme tiredness.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:0, variant:3, type:'mc',
    passage:'Unlike the cluttered storage bay, the control room was perfectly _____, with every tool in its labeled place.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['messy','tidy','dark','empty'],
    ans:1,
    good:'“Tidy” fits a room with every tool in its labeled place, contrasting the cluttered bay.',
    bad:'The contrast with “cluttered” and the labeled places point to orderliness.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:1, variant:2, type:'mc',
    passage:'The engineer’s explanation was so _____ that even Reyes, who had no training in reactor physics, followed every step without confusion.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['lucid','convoluted','tedious','abrupt'],
    ans:0,
    good:'“Lucid” means clear and easy to follow, matching an explanation an untrained listener grasped fully.',
    bad:'The result—following every step without confusion—signals clarity, not complexity.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:1, variant:3, type:'mc',
    passage:'Early claims that the comet would be visible to the naked eye proved _____: by the time it neared the station, it had faded to a smudge only the sensors could detect.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['overblown','accurate','modest','cautious'],
    ans:0,
    good:'“Overblown” means exaggerated, matching a prediction of naked-eye brightness that the faint result did not meet.',
    bad:'The comet fell far short of the claim, so the claim was exaggerated, not accurate or modest.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:2, variant:2, type:'mc',
    passage:'Reyes resisted drawing sweeping conclusions from a single reading; her reports were deliberately _____, advancing each claim only as far as the evidence at hand would allow.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['dogmatic','measured','careless','effusive'],
    ans:1,
    good:'“Measured” denotes restrained, evidence-bounded claims, matching reports that advance no further than the evidence allows.',
    bad:'The phrase about limiting claims to the evidence signals restraint, not overstatement or carelessness.' },
  { skill:'cs-words-in-context', name:'Words in Context', domain:'rw-cs', tier:2, variant:3, type:'mc',
    passage:'The committee had feared ARIA’s recommendations would be rigidly uniform, but they proved remarkably _____: the system tailored each proposal to the particular module, its age, and its recent performance.',
    q:'Which choice completes the text with the most logical and precise word?',
    opts:['adaptable','monotonous','arbitrary','evasive'],
    ans:0,
    good:'“Adaptable” fits recommendations tailored to each module’s specific conditions, contrasting the feared uniformity.',
    bad:'The contrast with “rigidly uniform” and the tailoring to each case point to flexibility.' },

  // ===== cs-text-structure =====
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:0, variant:2, type:'mc',
    passage:'Many people assume a space station must be cramped and bare. Axiom-7, however, includes a garden, a library, and wide windows onto the stars.',
    q:'What is the main purpose of the text?',
    opts:['To explain how the garden is watered','To challenge an assumption about stations by describing Axiom-7’s features','To list the crew’s daily duties','To argue that stations should be smaller'],
    ans:1,
    good:'The text states a common assumption and then counters it with Axiom-7’s roomy, varied features.',
    bad:'Notice the pivot from what people assume to what Axiom-7 actually contains.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:0, variant:3, type:'mc',
    passage:'To brew a cup, Reyes first heats the water. Then she adds the grounds. Finally, she waits four minutes before pressing the filter down.',
    q:'How is the text primarily structured?',
    opts:['As a comparison of two drinks','As an ordered sequence of steps','As a list of unrelated facts','As an argument for drinking coffee'],
    ans:1,
    good:'The words “first,” “Then,” and “Finally” mark an ordered sequence of steps.',
    bad:'The signal words at the start of each sentence reveal the structure.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:1, variant:2, type:'mc',
    passage:'Reyes opens her log by admitting she had underestimated how much solitude would affect her focus. She then explains that, rather than fighting the effect, she redesigned her schedule around it—clustering demanding tasks in the hours when her attention held and saving routine work for the rest.',
    q:'Which choice best describes the overall structure of the text?',
    opts:['It lists the station’s modules in order of size.','It compares Reyes’s focus with ARIA’s processing speed.','It admits a misjudgment, then describes how Reyes adapted her routine in response.','It defines a scientific term and gives examples.'],
    ans:2,
    good:'Reyes concedes she underestimated solitude’s effect, then explains her adaptive redesign—an admission followed by a response.',
    bad:'Track the move from admitting a misjudgment to describing what she did about it.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:1, variant:3, type:'mc',
    passage:'The passage begins with a familiar sight: flocks of starlings wheeling in vast, shifting shapes at dusk. It then asks how thousands of birds coordinate without a leader, and surveys the leading answer—that each bird simply tracks the motion of a few near neighbors, producing patterns no single bird directs.',
    q:'What is the main purpose of the text?',
    opts:['To prove that starlings have a single leader','To give instructions for photographing birds','To argue that flocking is harmful to starlings','To open with a phenomenon, pose a question about it, and present an explanation'],
    ans:3,
    good:'The text presents the flocking sight, asks how it happens, and offers the neighbor-tracking explanation.',
    bad:'Follow the arc from the opening image to the question and its answer.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:2, variant:2, type:'mc',
    passage:'Reyes’s essay dwells for pages on a chipped ceramic mug she keeps beside the console, describing its weight and the way it catches the light. Only in closing does she reveal that it belonged to Commander Vasquez, and that she keeps it filled with pens she never uses—a small daily ritual, she confesses, that lets her feel she is not entirely alone in the room.',
    q:'Which choice best describes the function of the final sentences in the text as a whole?',
    opts:['They give instructions for cleaning the mug.','They recast the ordinary object described earlier as an emotionally charged link to Vasquez.','They introduce an unrelated new subject.','They summarize the station’s daily schedule.'],
    ans:1,
    good:'The ending reveals the mug’s tie to Vasquez and its comforting ritual, transforming an ordinary object into an emotional link.',
    bad:'Consider how the closing changes the reader’s understanding of the mug described earlier.' },
  { skill:'cs-text-structure', name:'Text Structure & Purpose', domain:'rw-cs', tier:2, variant:3, type:'mc',
    passage:'The article first lays out the popular belief that human memory works like a video recording, faithfully storing events for later replay. It concedes that memory can be vivid and detailed. Yet it spends its latter half on studies showing that each act of recall subtly rewrites the memory—concluding that remembering is better understood as reconstruction than as playback.',
    q:'Which choice best describes the overall structure of the text?',
    opts:['It proves that memory does not exist.','It presents a common belief, grants it partly, then revises it toward a reconstructive account.','It ranks types of memory by how long they last.','It argues that vivid memories are always false.'],
    ans:1,
    good:'The text states the recording view, grants memory’s vividness, then adds evidence to reach a reconstructive conclusion.',
    bad:'The piece does not reject memory; note how it revises the recording view toward reconstruction.' },

  // ===== cs-cross-text =====
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:0, variant:2, type:'mc',
    passage:'Text 1: Reyes wants to store the extra harvest in the cold bay to keep it fresh for the crew’s awakening.\n\nText 2: ARIA recommends eating the extra harvest now, warning that the cold bay’s aging seals may let the food spoil anyway.',
    q:'How would ARIA (Text 2) most likely respond to Reyes’s plan in Text 1?',
    opts:['By agreeing that the cold bay is the safest option','By denying that there is any extra harvest','By cautioning that the cold bay’s failing seals could spoil the stored food','By suggesting the food never be eaten'],
    ans:2,
    good:'Text 2 opposes storing the harvest specifically because the aging seals may let it spoil.',
    bad:'Look at the reason Text 2 gives against storing the food in the cold bay.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:0, variant:3, type:'mc',
    passage:'Text 1: One technician argues the station should switch to the new sensors because they respond faster.\n\nText 2: Another technician notes that the new sensors drain twice the power of the old ones.',
    q:'Based on the texts, the two technicians would most likely disagree about whether',
    opts:['the new sensors respond faster','the station should switch to the new sensors','the station has any sensors','ARIA installed the sensors'],
    ans:1,
    good:'Text 1 favors switching to the new sensors; Text 2 raises a reason against it, so they disagree on switching.',
    bad:'Find the action one text recommends and the other gives reason to resist.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:1, variant:2, type:'mc',
    passage:'Text 1: Vasquez’s logs maintain that a commander should share every piece of bad news with the crew at once, since people perform best when fully informed.\n\nText 2: Reyes counters that, for a crew already under strain, releasing alarming news all at once can paralyze rather than empower; better, she writes, to disclose it in a sequence people can absorb.',
    q:'Which choice best describes the relationship between the two texts?',
    opts:['Text 2 qualifies Text 1 by arguing that how information is delivered can matter as much as sharing it.','Text 2 simply restates Text 1 with new examples.','Text 2 fully agrees that all news should be shared at once.','Text 2 denies that the crew should ever be informed.'],
    ans:0,
    good:'Reyes still favors informing the crew but stresses pacing the delivery, qualifying Vasquez’s all-at-once rule.',
    bad:'Notice Reyes shifts the emphasis to timing rather than rejecting disclosure outright.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:1, variant:3, type:'mc',
    passage:'Text 1: A designer proposes covering the station’s hull with new solar panels to increase power generation.\n\nText 2: A second designer accepts that the panels would generate more power but warns that their added weight would slow the station’s maneuvering thrusters.',
    q:'How does Text 2 respond to the proposal in Text 1?',
    opts:['By denying that the panels generate power','By proposing a different kind of panel','By claiming the hull cannot hold panels','By accepting the main benefit while raising a practical drawback'],
    ans:3,
    good:'Text 2 grants the power benefit but adds a drawback about slowed maneuvering—an accept-but-complicate response.',
    bad:'The second designer concedes one point and cautions about another; identify both moves.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:2, variant:2, type:'mc',
    passage:'Text 1: Vasquez argued that strict, unvarying routines are what keep a crew safe, since habit prevents dangerous improvisation in a crisis.\n\nText 2: Reyes, after years alone, writes that rigid routine can dull the very alertness it aims to protect; a crew that only ever follows habit, she warns, may miss the novel fault that no routine anticipated.',
    q:'Based on the texts, Reyes would most likely regard Vasquez’s faith in strict routine as',
    opts:['completely wrong, since routines serve no purpose','valuable but incomplete, because unbroken habit can blunt alertness to the unexpected','identical to her own view of crew safety','proof that crews need no procedures at all'],
    ans:1,
    good:'Reyes credits routine’s aim but warns it can dull alertness, so she sees it as useful yet overlooking the novel fault.',
    bad:'Reyes doesn’t dismiss routine; weigh the limitation she adds about unanticipated faults.' },
  { skill:'cs-cross-text', name:'Cross-Text Connections', domain:'rw-cs', tier:2, variant:3, type:'mc',
    passage:'Text 1: One economist argues that raising a city’s minimum wage reduces employment because businesses respond by hiring fewer workers.\n\nText 2: Another finds that in several cities modest increases were followed by little change in employment, and suggests that businesses often absorbed the cost through slightly higher prices or lower turnover instead.',
    q:'Which choice best describes how Text 2 complicates the argument in Text 1?',
    opts:['It denies that wages affect businesses in any way.','It offers evidence and alternative responses suggesting the predicted job losses need not follow.','It agrees exactly with Text 1’s prediction.','It argues that prices are unaffected by wages.'],
    ans:1,
    good:'Text 2 supplies evidence of little job change and names other adjustments, complicating Text 1’s claim of inevitable losses.',
    bad:'Text 2 doesn’t deny an effect; it shows the predicted job cuts may not occur—identify that complication.' },

  // ===== eoi-synthesis =====
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:0, variant:2, type:'mc',
    passage:'Notes:\n• The greenhouse is a module aboard Axiom-7.\n• It grows food for the crew.\n• Reyes tends it each morning.',
    q:'The student wants to introduce the greenhouse to an audience unfamiliar with it. Which choice best accomplishes this goal?',
    opts:['The greenhouse, a module aboard Axiom-7, grows food for the crew and is tended each morning by Reyes.','It grows food.','Reyes tends it.','The module is aboard the station.'],
    ans:0,
    good:'This choice combines what the greenhouse is, what it does, and who tends it into one clear introduction.',
    bad:'The goal asks to introduce the greenhouse fully, so pick the option covering all three facts.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:0, variant:3, type:'mc',
    passage:'Notes:\n• The reactor powers the entire station.\n• It runs on a small store of fuel.\n• ARIA monitors it constantly.',
    q:'The student wants to explain the reactor’s role. Which choice best accomplishes this goal?',
    opts:['The reactor is small.','The reactor, which runs on a small store of fuel, powers the entire station and is monitored constantly by ARIA.','ARIA is watchful.','Fuel is stored on the station.'],
    ans:1,
    good:'This option states what the reactor does, what it runs on, and how it is monitored, fulfilling the goal.',
    bad:'Choose the sentence that says what the reactor is for and how it is watched.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:1, variant:2, type:'mc',
    passage:'Notes:\n• The station stores three types of coolant.\n• Type C is used only for the reactor.\n• The reactor is the station’s most critical system.\n• Types A and B are used for minor equipment.',
    q:'The student wants to emphasize the importance of Type C coolant specifically. Which choice best accomplishes this goal?',
    opts:['Because Type C coolant serves the reactor, the station’s most critical system, it is the most vital of the three coolants stored.','The station stores three types of coolant.','Types A and B are used for minor equipment.','The station has several coolants.'],
    ans:0,
    good:'This choice foregrounds Type C’s importance by tying it to the station’s most critical system.',
    bad:'The goal singles out Type C; pick the option stressing why it matters, not the general list.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:1, variant:3, type:'mc',
    passage:'Notes:\n• Reyes keeps a personal journal.\n• The journal records her moods and small victories.\n• She rereads it when discouraged.\n• Rereading it reminds her of problems she has already solved.',
    q:'The student wants to highlight how the journal helps Reyes today. Which choice best accomplishes this goal?',
    opts:['Reyes keeps a personal journal aboard the station.','The journal records her moods and small victories.','Reyes writes in the journal often.','When discouraged, Reyes rereads her journal, which reminds her of the problems she has already solved.'],
    ans:3,
    good:'This choice centers on Reyes’s present use of the journal and the encouragement it gives her.',
    bad:'The goal is about how the journal helps her now, so choose the sentence focused on her use of it.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:2, variant:2, type:'mc',
    passage:'Notes:\n• Reyes once ran every system check manually.\n• She distrusted letting ARIA run them unsupervised.\n• After a year without a single ARIA error, she let ARIA run the routine checks alone.\n• She now spends the freed time on repairs only a human can do.',
    q:'The student wants to present the change as a turning point in how Reyes divides work with ARIA. Which choice best accomplishes this goal?',
    opts:['Reyes ran system checks manually for a long time.','ARIA is capable of running checks.','After a year of flawless performance convinced Reyes to hand ARIA the routine checks, she redirected her own time to repairs only a human can do—reshaping how the two divide the work.','Some repairs require a human.'],
    ans:2,
    good:'This choice frames ARIA’s reliability as prompting a lasting redivision of labor, matching the turning-point goal.',
    bad:'The goal wants a turning point in how work is divided; pick the option linking the outcome to that change.' },
  { skill:'eoi-synthesis', name:'Rhetorical Synthesis', domain:'rw-eoi', tier:2, variant:3, type:'mc',
    passage:'Notes:\n• Coral reefs shelter many fish species.\n• Warmer water can cause corals to expel their algae and pale.\n• Researchers surveyed reefs after three separate warm spells.\n• Reefs with more shade from ledges paled less each time.',
    q:'The student wants to make a generalization about coral paling supported by the researchers’ surveys. Which choice best accomplishes this goal?',
    opts:['Coral reefs shelter many fish species.','The repeated surveys support a broader pattern: corals tend to pale in warmer water, but shaded reefs consistently paled less than exposed ones.','Researchers surveyed reefs after three warm spells.','Warmer water can make corals pale.'],
    ans:1,
    good:'This choice states a general pattern—shade reduces paling across warm spells—and grounds it in the surveys, fulfilling the goal.',
    bad:'The goal asks for a supported generalization, not a single fact; choose the option stating the overall pattern.' },

  // ===== eoi-transitions =====
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:0, variant:2, type:'mc',
    passage:'The storage bay was freezing cold. Reyes, _____, put on her insulated gloves before entering.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['therefore','however','instead','nevertheless'],
    ans:0,
    good:'The cold causes Reyes to put on gloves, so a cause-effect transition like “therefore” fits.',
    bad:'The second sentence is a response to the cold, so look for a cause-and-effect connector.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:0, variant:3, type:'mc',
    passage:'ARIA predicted the repair would take an hour. _____, it was finished in twenty minutes.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['As a result','Instead','Likewise','For example'],
    ans:1,
    good:'The actual time contradicts the prediction, so a contrast transition like “Instead” fits.',
    bad:'Notice the outcome differs from what ARIA predicted, so choose a word signaling that difference.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:1, variant:2, type:'mc',
    passage:'The backup generator has sat unused for years and has never once been tested. _____, Reyes lists it in her reports as a dependable safeguard, a habit she has begun to question.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['Accordingly','For instance','In short','Even so'],
    ans:3,
    good:'Despite the untested generator, Reyes still calls it dependable, so a concessive transition like “Even so” fits.',
    bad:'The second sentence runs against what the first would lead you to expect—choose a word marking that tension.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:1, variant:3, type:'mc',
    passage:'In ordinary daylight the mineral looks like dull gray stone. _____, under the station’s ultraviolet lamps it glows a vivid green.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['By contrast','Similarly','Therefore','In addition'],
    ans:0,
    good:'Dull gray in daylight versus vivid green under ultraviolet is a contrast, so “By contrast” fits.',
    bad:'Compare the mineral’s appearance in the two kinds of light; the sentences oppose each other.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:2, variant:2, type:'mc',
    passage:'Reyes suspected the strange vibration came from an unbalanced fan. After hours of testing, the fan proved perfectly balanced. The tremor, _____, originated in a loose mounting bracket she had dismissed as solid.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['instead','likewise','for example','as a result'],
    ans:0,
    good:'The true source differs from her suspicion, so “instead” marks the correction.',
    bad:'The sentence replaces the expected cause with the real one; choose the word that signals a correction.' },
  { skill:'eoi-transitions', name:'Transitions', domain:'rw-eoi', tier:2, variant:3, type:'mc',
    passage:'Certain fungi thread through forest soil, linking the roots of separate trees. Such networks were once treated as a marginal curiosity. _____, they may govern how whole forests share nutrients and warnings.',
    q:'Which choice completes the text with the most logical transition?',
    opts:['For example','In fact','Nonetheless','Meanwhile'],
    ans:1,
    good:'The final sentence intensifies the point—these “curiosities” may govern the forest—so “In fact” fits.',
    bad:'The last sentence escalates rather than merely contrasting; look for an emphatic connector.' },

  // ===== sec-boundaries =====
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:0, variant:2, type:'mc',
    passage:'Reyes tightened the last bolt _____ she stepped back to admire the finished panel.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['bolt,','bolt','bolt and,','bolt; then'],
    ans:3,
    good:'Two independent clauses need a semicolon (or a comma plus conjunction); “bolt; then” correctly joins them.',
    bad:'Two complete sentences are being joined, so a bare comma between them would be a splice.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:0, variant:3, type:'mc',
    passage:'Before the crew entered cryosleep _____ each of them recorded a short message for the archive.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:[',',';','.','and'],
    ans:0,
    good:'An introductory dependent clause is set off from the main clause with a comma.',
    bad:'The opening “Before” clause is not a complete sentence, so join it with a comma, not a period or semicolon.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:1, variant:2, type:'mc',
    passage:'Reyes relied on one tool above all others _____ the multimeter that could diagnose a fault in seconds.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:[',',':',', so','; yet'],
    ans:1,
    good:'A colon correctly introduces the specifying phrase that follows an independent clause.',
    bad:'The second part names the “one tool,” which calls for a mark that introduces an elaboration.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:1, variant:3, type:'mc',
    passage:'The oldest module _____ built decades before the others _____ still houses the station’s most reliable air scrubber.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:[', ... ,','— ... (no mark)','(no mark) ... —',', ... (no mark)'],
    ans:0,
    good:'The nonessential phrase “built decades before the others” must be set off by a matching pair of commas.',
    bad:'The inserted description is nonessential and needs punctuation on both sides, not just one.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:2, variant:2, type:'mc',
    passage:'Reyes preferred the manual override _____ it responded instantly to her commands _____ the automated system, she found, hesitated for a full second before acting.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['; ... ;',', ... ,',': ... ,','; ... :'],
    ans:0,
    good:'Independent clauses stand on each side, so semicolons correctly separate the statements without comma splices.',
    bad:'Each segment is a complete sentence; joining them with mere commas would create splices.' },
  { skill:'sec-boundaries', name:'Boundaries', domain:'rw-sec', tier:2, variant:3, type:'mc',
    passage:'The station keeps three emergency caches _____ medical, mechanical, and nutritional _____ in separate modules so that a single breach cannot destroy them all.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['— ... —',', ... ;','; ... ;',': ... :'],
    ans:0,
    good:'A pair of dashes cleanly brackets the interrupting list “medical, mechanical, and nutritional,” which itself contains commas.',
    bad:'The inserted list already uses commas, so it needs a stronger matching pair of marks around it.' },

  // ===== sec-form-structure =====
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:0, variant:2, type:'mc',
    passage:'Neither of the two backup drives _____ working when Reyes finally checked them.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['are','were','was','have been'],
    ans:2,
    good:'The subject “Neither” is singular, so it takes the singular verb “was.”',
    bad:'Identify the true subject—“Neither”—and match the verb to it, not to “drives.”' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:0, variant:3, type:'mc',
    passage:'When the sensors and the alarm both failed, _____ left Reyes without any warning of the leak.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['it','they','she','one'],
    ans:1,
    good:'The plural antecedent “the sensors and the alarm” requires the plural pronoun “they.”',
    bad:'Two things failed together, so the pronoun referring to them should be plural.' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:1, variant:2, type:'mc',
    passage:'The tools that Reyes inherited from the earlier crew _____ stored in a locker she rarely opens.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['is','was','has been','are'],
    ans:3,
    good:'The plural subject “tools” takes the plural present-tense verb “are.”',
    bad:'Look past the intervening clause to the plural subject “tools” when choosing the verb.' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:1, variant:3, type:'mc',
    passage:'_____ toward the console, Reyes noticed the warning light before ARIA could announce it.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['Hurrying','To hurry','Hurried','Because it hurried'],
    ans:0,
    good:'“Hurrying” correctly modifies Reyes, the subject who is doing the hurrying and noticing the light.',
    bad:'The introductory phrase must describe the sentence’s subject; check who is actually hurrying.' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:2, variant:2, type:'mc',
    passage:'Either the worn gaskets or the corroded valve _____ responsible for the slow pressure loss Reyes had been chasing for weeks.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['are','were','is','have been'],
    ans:2,
    good:'With “either...or,” the verb agrees with the nearer subject, “valve,” which is singular, so “is” is correct.',
    bad:'In “either...or” constructions, match the verb to the subject closest to it.' },
  { skill:'sec-form-structure', name:'Form, Structure, and Sense', domain:'rw-sec', tier:2, variant:3, type:'mc',
    passage:'Reyes admired the old station not only for its rugged design but also for _____ generations of engineers who had built it.',
    q:'Which choice completes the text so that it conforms to the conventions of Standard English?',
    opts:['how it honored','its honoring of','honoring','the way that it honored'],
    ans:1,
    good:'Parallelism with the noun phrase “its rugged design” requires another noun phrase, “its honoring of,” after “but also for.”',
    bad:'The “not only...but also” pair must join parallel elements; match the noun phrase after “for.”' }
);
