// SAT Math: Advanced Math skill bank — Axiom-7 — variants C & D
(window.SKILL_BANK = window.SKILL_BANK || []).push(
  // ---------- adv-equiv-expr ----------
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:0, variant:2, type:'mc',
    q:'A ventilation routine on Axiom-7 computes <strong>4(x − 2) + 3x</strong>. Which expression is equivalent?',
    opts:['x − 8','7x − 6','7x − 8','7x − 2'], ans:2,
    good:'Distribute: 4x − 8 + 3x = 7x − 8. Airflow balanced.',
    bad:'4(x − 2) = 4x − 8, then add 3x to get 7x − 8.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:0, variant:3, type:'mc',
    q:'A docking script evaluates <strong>2(3x + 5) − 4</strong>. Which expression is equivalent?',
    opts:['6x + 2','6x + 6','9x + 6','6x − 6'], ans:1,
    good:'6x + 10 − 4 = 6x + 6. Docking aligned.',
    bad:'2(3x + 5) = 6x + 10, then subtract 4 to get 6x + 6.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:1, variant:2, type:'mc',
    q:'A thermal model uses <strong>3x(x + 2) − 2(x² − 4)</strong>. Which expression is equivalent?',
    opts:['x² + 6x − 8','5x² + 6x + 8','x² + 8','x² + 6x + 8'], ans:3,
    good:'3x² + 6x − 2x² + 8 = x² + 6x + 8. Thermal model verified.',
    bad:'Expand: 3x² + 6x and −2x² + 8, then combine to x² + 6x + 8.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:1, variant:3, type:'mc',
    q:'The stabilizer firmware computes <strong>(x + 4)² − 8x</strong>. Which expression is equivalent?',
    opts:['x² + 16','x² + 8x + 16','x² − 16','2x² + 16'], ans:0,
    good:'(x + 4)² = x² + 8x + 16; subtracting 8x leaves x² + 16.',
    bad:'Expand the square to x² + 8x + 16, then the −8x cancels the 8x, leaving x² + 16.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:2, variant:2, type:'mc',
    q:'For x ≠ 4, a gyro ratio is <strong>(x² − 16)/(x − 4)</strong>. Which expression is equivalent?',
    opts:['x − 4','x + 4','x² + 4','x + 16'], ans:1,
    good:'Factor: (x + 4)(x − 4), cancel (x − 4) to get x + 4.',
    bad:'x² − 16 = (x + 4)(x − 4). Cancel (x − 4), leaving x + 4.' },
  { skill:'adv-equiv-expr', name:'Equivalent expressions', domain:'m-adv', tier:2, variant:3, type:'mc',
    q:'For x + 3 ≠ 0, a fuel ratio is <strong>(2x² + 5x − 3)/(x + 3)</strong>. Which expression is equivalent?',
    opts:['x − 1','2x + 1','2x − 1','2x − 3'], ans:2,
    good:'2x² + 5x − 3 = (2x − 1)(x + 3), so the ratio is 2x − 1.',
    bad:'Factor: (2x − 1)(x + 3) = 2x² + 5x − 3. Cancel (x + 3) to get 2x − 1.' },

  // ---------- adv-polynomials ----------
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:0, variant:2, type:'mc',
    q:'Two coil outputs sum to <strong>(4x² + x) + (2x² − 3x)</strong>. Which expression is the total?',
    opts:['8x² − 2x','6x² + 4x','6x² − 2x','6x² − 3x'], ans:2,
    good:'Combine like terms: 6x² and −2x. Total locked in.',
    bad:'Add the x² terms (4 + 2 = 6) and the x terms (1 − 3 = −2): 6x² − 2x.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:0, variant:3, type:'mc',
    q:'The lab computes <strong>(6x² − 2x + 5) − (x² − 4x + 2)</strong>. Which expression is the result?',
    opts:['5x² − 2x + 3','5x² + 2x + 3','5x² + 2x + 7','7x² + 2x + 3'], ans:1,
    good:'Distribute the minus: 6x² − x² = 5x², −2x + 4x = 2x, 5 − 2 = 3.',
    bad:'Flip every sign of the second polynomial: 5x² + 2x + 3.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:1, variant:2, type:'mc',
    q:'A greenhouse area expands as <strong>(x + 6)(x − 3)</strong>. Which expression is equivalent?',
    opts:['x² − 3x − 18','x² + 3x + 18','x² − 18','x² + 3x − 18'], ans:3,
    good:'FOIL: x² − 3x + 6x − 18 = x² + 3x − 18.',
    bad:'Multiply out: x² + 6x − 3x − 18 = x² + 3x − 18.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:1, variant:3, type:'input',
    q:'A thrust model is <strong>q(x) = x³ + 2x² − 5</strong>. To release the clamp, enter <strong>q(2)</strong>.',
    ans:11, ph:'q(2) = ?',
    good:'q(2) = 8 + 8 − 5 = 11. Clamp released.',
    bad:'Substitute x = 2: 2³ + 2(2²) − 5 = 8 + 8 − 5 = 11.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:2, variant:2, type:'mc',
    q:'A heat-shield tile side is (3x − 2) units, so its area is <strong>(3x − 2)²</strong>. Which expression is equivalent?',
    opts:['9x² + 4','9x² − 6x + 4','9x² − 12x + 4','3x² − 12x + 4'], ans:2,
    good:'(3x − 2)² = 9x² − 12x + 4. Middle term is 2·(3x)·(−2).',
    bad:'Square the binomial: (3x)² − 2(3x)(2) + 2² = 9x² − 12x + 4.' },
  { skill:'adv-polynomials', name:'Operations with polynomials', domain:'m-adv', tier:2, variant:3, type:'mc',
    q:'The nav computer multiplies <strong>(x² − x + 2)(x + 4)</strong>. Which expression is the product?',
    opts:['x³ − 3x² − 2x + 8','x³ + 3x² − 2x + 8','x³ + 3x² + 2x + 8','x³ + 3x² − 2x − 8'], ans:1,
    good:'x³ − x² + 2x + 4x² − 4x + 8 = x³ + 3x² − 2x + 8.',
    bad:'Distribute (x + 4) through the trinomial, then combine: x³ + 3x² − 2x + 8.' },

  // ---------- adv-factoring ----------
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:0, variant:2, type:'mc',
    q:'Factor <strong>x² + 8x + 15</strong> to partition a sensor array.',
    opts:['(x + 2)(x + 6)','(x + 1)(x + 15)','(x + 3)(x + 5)','(x − 3)(x − 5)'], ans:2,
    good:'3 + 5 = 8 and 3 × 5 = 15. Array partitioned.',
    bad:'Find two numbers multiplying to 15 and adding to 8: 3 and 5.' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:0, variant:3, type:'mc',
    q:'A panel stress term is <strong>x² − 25</strong>. Which is the factored form?',
    opts:['(x − 5)²','(x + 5)(x − 5)','(x + 5)²','(x + 25)(x − 1)'], ans:1,
    good:'Difference of squares: x² − 25 = (x + 5)(x − 5).',
    bad:'x² − 25 is a difference of squares: (x + 5)(x − 5).' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:1, variant:2, type:'mc',
    q:'Factor the drift polynomial <strong>x² + 3x − 10</strong>.',
    opts:['(x − 5)(x + 2)','(x + 10)(x − 1)','(x − 5)(x − 2)','(x + 5)(x − 2)'], ans:3,
    good:'5 + (−2) = 3 and 5 × (−2) = −10. Drift decomposed.',
    bad:'You need a pair multiplying to −10 and summing to 3: 5 and −2.' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:1, variant:3, type:'input',
    q:'The polynomial <strong>x² − 9x + 20</strong> factors as (x − 4)(x − k). The hatch code is <strong>k</strong>.',
    ans:5, ph:'k = ?',
    good:'4 × 5 = 20 and 4 + 5 = 9, so k = 5. Hatch open.',
    bad:'Since 4 · k = 20 and 4 + k = 9, k = 5.' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:2, variant:2, type:'mc',
    q:'Factor the receiver polynomial <strong>3x² + 10x + 8</strong>.',
    opts:['(3x + 2)(x + 4)','(3x + 4)(x + 2)','(3x − 4)(x − 2)','(x + 4)(x + 2)'], ans:1,
    good:'(3x + 4)(x + 2) = 3x² + 6x + 4x + 8 = 3x² + 10x + 8.',
    bad:'Check by expanding: (3x + 4)(x + 2) gives 3x² + 10x + 8.' },
  { skill:'adv-factoring', name:'Factoring quadratics', domain:'m-adv', tier:2, variant:3, type:'mc',
    q:'The actuator torque is <strong>6x² + x − 2</strong>. Which is the factored form?',
    opts:['(6x + 2)(x − 1)','(3x − 2)(2x + 1)','(3x + 2)(2x − 1)','(3x + 1)(2x − 2)'], ans:2,
    good:'(3x + 2)(2x − 1) = 6x² − 3x + 4x − 2 = 6x² + x − 2.',
    bad:'Expand each option; only (3x + 2)(2x − 1) yields 6x² + x − 2.' },

  // ---------- adv-solve-quad ----------
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:0, variant:2, type:'input',
    q:'A viewport has area x² = 81 square units. Enter the positive solution of <strong>x² = 81</strong>.',
    ans:9, ph:'x = ?',
    good:'√81 = 9. Viewport sized at 9 units.',
    bad:'Take the square root of both sides: x = 9 (the positive root).' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:0, variant:3, type:'input',
    q:'The vault code is the positive solution of <strong>x² − 2x − 35 = 0</strong>.',
    ans:7, ph:'x = ?',
    good:'(x − 7)(x + 5) = 0, so x = 7 or x = −5. Code: 7.',
    bad:'Factor: (x − 7)(x + 5) = 0. The positive solution is 7.' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:1, variant:2, type:'input',
    q:'A rover locks when <strong>x² − 9x + 20 = 0</strong>. Enter the <strong>larger</strong> solution.',
    ans:5, ph:'x = ?',
    good:'(x − 4)(x − 5) = 0; solutions 4 and 5. Larger: 5.',
    bad:'Factor: (x − 4)(x − 5) = 0, giving x = 4 or x = 5. The larger is 5.' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:1, variant:3, type:'input',
    q:'The pressure valve opens at the positive solution of <strong>3x² − 48 = 0</strong>.',
    ans:4, ph:'x = ?',
    good:'3x² = 48, x² = 16, so x = 4. Valve open.',
    bad:'Divide by 3: x² = 16, so the positive solution is x = 4.' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:2, variant:2, type:'input',
    q:'A trajectory satisfies <strong>x² − 10x + 21 = 0</strong>. The uplink key is the <strong>sum</strong> of its two solutions.',
    ans:10, ph:'sum = ?',
    good:'For x² + bx + c, the solutions sum to −b = 10. (They are 3 and 7.)',
    bad:'The solutions are 3 and 7 (or use sum = −b/a = 10). Sum: 10.' },
  { skill:'adv-solve-quad', name:'Solving quadratic equations', domain:'m-adv', tier:2, variant:3, type:'input',
    q:'The equation <strong>x² + kx + 16 = 0</strong> has exactly one real solution. Enter the <strong>positive</strong> value of k.',
    ans:8, ph:'k = ?',
    good:'Discriminant zero: k² − 64 = 0, so k = 8.',
    bad:'One solution means k² − 4(1)(16) = 0, so k² = 64 and k = 8.' },

  // ---------- adv-quad-graphs ----------
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:0, variant:2, type:'mc',
    q:'A probe arc follows <strong>y = (x + 2)² − 5</strong>. What is the vertex of the graph?',
    opts:['(2, −5)','(−2, 5)','(2, 5)','(−2, −5)'], ans:3,
    good:'Vertex form y = (x − h)² + k has vertex (h, k) = (−2, −5).',
    bad:'Rewrite as (x − (−2))² + (−5): the vertex is (−2, −5).' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:0, variant:3, type:'mc',
    q:'The power curve is <strong>y = 3x² − 2x + 1</strong>. Which describes the graph?',
    opts:['It opens upward','It opens downward','It is a straight line','It is a circle'], ans:0,
    good:'The x² coefficient is 3 (positive), so the parabola opens upward.',
    bad:'A positive leading coefficient (3) makes the parabola open upward.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:1, variant:2, type:'input',
    q:'A cargo pod arc is <strong>y = x² − 10x + 16</strong>. Enter the <strong>larger</strong> x-intercept.',
    ans:8, ph:'x = ?',
    good:'y = (x − 2)(x − 8), so intercepts at x = 2 and x = 8. Larger: 8.',
    bad:'Set y = 0 and factor: (x − 2)(x − 8) = 0. The larger x-intercept is 8.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:1, variant:3, type:'input',
    q:'Fuel use follows <strong>y = x² − 4x + 3</strong>. Enter the x-coordinate of the vertex (the minimum-use time).',
    ans:2, ph:'x = ?',
    good:'x = −b/(2a) = 4/2 = 2. Minimum use at t = 2.',
    bad:'The vertex x-coordinate is −b/(2a) = 4/2 = 2.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:2, variant:2, type:'input',
    q:'Signal strength is <strong>y = −(x − 3)² + 16</strong>. Enter the <strong>maximum</strong> value of y.',
    ans:16, ph:'max y = ?',
    good:'The vertex (3, 16) is the highest point since the parabola opens downward. Max: 16.',
    bad:'Vertex form shows the peak at (3, 16); with a negative lead coefficient the maximum is 16.' },
  { skill:'adv-quad-graphs', name:'Graphs of quadratics', domain:'m-adv', tier:2, variant:3, type:'mc',
    q:'The reactor curve is <strong>y = x² + 6x + 11</strong>. Which statement is true about its graph?',
    opts:['It has two x-intercepts and a maximum value','It has one x-intercept at x = −3','It has no x-intercepts and a minimum value of 2','It has no x-intercepts and a minimum value of 11'], ans:2,
    good:'Complete the square: y = (x + 3)² + 2. Minimum 2, never reaches 0.',
    bad:'y = (x + 3)² + 2, so the vertex is (−3, 2): minimum value 2, and since 2 > 0 there are no x-intercepts.' },

  // ---------- adv-exponential ----------
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:0, variant:2, type:'input',
    q:'A culture in the Axiom-7 lab starts with 3 colonies and <strong>doubles every hour</strong>. How many colonies after 4 hours?',
    ans:48, ph:'colonies = ?',
    good:'3 → 6 → 12 → 24 → 48. That is 3 · 2⁴ = 48.',
    bad:'Doubling four times: 3 · 2⁴ = 3 · 16 = 48.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:0, variant:3, type:'mc',
    q:'Which function models a cell that <strong>loses 20% of its charge</strong> each cycle, starting at 200 units?',
    opts:['y = 200(1.2)^t','y = 200 − 20t','y = 200(0.8)^t','y = 200(0.2)^t'], ans:2,
    good:'Keeping 80% each cycle means multiplying by 0.8 repeatedly.',
    bad:'Losing 20% leaves 80%, so the decay factor is 0.8: y = 200(0.8)^t.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:1, variant:2, type:'input',
    q:'Spore count follows <strong>P = 100(2)^t</strong> where t is days. Enter P when t = 3.',
    ans:800, ph:'P = ?',
    good:'100 · 8 = 800 spores. Seal the chamber!',
    bad:'2³ = 8, and 100 · 8 = 800.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:1, variant:3, type:'input',
    q:'An isotope in the core <strong>halves every 5 hours</strong>. Starting at 480 grams, how many grams remain after 15 hours?',
    ans:60, ph:'grams = ?',
    good:'15 hours = 3 half-lives: 480 → 240 → 120 → 60.',
    bad:'15 / 5 = 3 half-lives, so 480 · (1/2)³ = 60 grams.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:2, variant:2, type:'input',
    q:'A colony grows <strong>10% per day</strong>, compounding daily, from 400 cells. Enter the cell count after 2 days.',
    ans:484, ph:'cells = ?',
    good:'400 · 1.1² = 400 · 1.21 = 484. Compound growth, not 400 + 20%.',
    bad:'Apply the factor twice: 400 · 1.1 = 440, then 440 · 1.1 = 484.' },
  { skill:'adv-exponential', name:'Exponential growth & decay', domain:'m-adv', tier:2, variant:3, type:'mc',
    q:'A culture of 200 cells <strong>triples every 5 hours</strong>. Which expression gives the count after t hours?',
    opts:['200 · 3^(5t)','200 + 3^(t/5)','200 · 3^(t/5)','200 · 5^(t/3)'], ans:2,
    good:'t/5 counts the number of tripling periods, so 200 · 3^(t/5).',
    bad:'After t hours there have been t/5 triplings: 200 · 3^(t/5). Check t = 5 gives 600.' },

  // ---------- adv-radicals ----------
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:0, variant:2, type:'input',
    q:'The airlock code is <strong>√81 + √49</strong>.',
    ans:16, ph:'code = ?',
    good:'9 + 7 = 16. Airlock sealed.',
    bad:'√81 = 9 and √49 = 7, so the code is 16.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:0, variant:3, type:'mc',
    q:'For x > 0, which is equivalent to <strong>x^(1/3)</strong>?',
    opts:['x/3','∛x','1/x³','3x'], ans:1,
    good:'A 1/3 exponent is exactly a cube root.',
    bad:'A rational exponent of 1/3 means the cube root: x^(1/3) = ∛x.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:1, variant:2, type:'input',
    q:'A sensor gain is <strong>∛64 · √16</strong>. Enter the gain.',
    ans:16, ph:'gain = ?',
    good:'4 · 4 = 16. Sensor calibrated.',
    bad:'∛64 = 4 and √16 = 4, so the product is 16.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:1, variant:3, type:'mc',
    q:'Which is equivalent to <strong>√72</strong>?',
    opts:['8√3','2√6','36√2','6√2'], ans:3,
    good:'√72 = √36 · √2 = 6√2.',
    bad:'Pull out the largest perfect square: 72 = 36 · 2, so √72 = 6√2.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:2, variant:2, type:'input',
    q:'The encryption key is <strong>27^(2/3)</strong>.',
    ans:9, ph:'key = ?',
    good:'Cube root of 27 is 3; 3² = 9. Key accepted.',
    bad:'27^(2/3) = (27^(1/3))² = 3² = 9.' },
  { skill:'adv-radicals', name:'Radicals & rational exponents', domain:'m-adv', tier:2, variant:3, type:'mc',
    q:'For x > 0, which is equivalent to <strong>√(x⁸)</strong>?',
    opts:['x⁴','x^(1/8)','x²','x⁶'], ans:0,
    good:'√(x⁸) = x^(8/2) = x⁴.',
    bad:'Halve the exponent under a square root: x^(8/2) = x⁴.' },

  // ---------- adv-rational-eq ----------
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:0, variant:2, type:'input',
    q:'A ration split satisfies <strong>20/x = 4</strong>. Solve for x, the number of crew.',
    ans:5, ph:'x = ?',
    good:'20 = 4x, so x = 5 crew members.',
    bad:'Multiply both sides by x: 20 = 4x, so x = 5.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:0, variant:3, type:'input',
    q:'A telemetry check requires <strong>√x = 7</strong>. Solve for x.',
    ans:49, ph:'x = ?',
    good:'Square both sides: x = 49.',
    bad:'Square both sides of √x = 7 to get x = 49.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:1, variant:2, type:'input',
    q:'Coolant flow satisfies <strong>8/(x − 1) = 2</strong>. Solve for x.',
    ans:5, ph:'x = ?',
    good:'8 = 2(x − 1), so x − 1 = 4 and x = 5.',
    bad:'Multiply both sides by (x − 1): 8 = 2x − 2, so x = 5.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:1, variant:3, type:'input',
    q:'The beacon fires when <strong>√(3x + 1) = 4</strong>. Solve for x.',
    ans:5, ph:'x = ?',
    good:'3x + 1 = 16, so 3x = 15 and x = 5.',
    bad:'Square both sides: 3x + 1 = 16, giving x = 5.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:2, variant:2, type:'input',
    q:'The oxygen mix satisfies <strong>x/(x − 2) = 3</strong>. Solve for x.',
    ans:3, ph:'x = ?',
    good:'x = 3(x − 2) = 3x − 6, so 2x = 6 and x = 3 (and 3 ≠ 2, so it is valid).',
    bad:'Cross-multiply: x = 3x − 6, so 2x = 6 and x = 3.' },
  { skill:'adv-rational-eq', name:'Rational & radical equations', domain:'m-adv', tier:2, variant:3, type:'input',
    q:'The vault opens when <strong>√(x + 7) = x − 5</strong>. Enter the valid solution. (Watch for the extraneous one!)',
    ans:9, ph:'x = ?',
    good:'Squaring gives x² − 11x + 18 = 0, so x = 2 or x = 9. Only x = 9 checks: √16 = 4 = 9 − 5.',
    bad:'Square both sides: x + 7 = x² − 10x + 25, so x² − 11x + 18 = 0 and x = 2 or 9. x = 2 fails the original equation, so x = 9.' },

  // ---------- adv-absolute ----------
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:0, variant:2, type:'input',
    q:'Temperature drift satisfies <strong>|x − 3| = 7</strong>. Enter the <strong>larger</strong> solution.',
    ans:10, ph:'x = ?',
    good:'x − 3 = ±7, so x = 10 or x = −4. Larger: 10.',
    bad:'Split into x − 3 = 7 and x − 3 = −7: x = 10 or x = −4. The larger is 10.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:0, variant:3, type:'input',
    q:'A sensor reads <strong>|x| + 2 = 9</strong>. Enter the positive solution.',
    ans:7, ph:'x = ?',
    good:'|x| = 7, so the positive solution is 7.',
    bad:'Subtract 2: |x| = 7, so x = 7 or −7. Positive: 7.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:1, variant:2, type:'input',
    q:'Gyro error satisfies <strong>|2x − 4| = 8</strong>. Enter the <strong>larger</strong> solution.',
    ans:6, ph:'x = ?',
    good:'2x − 4 = ±8, so x = 6 or x = −2. Larger: 6.',
    bad:'Two cases: 2x − 4 = 8 gives x = 6; 2x − 4 = −8 gives x = −2. Larger: 6.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:1, variant:3, type:'mc',
    q:'Safe cabin pressure satisfies <strong>|x − 4| &lt; 2</strong>. Which describes all solutions?',
    opts:['2 < x < 6','x < 2 or x > 6','x < 6','−2 < x < 2'], ans:0,
    good:'Within 2 of 4 means between 2 and 6.',
    bad:'|x − 4| < 2 means −2 < x − 4 < 2, so 2 < x < 6.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:2, variant:2, type:'input',
    q:'Two beacons match when <strong>|2x + 1| = |x + 7|</strong>. Enter the <strong>positive</strong> solution.',
    ans:6, ph:'x = ?',
    good:'2x + 1 = x + 7 gives x = 6; 2x + 1 = −(x + 7) gives x = −8/3. Positive: 6.',
    bad:'Set the insides equal or opposite: x = 6 or x = −8/3. The positive solution is 6.' },
  { skill:'adv-absolute', name:'Absolute value equations & inequalities', domain:'m-adv', tier:2, variant:3, type:'mc',
    q:'The radiation alarm triggers when <strong>|x − 5| ≥ 3</strong>. Which describes the alarm zone?',
    opts:['2 ≤ x ≤ 8','x ≥ 8 only','x ≤ 2 only','x ≤ 2 or x ≥ 8'], ans:3,
    good:'At least 3 away from 5 means x ≤ 2 or x ≥ 8.',
    bad:'|x − 5| ≥ 3 splits into x − 5 ≥ 3 or x − 5 ≤ −3: x ≥ 8 or x ≤ 2.' },

  // ---------- adv-functions ----------
  { skill:'adv-functions', name:'Function notation & composition', domain:'m-adv', tier:0, variant:2, type:'input',
    q:'The shield function is <strong>f(x) = x² − 2</strong>. Enter f(4) to set shield strength.',
    ans:14, ph:'f(4) = ?',
    good:'f(4) = 16 − 2 = 14. Shields at full.',
    bad:'Substitute x = 4: 4² − 2 = 14.' },
  { skill:'adv-functions', name:'Function notation & composition', domain:'m-adv', tier:0, variant:3, type:'input',
    q:'Given <strong>f(x) = 3x − 1</strong> and <strong>g(x) = x²</strong>, enter <strong>g(f(2))</strong>.',
    ans:25, ph:'g(f(2)) = ?',
    good:'f(2) = 5, then g(5) = 25. Composition complete.',
    bad:'Work inside out: f(2) = 3(2) − 1 = 5, then g(5) = 5² = 25.' },
  { skill:'adv-functions', name:'Function notation & composition', domain:'m-adv', tier:1, variant:2, type:'input',
    q:'Nav routines: <strong>g(x) = x + 3</strong>, <strong>f(x) = x² + 1</strong>. Enter <strong>f(g(1))</strong>.',
    ans:17, ph:'f(g(1)) = ?',
    good:'g(1) = 4, then f(4) = 16 + 1 = 17.',
    bad:'Inside first: g(1) = 4. Then f(4) = 4² + 1 = 17.' },
  { skill:'adv-functions', name:'Function notation & composition', domain:'m-adv', tier:1, variant:3, type:'mc',
    q:'If <strong>f(x) = x²</strong> and <strong>g(x) = x − 2</strong>, which is <strong>f(g(x))</strong>?',
    opts:['x² − 2','x² + 4','(x − 2)²','x² − 4'], ans:2,
    good:'Plug g into f: f(x − 2) = (x − 2)².',
    bad:'f(g(x)) means substitute g(x) into f: (x − 2)².' },
  { skill:'adv-functions', name:'Nonlinear systems', domain:'m-adv', tier:2, variant:2, type:'input',
    q:'Two flight paths meet where <strong>y = x²</strong> and <strong>y = 3x + 4</strong>. Enter the y-coordinate of the intersection with <strong>positive</strong> x.',
    ans:16, ph:'y = ?',
    good:'x² − 3x − 4 = 0 gives x = 4 or −1. At x = 4, y = 16.',
    bad:'Set x² = 3x + 4: (x − 4)(x + 1) = 0, so x = 4. Then y = 4² = 16.' },
  { skill:'adv-functions', name:'Nonlinear systems', domain:'m-adv', tier:2, variant:3, type:'input',
    q:'The curves <strong>y = x² − 5x + 8</strong> and <strong>y = x + 3</strong> intersect at two points. Enter the <strong>sum</strong> of their x-coordinates.',
    ans:6, ph:'sum = ?',
    good:'x² − 6x + 5 = 0 has roots 1 and 5; sum 6 (also −b/a).',
    bad:'Set equal: x² − 6x + 5 = 0, so (x − 1)(x − 5) = 0. Sum: 1 + 5 = 6.' }
);
